"""§19 Active Directory — 99 endpoints per 19_ad.md.
11 sections: discovery, cred access, kerberoast/asrep, lateral, privesc,
AD CS ESC1-15, delegation, coercion, persistence, defense evasion, modern CVEs.
"""
from tools._pack_common import make_advisory_router

T = [
    # §1 Discovery / Enumeration (16)
    ("bloodhound_collect", "BloodHound + SharpHound collection.", "MEDIUM", "5.5"),
    ("bloodhound_python", "BloodHound.py.", "MEDIUM", "5.5"),
    ("ad_module_powershell", "AD PowerShell module enum.", "INFO", "0.0"),
    ("powerview_enum", "PowerView enumeration.", "INFO", "0.0"),
    ("adexplorer_snapshot", "AdExplorer snapshot.", "INFO", "0.0"),
    ("ldapsearch_enum", "ldapsearch enumeration.", "INFO", "0.0"),
    ("net_user_dc_enum", "net user /domain enumeration.", "INFO", "0.0"),
    ("nltest_dclist", "nltest /dclist.", "INFO", "0.0"),
    ("dsquery_enum", "dsquery enumeration.", "INFO", "0.0"),
    ("adsi_query", "ADSI query.", "INFO", "0.0"),
    ("rubeus_klist", "Rubeus klist.", "INFO", "0.0"),
    ("rid_brute_lookupsid", "RID brute via lookupsid.", "MEDIUM", "5.5"),
    ("smb_share_enum_ad", "SMB share enumeration.", "MEDIUM", "5.5"),
    ("group_membership_enum", "Group membership enum.", "INFO", "0.0"),
    ("sid_history_enum", "SID history enumeration.", "MEDIUM", "5.5"),
    ("gpo_enum_pingcastle", "GPO enum (PingCastle).", "INFO", "0.0"),
    # §2 Credential Access (13)
    ("mimikatz_sekurlsa", "Mimikatz sekurlsa::logonpasswords.", "CRITICAL", "9.5"),
    ("mimikatz_sekurlsa_tickets", "Mimikatz sekurlsa::tickets.", "CRITICAL", "9.0"),
    ("mimikatz_lsa_dump", "Mimikatz lsadump.", "CRITICAL", "9.0"),
    ("mimikatz_dcsync", "Mimikatz lsadump::dcsync.", "CRITICAL", "9.5"),
    ("dpapi_master_key_dump", "DPAPI master key dump.", "HIGH", "8.0"),
    ("dpapi_unprotect_blob", "DPAPI unprotect blob.", "HIGH", "8.0"),
    ("vault_credential_dump", "Vault credential dump.", "HIGH", "7.5"),
    ("ntds_dit_dump_secretsdump", "NTDS.dit dump via secretsdump.", "CRITICAL", "9.5"),
    ("sam_offline_secretsdump", "SAM offline dump.", "HIGH", "8.0"),
    ("lsass_dump_procdump", "LSASS dump via procdump.", "CRITICAL", "9.0"),
    ("lsass_dump_nanodump", "LSASS dump via NanoDump.", "CRITICAL", "9.0"),
    ("credential_guard_audit", "Credential Guard audit.", "MEDIUM", "5.5"),
    ("manual_cred_access_chain", "Manual cred access chain.", "INFO", "0.0"),
    # §3 Kerberoasting / AS-REP (9)
    ("kerberoasting_getuserspns", "Kerberoasting (GetUserSPNs).", "HIGH", "7.5"),
    ("kerberoasting_rubeus", "Kerberoasting via Rubeus.", "HIGH", "7.5"),
    ("asrep_roasting_getnpusers", "AS-REP roasting (GetNPUsers).", "HIGH", "7.5"),
    ("targeted_kerberoast_no_preauth", "Targeted Kerberoast.", "HIGH", "7.5"),
    ("kerberos_pre_auth_brute", "Kerberos pre-auth password brute.", "HIGH", "7.5"),
    ("hashcat_13100_kerberos", "hashcat -m 13100 Kerberos.", "MEDIUM", "5.5"),
    ("hashcat_18200_asrep", "hashcat -m 18200 AS-REP.", "MEDIUM", "5.5"),
    ("kerberos_constrained_deleg_audit", "Constrained delegation audit.", "HIGH", "7.5"),
    ("manual_kerberos_attack_chain", "Manual Kerberos chain.", "INFO", "0.0"),
    # §4 Lateral Movement (10)
    ("psexec_impacket", "PsExec via impacket.", "HIGH", "8.0"),
    ("wmiexec_impacket", "WMIExec via impacket.", "HIGH", "8.0"),
    ("smbexec_impacket", "SMBExec via impacket.", "HIGH", "8.0"),
    ("atexec_impacket", "AtExec via impacket.", "HIGH", "8.0"),
    ("dcomexec_impacket", "DCOMExec via impacket.", "HIGH", "8.0"),
    ("evil_winrm", "evil-winrm.", "HIGH", "8.0"),
    ("rdp_via_xfreerdp", "RDP via xfreerdp.", "HIGH", "7.5"),
    ("psremoting_invokecommand", "PSRemoting / Invoke-Command.", "HIGH", "7.5"),
    ("crackmapexec_netexec_lateral", "Crackmapexec/NetExec lateral.", "HIGH", "7.5"),
    ("manual_lateral_chain", "Manual lateral chain.", "INFO", "0.0"),
    # §5 Privilege Escalation (12)
    ("dcsync_replication_rights", "DCSync via replication rights.", "CRITICAL", "9.5"),
    ("dcshadow_attack", "DCShadow attack.", "CRITICAL", "9.5"),
    ("genericwrite_takeover", "GenericWrite ACE takeover.", "HIGH", "8.0"),
    ("genericall_takeover", "GenericAll ACE takeover.", "HIGH", "8.0"),
    ("writedacl_takeover", "WriteDacl ACE takeover.", "HIGH", "8.0"),
    ("write_owner_takeover", "WriteOwner ACE takeover.", "HIGH", "8.0"),
    ("forcechangepassword_takeover", "ForceChangePassword takeover.", "HIGH", "8.0"),
    ("self_member_takeover", "Self → group member takeover.", "HIGH", "8.0"),
    ("addmember_takeover", "AddMember takeover.", "HIGH", "8.0"),
    ("allextendedrights_takeover", "AllExtendedRights takeover.", "HIGH", "8.0"),
    ("shadow_credentials_certificate", "Shadow Credentials (cert-based).", "HIGH", "8.0"),
    ("badsuccessor_dmsa_advisory", "BadSuccessor / dMSA advisory.", "CRITICAL", "9.0"),
    # §6 AD CS Abuse ESC1-15 (15)
    ("adcs_esc1_san", "ESC1: SAN supply via template.", "CRITICAL", "9.0"),
    ("adcs_esc2_any_purpose", "ESC2: Any-Purpose EKU.", "CRITICAL", "9.0"),
    ("adcs_esc3_request_template_delegated", "ESC3: Request agent template.", "CRITICAL", "9.0"),
    ("adcs_esc4_template_dacl", "ESC4: Template DACL writable.", "HIGH", "8.0"),
    ("adcs_esc5_pki_dacl", "ESC5: PKI object DACL writable.", "HIGH", "8.0"),
    ("adcs_esc6_uschema", "ESC6: EDITF_ATTRIBUTESUBJECTALTNAME2.", "CRITICAL", "9.0"),
    ("adcs_esc7_ca_role", "ESC7: CA admin → arbitrary cert.", "CRITICAL", "9.5"),
    ("adcs_esc8_ntlm_relay_web_enroll", "ESC8: NTLM relay to Web Enrollment.", "CRITICAL", "9.0"),
    ("adcs_esc9_no_strong_mapping", "ESC9: No-strong-mapping.", "HIGH", "8.0"),
    ("adcs_esc10_weak_explicit_mapping", "ESC10: Weak explicit mapping.", "HIGH", "8.0"),
    ("adcs_esc11_ntlm_relay_icpr_rpc", "ESC11: NTLM relay to ICPR RPC.", "CRITICAL", "9.0"),
    ("adcs_esc12_yubihsm_kspweak", "ESC12: YubiHSM KSP weak.", "MEDIUM", "5.5"),
    ("adcs_esc13_oid_group_link", "ESC13: OID group link.", "HIGH", "8.0"),
    ("adcs_esc14_user_certificate_dn", "ESC14: User certificate DN mapping.", "HIGH", "8.0"),
    ("adcs_esc15_certifried_cve_2022_26923", "ESC15: Certifried (CVE-2022-26923).", "CRITICAL", "9.0"),
    # §7 Delegation Abuse (8)
    ("unconstrained_delegation_capture", "Unconstrained delegation TGT capture.", "HIGH", "8.0"),
    ("constrained_delegation_s4u2self", "Constrained delegation S4U2self.", "HIGH", "8.0"),
    ("rbcd_resource_based", "RBCD (resource-based).", "HIGH", "8.0"),
    ("printer_bug_unconstrained_pivot", "Printer Bug + unconstrained pivot.", "HIGH", "8.0"),
    ("petitpotam_coercion", "PetitPotam coercion.", "HIGH", "8.0"),
    ("dfscoerce_coercion", "DFSCoerce coercion.", "HIGH", "8.0"),
    ("efs_rpc_coercion", "EFSRPC coercion (PetitPotam variant).", "HIGH", "8.0"),
    ("manual_delegation_chain", "Manual delegation chain.", "INFO", "0.0"),
    # §8 Coercion Techniques (7)
    ("petitpotam_msrprn_coerce", "PetitPotam MS-RPRN coerce.", "HIGH", "8.0"),
    ("printerbug_lock_machine", "PrinterBug lock machine.", "HIGH", "8.0"),
    ("printnightmare_coerce", "PrintNightmare coerce.", "HIGH", "8.0"),
    ("dfscoerce_msdfsnm", "DFSCoerce MS-DFSNM.", "HIGH", "8.0"),
    ("efs_rpc_lock", "EFSRPC lock.", "HIGH", "8.0"),
    ("ntlm_relay_to_ldap", "NTLM relay to LDAP.", "HIGH", "8.0"),
    ("manual_coercion_chain", "Manual coercion chain.", "INFO", "0.0"),
    # §9 Persistence (9)
    ("golden_ticket", "Golden Ticket (krbtgt forgery).", "CRITICAL", "9.5"),
    ("silver_ticket", "Silver Ticket (service-specific).", "HIGH", "8.5"),
    ("skeleton_key", "Skeleton Key.", "CRITICAL", "9.5"),
    ("dsrm_password_persistence", "DSRM password persistence.", "HIGH", "8.0"),
    ("acl_persistence_genericall", "ACL persistence (GenericAll).", "HIGH", "8.0"),
    ("group_policy_writable_persist", "Writable GPO persistence.", "HIGH", "8.0"),
    ("sidhistory_injection_persist", "SID history injection persistence.", "HIGH", "8.0"),
    ("admin_sdholder_persist", "AdminSDHolder ACE persistence.", "HIGH", "8.0"),
    ("manual_persistence_chain", "Manual persistence chain.", "INFO", "0.0"),
    # §10 Defense Evasion (5)
    ("event_log_tamper", "Event log tampering.", "HIGH", "7.5"),
    ("amsi_bypass_ad_context", "AMSI bypass in AD context.", "HIGH", "7.5"),
    ("etw_disable_ad_context", "ETW disable in AD context.", "HIGH", "7.5"),
    ("scriptblock_logging_bypass", "ScriptBlock logging bypass.", "HIGH", "7.5"),
    ("manual_defense_evasion_chain", "Manual defense evasion chain.", "INFO", "0.0"),
    # §11 Modern AD CVEs 2024+ (9)
    ("cve_2024_38077_ldapnightmare", "LDAPNightmare (CVE-2024-49113).", "HIGH", "7.5"),
    ("cve_2024_43554_ad_ksp", "AD KSP CVE (2024).", "HIGH", "7.5"),
    ("cve_2024_38063_ipv6_rce", "IPv6 RCE (CVE-2024-38063).", "CRITICAL", "9.8"),
    ("badsuccessor_dmsa_takeover", "BadSuccessor dMSA takeover.", "CRITICAL", "9.0"),
    ("cve_2023_28252_clfs_lpe", "CLFS LPE (CVE-2023-28252).", "HIGH", "7.8"),
    ("cve_2022_33679_kerberos", "Kerberos PAC (CVE-2022-33679).", "HIGH", "8.0"),
    ("cve_2024_26218_ad_lpe", "AD LPE (CVE-2024-26218).", "HIGH", "7.5"),
    ("certipy_modern_pattern", "Certipy modern attack patterns.", "HIGH", "8.0"),
    ("manual_modern_cve_chain", "Manual modern CVE chain.", "INFO", "0.0"),
]

router = make_advisory_router("ad", T,
    playbook_ref="See module_playbooks/19_ad.md.")


def register(app):
    app.include_router(router)
