ServerName          "ProFTPd 1.3.3c"
ServerType          standalone
DefaultServer       on
Port                21
Umask               022
MaxInstances        30
User                nobody
Group               nogroup
AllowOverwrite      on
TransferLog         /var/log/proftpd.log
SystemLog           /var/log/proftpd.log
<Anonymous /home/ftp>
    User            ftp
    Group           nogroup
    UserAlias       anonymous ftp
    RequireValidShell off
    MaxClients      10
    <Limit LOGIN>
        AllowAll
    </Limit>
</Anonymous>
