"""§24 Container/K8s — 103 endpoints per 24_container_k8s.md."""
from tools._pack_common import make_advisory_router

T = [
    # §1 Image/Registry (13)
    ("trivy_image", "Trivy image scan.", "MEDIUM", "5.5"),
    ("grype_image", "Grype image scan.", "MEDIUM", "5.5"),
    ("snyk_container", "Snyk container.", "MEDIUM", "5.5"),
    ("anchore_image", "Anchore image.", "MEDIUM", "5.5"),
    ("clair_image", "Clair image.", "MEDIUM", "5.5"),
    ("hadolint_dockerfile", "Hadolint Dockerfile.", "MEDIUM", "5.5"),
    ("image_secrets_scan", "Image secrets scan.", "HIGH", "8.0"),
    ("image_distroless_base", "Distroless/Wolfi base check.", "INFO", "0.0"),
    ("image_signing_cosign", "Cosign image signing.", "MEDIUM", "5.5"),
    ("registry_public_pull", "Registry public pull.", "HIGH", "7.5"),
    ("registry_anon_push", "Registry anonymous push.", "CRITICAL", "9.0"),
    ("image_provenance_slsa", "SLSA provenance check.", "MEDIUM", "5.5"),
    ("manual_image_review", "Manual image review.", "INFO", "0.0"),
    # §2 Dockerfile (10)
    ("dockerfile_root_user", "Dockerfile USER root.", "MEDIUM", "5.5"),
    ("dockerfile_no_user", "Dockerfile no USER directive.", "MEDIUM", "5.5"),
    ("dockerfile_ssh_in_image", "SSH server in image.", "MEDIUM", "5.5"),
    ("dockerfile_curl_pipe_bash", "curl | bash in RUN.", "HIGH", "7.0"),
    ("dockerfile_hardcoded_secret", "Hardcoded secret in image.", "CRITICAL", "9.0"),
    ("dockerfile_apt_unpinned", "apt without pinned versions.", "MEDIUM", "5.5"),
    ("dockerfile_no_healthcheck", "No HEALTHCHECK.", "INFO", "0.0"),
    ("dockerfile_multistage_audit", "Multi-stage build audit.", "INFO", "0.0"),
    ("dockerfile_copy_chown_audit", "COPY --chown audit.", "INFO", "0.0"),
    ("dockerfile_expose_audit", "EXPOSE port audit.", "INFO", "0.0"),
    # §3 Container Runtime (12)
    ("container_privileged", "Container privileged mode.", "CRITICAL", "9.0"),
    ("container_capadd_dangerous", "Dangerous CAP_ADD.", "HIGH", "8.0"),
    ("container_host_pid", "hostPID:true.", "HIGH", "8.0"),
    ("container_host_network", "hostNetwork:true.", "HIGH", "7.5"),
    ("container_host_ipc", "hostIPC:true.", "HIGH", "7.5"),
    ("container_hostpath_dangerous", "Dangerous hostPath mount.", "CRITICAL", "9.0"),
    ("container_docker_sock_mount", "Docker socket mounted.", "CRITICAL", "9.5"),
    ("container_runas_root", "runAsUser:0.", "HIGH", "7.5"),
    ("container_no_readonly_rootfs", "readOnlyRootFilesystem:false.", "MEDIUM", "5.5"),
    ("container_allow_priv_escalation", "allowPrivilegeEscalation:true.", "HIGH", "7.5"),
    ("container_seccomp_unset", "seccompProfile unset.", "MEDIUM", "5.5"),
    ("container_apparmor_unset", "AppArmor profile unset.", "MEDIUM", "5.5"),
    # §4 K8s Cluster Hardening CIS (17)
    ("kube_bench_master", "kube-bench master.", "MEDIUM", "5.5"),
    ("kube_bench_node", "kube-bench node.", "MEDIUM", "5.5"),
    ("kube_hunter", "kube-hunter.", "MEDIUM", "5.5"),
    ("k8s_anonymous_auth", "Anonymous-auth=true.", "CRITICAL", "9.0"),
    ("k8s_audit_logs_off", "Audit logs off.", "MEDIUM", "5.5"),
    ("k8s_etcd_unencrypted", "etcd unencrypted.", "HIGH", "7.5"),
    ("k8s_etcd_no_tls", "etcd no TLS.", "HIGH", "8.0"),
    ("k8s_api_server_insecure_port", "API server insecure port.", "CRITICAL", "9.0"),
    ("k8s_kubelet_anonymous_auth", "Kubelet anonymous-auth.", "CRITICAL", "9.0"),
    ("k8s_kubelet_unauth_token", "Kubelet unauth token.", "CRITICAL", "9.0"),
    ("k8s_admission_no_plugin", "Admission plugin missing.", "HIGH", "7.5"),
    ("k8s_psp_psa_disabled", "PSP/PSA disabled.", "HIGH", "7.5"),
    ("k8s_network_policy_absent", "NetworkPolicy absent.", "MEDIUM", "5.5"),
    ("k8s_certificate_rotation", "Certificate rotation audit.", "MEDIUM", "5.5"),
    ("k8s_tls_min_version", "TLS min version audit.", "MEDIUM", "5.5"),
    ("k8s_admission_controller_audit", "Admission controller audit.", "MEDIUM", "5.5"),
    ("k8s_cni_plugin_audit", "CNI plugin audit.", "MEDIUM", "5.5"),
    # §5 RBAC / Policy / OPA (12)
    ("rbac_cluster_admin_overuse", "cluster-admin overuse.", "HIGH", "8.0"),
    ("rbac_secret_get_anywhere", "Secrets GET cluster-wide.", "HIGH", "7.5"),
    ("rbac_pod_exec_create_overuse", "pod exec/create RBAC overuse.", "HIGH", "8.0"),
    ("rbac_node_proxy_overuse", "node/proxy overuse.", "HIGH", "7.5"),
    ("rbac_impersonate_users", "impersonate users RBAC.", "HIGH", "8.0"),
    ("rbac_pod_serviceaccount_token", "Pod SA token automount audit.", "MEDIUM", "5.5"),
    ("rbac_clusterrolebinding_audit", "ClusterRoleBinding audit.", "MEDIUM", "5.5"),
    ("rbac_aggregate_role_audit", "aggregateRule audit.", "MEDIUM", "5.5"),
    ("opa_gatekeeper_no_constraints", "Gatekeeper no constraints.", "MEDIUM", "5.5"),
    ("opa_kyverno_no_policies", "Kyverno no policies.", "MEDIUM", "5.5"),
    ("rbac_audit_via_rbac_tool", "rbac-tool audit.", "INFO", "0.0"),
    ("manual_rbac_review", "Manual RBAC review.", "INFO", "0.0"),
    # §6 Network Policy / Service Mesh (10)
    ("network_policy_default_deny", "Default-deny NetworkPolicy.", "MEDIUM", "5.5"),
    ("network_policy_egress_audit", "Egress NetworkPolicy audit.", "MEDIUM", "5.5"),
    ("service_mesh_mtls_off", "Service mesh mTLS off.", "HIGH", "7.5"),
    ("service_mesh_authz_open", "Service mesh authz open.", "HIGH", "7.5"),
    ("ingress_tls_audit", "Ingress TLS audit.", "MEDIUM", "5.5"),
    ("ingress_authz_open", "Ingress authz open.", "HIGH", "7.5"),
    ("istio_gateway_mtls_off", "Istio gateway mTLS off.", "HIGH", "7.5"),
    ("linkerd_authz_audit", "Linkerd authz audit.", "MEDIUM", "5.5"),
    ("envoy_filter_audit", "Envoy filter audit.", "MEDIUM", "5.5"),
    ("manual_network_policy_review", "Manual network policy review.", "INFO", "0.0"),
    # §7 Secrets Management (9)
    ("secrets_etcd_unencrypted", "etcd secrets unencrypted.", "HIGH", "7.5"),
    ("secrets_in_env_var", "Secrets in env vars.", "MEDIUM", "5.5"),
    ("secrets_in_configmap", "Secrets in ConfigMap (not Secret).", "HIGH", "7.5"),
    ("secrets_helm_values_leak", "Helm values.yaml secret leak.", "HIGH", "8.0"),
    ("secrets_kustomize_leak", "Kustomize secret leak.", "HIGH", "7.5"),
    ("external_secrets_audit", "ExternalSecrets audit.", "MEDIUM", "5.5"),
    ("vault_csi_audit", "Vault CSI audit.", "MEDIUM", "5.5"),
    ("sealed_secrets_audit", "SealedSecrets audit.", "MEDIUM", "5.5"),
    ("manual_secrets_review", "Manual secrets review.", "INFO", "0.0"),
    # §8 Container Escape CVEs (9) ⭐
    ("escape_leaky_vessels_runc_2024", "⭐ Leaky Vessels runc (CVE-2024-21626).", "HIGH", "8.6"),
    ("escape_containerd_cve_2022_23648", "⭐ containerd (CVE-2022-23648).", "HIGH", "7.5"),
    ("escape_docker_socket_mount", "Docker socket escape.", "CRITICAL", "9.5"),
    ("escape_cap_sys_admin_chain", "CAP_SYS_ADMIN escape chain.", "HIGH", "8.0"),
    ("escape_kernel_keyring", "Kernel keyring escape.", "HIGH", "7.5"),
    ("escape_proc_self_exe", "/proc/self/exe escape.", "HIGH", "7.5"),
    ("escape_user_namespace_audit", "User namespace audit.", "MEDIUM", "5.5"),
    ("escape_cgroup_release_agent", "cgroup release_agent escape.", "HIGH", "8.0"),
    ("manual_escape_research", "Manual escape research.", "INFO", "0.0"),
    # §9 Service Mesh & Ingress (8)
    ("istio_audit", "Istio audit.", "MEDIUM", "5.5"),
    ("linkerd_audit", "Linkerd audit.", "MEDIUM", "5.5"),
    ("consul_audit", "Consul audit.", "MEDIUM", "5.5"),
    ("envoy_config_audit", "Envoy config audit.", "MEDIUM", "5.5"),
    ("nginx_ingress_audit", "Nginx ingress audit.", "MEDIUM", "5.5"),
    ("traefik_audit", "Traefik audit.", "MEDIUM", "5.5"),
    ("haproxy_ingress_audit", "HAProxy ingress audit.", "MEDIUM", "5.5"),
    ("manual_mesh_review", "Manual mesh review.", "INFO", "0.0"),
    # §10 eBPF Runtime Detection (3) ⭐
    ("falco_runtime_audit", "⭐ Falco runtime audit.", "MEDIUM", "5.5"),
    ("tetragon_runtime_audit", "⭐ Tetragon (Cilium) runtime audit.", "MEDIUM", "5.5"),
    ("tracee_runtime_audit", "⭐ Tracee (Aqua) runtime audit.", "MEDIUM", "5.5"),
]

router = make_advisory_router("container_k8s", T,
    playbook_ref="See module_playbooks/24_container_k8s.md.")


def register(app):
    app.include_router(router)
