"""recon_waf_cdn -- isolated tool (Kali-style architecture).

Route: /api/recon/waf_cdn
Split from recon_module.py monolith by scripts/split_recon_module.py.
Failure here is quarantined by the healing autoloader -- other tools unaffected.
"""

import asyncio
import base64
import datetime
import hashlib
import re
import socket
from typing import Optional
import requests
import dns.resolver
import dns.asyncresolver
import whois as whois_lib
from fastapi import APIRouter, Depends
from tools._shared import (
    ScanRequest, verify_scan_quota, recon_host, safe_get, web_url,
)
import aiohttp as _aiohttp_crawl
import ssl as _ssl_mod

from fastapi import APIRouter, Depends

router = APIRouter()

_WAF_CDN_SIGS = [
    ("Cloudflare",             "CDN+WAF",  [("header:server", r"^cloudflare"), ("header:cf-ray", r".+"), ("cookie:__cf_bm", r".+")]),
    ("AWS CloudFront",         "CDN",      [("header:server", r"^CloudFront"), ("header:x-amz-cf-id", r".+"), ("header:via", r"CloudFront")]),
    ("Akamai",                 "CDN+WAF",  [("header:server", r"AkamaiGHost"), ("header:x-akamai-transformed", r".+")]),
    ("Fastly",                 "CDN",      [("header:fastly-debug-path", r".+"), ("header:x-served-by", r"^cache-"), ("header:x-fastly", r".+")]),
    ("Imperva Incapsula",      "WAF",      [("header:x-cdn", r"Incapsula"), ("cookie:visid_incap", r".+"), ("cookie:incap_ses", r".+")]),
    ("Sucuri CloudProxy",      "WAF",      [("header:server", r"Sucuri"), ("header:x-sucuri-id", r".+"), ("header:x-sucuri-cache", r".+")]),
    ("F5 BIG-IP ASM",          "WAF",      [("cookie:bigipserver", r".+"), ("cookie:ts[0-9a-f]+", r".+"), ("header:x-wa-info", r".+")]),
    ("Citrix NetScaler",       "WAF",      [("header:via", r"NS-CACHE"), ("cookie:ns_af", r".+"), ("cookie:citrix_ns_id", r".+")]),
    ("Barracuda",              "WAF",      [("header:server", r"^barra"), ("cookie:barra_counter_session", r".+")]),
    ("Fortinet FortiWeb",      "WAF",      [("header:server", r"FortiWeb"), ("cookie:fortiwafsid", r".+")]),
    ("StackPath",              "CDN",      [("header:server", r"StackPath"), ("header:x-cdn", r"stackpath")]),
    ("DDoS-Guard",             "WAF",      [("header:server", r"ddos-guard"), ("cookie:__ddg", r".+")]),
    ("Edgio (Verizon)",        "CDN",      [("header:server", r"^ECS"), ("header:x-ec-debug", r".+"), ("header:x-edgio-cache", r".+")]),
    ("Distil Networks",        "WAF",      [("header:x-distil-cs", r".+")]),
    ("Yundun (Aliyun)",        "WAF",      [("header:server", r"Yundun"), ("cookie:yd_cookie", r".+")]),
    ("Aliyun OSS",             "CDN",      [("header:server", r"AliyunOSS")]),
    ("Reblaze",                "WAF",      [("header:x-reblaze", r".+"), ("cookie:rbzid", r".+")]),
    ("Sangfor",                "WAF",      [("header:x-sf-", r".+")]),
    ("Wallarm",                "WAF",      [("header:server", r"nginx-wallarm"), ("header:x-wallarm-flag", r".+")]),
    ("Wordfence",              "WAF",      [("header:server", r"^wordfence"), ("body", r"Generated by Wordfence")]),
    ("ModSecurity",            "WAF",      [("header:server", r"Mod_Security|NOYB"), ("header:x-mod-security", r".+")]),
    ("NAXSI",                  "WAF",      [("header:x-data-origin", r"naxsi")]),
    ("Squid Proxy",            "Proxy",    [("header:server", r"^squid"), ("header:x-squid-error", r".+")]),
    ("Varnish",                "CDN",      [("header:server", r"^Varnish"), ("header:via", r"varnish"), ("header:x-varnish", r".+")]),
    ("Bunny.net",              "CDN",      [("header:server", r"BunnyCDN"), ("header:cdn-pullzone", r".+")]),
    ("KeyCDN",                 "CDN",      [("header:server", r"keycdn"), ("header:x-cache", r"keycdn")]),
    ("CDN77",                  "CDN",      [("header:server", r"CDN77"), ("header:x-77-cache", r".+")]),
    ("Tencent Cloud",          "CDN",      [("header:server", r"tencent|tcloud"), ("header:x-nws-log-uuid", r".+")]),
    ("Baidu Yunjiasu",         "WAF",      [("header:server", r"yunjiasu"), ("header:x-yunjiasu", r".+")]),
    ("Microsoft Azure Front Door", "CDN",  [("header:x-azure-ref", r".+"), ("header:x-azure-fdid", r".+")]),
    ("Google Frontend",        "CDN",      [("header:server", r"^gws$|gfe"), ("header:via", r"google")]),
    ("CacheFly",               "CDN",      [("header:server", r"CacheFly"), ("header:x-cf-cache", r".+")]),
    ("Section.io",             "CDN",      [("header:section-io-id", r".+")]),
    ("Limelight",              "CDN",      [("header:server", r"Limelight"), ("header:x-llnw", r".+")]),
    ("Sucuri (legacy)",        "WAF",      [("header:server", r"Sucuri/Cloudproxy")]),
    ("PerimeterX",             "WAF",      [("header:server", r"^px"), ("cookie:_px", r".+"), ("body", r"perimeterx")]),
    ("Datadome",               "WAF",      [("header:server", r"DataDome"), ("cookie:datadome", r".+")]),
    ("Kona Site Defender",     "WAF",      [("header:server", r"Kona"), ("header:x-akamai-rate-control", r".+")]),
    ("AWS WAF",                "WAF",      [("header:x-amzn-trace-id", r"Root="), ("header:x-amz-rid", r".+"), ("body", r"AWS WAF|Request blocked")]),
    ("Google Cloud Armor",     "WAF",      [("header:via", r"^[\d.]+ google"), ("body", r"Google Cloud Armor")]),
    ("Mod_Security (CRS)",     "WAF",      [("header:x-mod-security", r".+"), ("body", r"Mod_Security|NOYB")]),
    ("Anquanbao",              "WAF",      [("header:x-powered-by-anquanbao", r".+")]),
    ("BitNinja",               "WAF",      [("body", r"BitNinja|Security check by BitNinja")]),
    ("Bluedon IST",            "WAF",      [("header:server", r"bluedon")]),
    ("Comodo cWatch",          "WAF",      [("header:server", r"Protected by COMODO WAF")]),
    ("DOSarrest",              "WAF",      [("header:server", r"DOSarrest"), ("header:x-dis-request-id", r".+")]),
    ("DotDefender",            "WAF",      [("header:x-dotdefender-denied", r".+")]),
    ("eEye Digital Security",  "WAF",      [("header:server", r"SecureIIS")]),
    ("Greywizard",             "WAF",      [("header:server", r"greywizard")]),
    ("HyperGuard",             "WAF",      [("cookie:wlsessionkey", r".+")]),
    ("InstartLogic",           "WAF",      [("header:x-instart-request-id", r".+")]),
    ("ISA Server",             "WAF",      [("body", r"isaserror\.htm|Forefront TMG")]),
    ("Jiasule",                "WAF",      [("header:server", r"jiasule"), ("cookie:jsluid", r".+")]),
    ("KSWebShield",            "WAF",      [("header:server", r"KSWebShield")]),
    ("Mission Control",        "WAF",      [("header:server", r"Mission Control Application Shield")]),
    ("NetContinuum",           "WAF",      [("cookie:nci__sessionid", r".+")]),
    ("NewDefend",              "WAF",      [("header:server", r"NewDefend")]),
    ("NSFOCUS",                "WAF",      [("header:server", r"NSFocus")]),
    ("Powerful Firewall",      "WAF",      [("body", r"Powerful Firewall blocked")]),
    ("Profense",               "WAF",      [("header:server", r"profense"), ("cookie:profenceuserid", r".+")]),
    ("Safe3 Web Firewall",     "WAF",      [("header:x-powered-by", r"Safe3")]),
    ("SafeDog",                "WAF",      [("header:server", r"safedog"), ("header:x-powered-by", r"safedog")]),
    ("SecureSphere",           "WAF",      [("body", r"SecureSphere")]),
    ("USP-SES",                "WAF",      [("header:server", r"Secure Entry Server")]),
    ("WebKnight",              "WAF",      [("header:server", r"WebKnight")]),
]

@router.post("/api/recon/waf_cdn")
async def recon_waf_cdn(req: ScanRequest, _=Depends(verify_scan_quota)):
    url = web_url(req.target)
    r = safe_get(url, req=req, allow_redirects=True)
    if r is None:
        return {"ok": False, "detected": [], "skipped_reason": f"Could not reach {url}",
                "engine": "pure-Python (40 signatures)"}

    headers_lower = {k.lower(): str(v) for k, v in r.headers.items()}
    cookies_lower = {c.name.lower(): c.value for c in r.cookies}
    body = (r.text or "")[:50000]

    detected = []
    for vendor, category, checks in _WAF_CDN_SIGS:
        matched_check = None
        for field, pattern in checks:
            if field.startswith("header:"):
                hname = field.split(":", 1)[1].lower()
                for hk, hv in headers_lower.items():
                    if hk == hname or (hname.endswith("-") and hk.startswith(hname)):
                        if re.search(pattern, hv, re.I):
                            matched_check = f"{field}: {hv[:60]}"
                            break
                if matched_check: break
            elif field.startswith("cookie:"):
                cname = field.split(":", 1)[1].lower()
                for ck, cv in cookies_lower.items():
                    if ck == cname or (cname.endswith("-") and ck.startswith(cname)):
                        matched_check = f"{field}: {(cv or '')[:40] if cv else 'set'}"
                        break
                if matched_check: break
            elif field == "body":
                if re.search(pattern, body, re.I):
                    matched_check = f"body matched: {pattern[:40]}"
                    break
        if matched_check:
            detected.append({"vendor": vendor, "category": category, "evidence": matched_check})

    return {
        "ok": True,
        "detected": detected,
        "total_detected": len(detected),
        "signatures_checked": len(_WAF_CDN_SIGS),
        "engine": f"pure-Python (passive: headers + cookies + body, {len(_WAF_CDN_SIGS)} signatures)",
    }


def register(app):
    app.include_router(router)
