"""default_cred_paths — generated dev-time by Claude. Vuln module asset.
"""

DEFAULT_CRED_PATHS = [{'path': '/admin',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'username', 'password'],
  'priority': 10},
 {'path': '/login',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'Sign in', 'username'],
  'priority': 10},
 {'path': '/administrator',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'Administrator', 'username'],
  'priority': 10},
 {'path': '/dashboard',
  'category': 'generic_admin',
  'expected_indicators': ['Dashboard', 'Welcome', 'username'],
  'priority': 10},
 {'path': '/panel', 'category': 'generic_admin', 'expected_indicators': ['panel', 'login', 'username'], 'priority': 9},
 {'path': '/signin',
  'category': 'generic_admin',
  'expected_indicators': ['Sign in', 'username', 'password'],
  'priority': 9},
 {'path': '/admin/login',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'Admin', 'username'],
  'priority': 9},
 {'path': '/admin/index.php',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'Admin', 'password'],
  'priority': 9},
 {'path': '/admin/login.php',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'Admin', 'username'],
  'priority': 9},
 {'path': '/login.php',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'username', 'password'],
  'priority': 9},
 {'path': '/signin.php',
  'category': 'generic_admin',
  'expected_indicators': ['Sign in', 'username', 'password'],
  'priority': 8},
 {'path': '/admin.php',
  'category': 'generic_admin',
  'expected_indicators': ['Admin', 'login', 'username'],
  'priority': 8},
 {'path': '/controlpanel',
  'category': 'generic_admin',
  'expected_indicators': ['Control Panel', 'login', 'username'],
  'priority': 8},
 {'path': '/cp',
  'category': 'generic_admin',
  'expected_indicators': ['Control Panel', 'login', 'username'],
  'priority': 8},
 {'path': '/manage',
  'category': 'generic_admin',
  'expected_indicators': ['manage', 'login', 'username'],
  'priority': 8},
 {'path': '/management',
  'category': 'generic_admin',
  'expected_indicators': ['management', 'login', 'username'],
  'priority': 8},
 {'path': '/backend', 'category': 'generic_admin', 'expected_indicators': ['backend', 'login', 'Admin'], 'priority': 8},
 {'path': '/admin/dashboard',
  'category': 'generic_admin',
  'expected_indicators': ['Dashboard', 'Admin', 'Welcome'],
  'priority': 7},
 {'path': '/user/login',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'username', 'password'],
  'priority': 7},
 {'path': '/account/login',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'Account', 'username'],
  'priority': 7},
 {'path': '/auth/login',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'Auth', 'username'],
  'priority': 7},
 {'path': '/secure/login',
  'category': 'generic_admin',
  'expected_indicators': ['login', 'Secure', 'username'],
  'priority': 7},
 {'path': '/portal', 'category': 'generic_admin', 'expected_indicators': ['portal', 'login', 'Welcome'], 'priority': 7},
 {'path': '/portal/login',
  'category': 'generic_admin',
  'expected_indicators': ['portal', 'login', 'username'],
  'priority': 7},
 {'path': '/access',
  'category': 'generic_admin',
  'expected_indicators': ['Access', 'login', 'username'],
  'priority': 6},
 {'path': '/siteadmin',
  'category': 'generic_admin',
  'expected_indicators': ['Site Admin', 'login', 'username'],
  'priority': 6},
 {'path': '/webadmin',
  'category': 'generic_admin',
  'expected_indicators': ['Web Admin', 'login', 'username'],
  'priority': 6},
 {'path': '/adminpanel',
  'category': 'generic_admin',
  'expected_indicators': ['Admin Panel', 'login', 'username'],
  'priority': 6},
 {'path': '/memberlogin',
  'category': 'generic_admin',
  'expected_indicators': ['Member', 'login', 'username'],
  'priority': 5},
 {'path': '/admin/home',
  'category': 'generic_admin',
  'expected_indicators': ['Admin', 'Home', 'Welcome'],
  'priority': 5},
 {'path': '/wp-admin',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'login', 'username'],
  'priority': 10},
 {'path': '/wp-login.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'login', 'username'],
  'priority': 10},
 {'path': '/wp-admin/index.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'Dashboard', 'Welcome'],
  'priority': 9},
 {'path': '/wp-admin/admin.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'Admin', 'login'],
  'priority': 9},
 {'path': '/wp-admin/login.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'login', 'username'],
  'priority': 9},
 {'path': '/wordpress/wp-admin',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'login', 'username'],
  'priority': 8},
 {'path': '/wordpress/wp-login.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'login', 'username'],
  'priority': 8},
 {'path': '/blog/wp-admin',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'login', 'username'],
  'priority': 8},
 {'path': '/blog/wp-login.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'login', 'username'],
  'priority': 8},
 {'path': '/wp-admin/options-general.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'Settings', 'Admin'],
  'priority': 7},
 {'path': '/wp-admin/users.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'Users', 'Admin'],
  'priority': 7},
 {'path': '/wp-admin/plugins.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'Plugins', 'Admin'],
  'priority': 7},
 {'path': '/cms/wp-login.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'login', 'username'],
  'priority': 6},
 {'path': '/site/wp-admin',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'login', 'username'],
  'priority': 6},
 {'path': '/wp/wp-login.php',
  'category': 'wordpress',
  'expected_indicators': ['WordPress', 'login', 'username'],
  'priority': 6},
 {'path': '/administrator/index.php',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Joomla', 'Administrator', 'username'],
  'priority': 10},
 {'path': '/administrator/login',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Joomla', 'login', 'username'],
  'priority': 9},
 {'path': '/joomla/administrator',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Joomla', 'Administrator', 'username'],
  'priority': 9},
 {'path': '/user',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Drupal', 'login', 'username'],
  'priority': 9},
 {'path': '/user/login',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Drupal', 'login', 'username'],
  'priority': 9},
 {'path': '/admin/login/',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Drupal', 'login', 'Admin'],
  'priority': 8},
 {'path': '/index.php/admin',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Joomla', 'Admin', 'login'],
  'priority': 8},
 {'path': '/magento/admin',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Magento', 'Admin', 'login'],
  'priority': 9},
 {'path': '/magento/index.php/admin',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Magento', 'Admin', 'login'],
  'priority': 8},
 {'path': '/index.php/backend',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Magento', 'backend', 'login'],
  'priority': 8},
 {'path': '/backend/admin',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Magento', 'Admin', 'login'],
  'priority': 7},
 {'path': '/drupal/admin',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Drupal', 'Admin', 'login'],
  'priority': 7},
 {'path': '/drupal/user/login',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Drupal', 'login', 'username'],
  'priority': 7},
 {'path': '/store/admin',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Magento', 'Admin', 'login'],
  'priority': 7},
 {'path': '/shop/admin',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Admin', 'Shop', 'login'],
  'priority': 7},
 {'path': '/ecommerce/admin',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Admin', 'ecommerce', 'login'],
  'priority': 6},
 {'path': '/cms/admin',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['CMS', 'Admin', 'login'],
  'priority': 6},
 {'path': '/cms/administrator',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Joomla', 'Administrator', 'login'],
  'priority': 6},
 {'path': '/joomla/administrator/index.php',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Joomla', 'Administrator', 'login'],
  'priority': 6},
 {'path': '/admin/index',
  'category': 'joomla_drupal_magento',
  'expected_indicators': ['Admin', 'login', 'index'],
  'priority': 5},
 {'path': '/phpmyadmin',
  'category': 'database_admin',
  'expected_indicators': ['phpMyAdmin', 'login', 'username'],
  'priority': 10},
 {'path': '/phpmyadmin/index.php',
  'category': 'database_admin',
  'expected_indicators': ['phpMyAdmin', 'login', 'username'],
  'priority': 10},
 {'path': '/pma',
  'category': 'database_admin',
  'expected_indicators': ['phpMyAdmin', 'login', 'username'],
  'priority': 9},
 {'path': '/myadmin',
  'category': 'database_admin',
  'expected_indicators': ['phpMyAdmin', 'login', 'username'],
  'priority': 9},
 {'path': '/mysql', 'category': 'database_admin', 'expected_indicators': ['MySQL', 'login', 'username'], 'priority': 8},
 {'path': '/mysqladmin',
  'category': 'database_admin',
  'expected_indicators': ['MySQL', 'Admin', 'login'],
  'priority': 8},
 {'path': '/sqlbuddy',
  'category': 'database_admin',
  'expected_indicators': ['SQL Buddy', 'login', 'username'],
  'priority': 8},
 {'path': '/adminer',
  'category': 'database_admin',
  'expected_indicators': ['Adminer', 'login', 'username'],
  'priority': 9},
 {'path': '/adminer.php',
  'category': 'database_admin',
  'expected_indicators': ['Adminer', 'login', 'username'],
  'priority': 9},
 {'path': '/db', 'category': 'database_admin', 'expected_indicators': ['database', 'login', 'username'], 'priority': 8},
 {'path': '/dbadmin',
  'category': 'database_admin',
  'expected_indicators': ['DB Admin', 'login', 'username'],
  'priority': 8},
 {'path': '/database',
  'category': 'database_admin',
  'expected_indicators': ['database', 'login', 'username'],
  'priority': 7},
 {'path': '/db/admin', 'category': 'database_admin', 'expected_indicators': ['DB', 'Admin', 'login'], 'priority': 7},
 {'path': '/phpmyadmin2',
  'category': 'database_admin',
  'expected_indicators': ['phpMyAdmin', 'login', 'username'],
  'priority': 7},
 {'path': '/pma2',
  'category': 'database_admin',
  'expected_indicators': ['phpMyAdmin', 'login', 'username'],
  'priority': 7},
 {'path': '/mysql/admin',
  'category': 'database_admin',
  'expected_indicators': ['MySQL', 'Admin', 'login'],
  'priority': 7},
 {'path': '/pgadmin',
  'category': 'database_admin',
  'expected_indicators': ['pgAdmin', 'login', 'username'],
  'priority': 8},
 {'path': '/pgadmin4',
  'category': 'database_admin',
  'expected_indicators': ['pgAdmin', 'login', 'username'],
  'priority': 8},
 {'path': '/pgadmin/browser',
  'category': 'database_admin',
  'expected_indicators': ['pgAdmin', 'login', 'username'],
  'priority': 7},
 {'path': '/mongo',
  'category': 'database_admin',
  'expected_indicators': ['MongoDB', 'login', 'username'],
  'priority': 7},
 {'path': '/mongo-express',
  'category': 'database_admin',
  'expected_indicators': ['Mongo Express', 'login', 'username'],
  'priority': 8},
 {'path': '/redis', 'category': 'database_admin', 'expected_indicators': ['Redis', 'login', 'username'], 'priority': 7},
 {'path': '/redisadmin',
  'category': 'database_admin',
  'expected_indicators': ['Redis', 'Admin', 'login'],
  'priority': 7},
 {'path': '/rockmongo',
  'category': 'database_admin',
  'expected_indicators': ['RockMongo', 'login', 'username'],
  'priority': 6},
 {'path': '/mssql', 'category': 'database_admin', 'expected_indicators': ['MSSQL', 'login', 'username'], 'priority': 6},
 {'path': '/router', 'category': 'network_gear', 'expected_indicators': ['Router', 'login', 'username'], 'priority': 9},
 {'path': '/webconsole',
  'category': 'network_gear',
  'expected_indicators': ['Console', 'login', 'username'],
  'priority': 9},
 {'path': '/admin.html',
  'category': 'network_gear',
  'expected_indicators': ['Admin', 'login', 'username'],
  'priority': 9},
 {'path': '/system.html',
  'category': 'network_gear',
  'expected_indicators': ['System', 'login', 'username'],
  'priority': 8},
 {'path': '/config', 'category': 'network_gear', 'expected_indicators': ['Config', 'login', 'username'], 'priority': 8},
 {'path': '/cgi-bin/admin.cgi',
  'category': 'network_gear',
  'expected_indicators': ['Admin', 'login', 'username'],
  'priority': 8},
 {'path': '/index.html',
  'category': 'network_gear',
  'expected_indicators': ['login', 'username', 'Admin'],
  'priority': 7},
 {'path': '/setup', 'category': 'network_gear', 'expected_indicators': ['Setup', 'login', 'Admin'], 'priority': 8},
 {'path': '/setup.html', 'category': 'network_gear', 'expected_indicators': ['Setup', 'login', 'Admin'], 'priority': 8},
 {'path': '/setup.php', 'category': 'network_gear', 'expected_indicators': ['Setup', 'login', 'Admin'], 'priority': 7},
 {'path': '/cgi-bin/luci',
  'category': 'network_gear',
  'expected_indicators': ['LuCI', 'login', 'username'],
  'priority': 9},
 {'path': '/cgi-bin/luci/admin',
  'category': 'network_gear',
  'expected_indicators': ['LuCI', 'Admin', 'login'],
  'priority': 8},
 {'path': '/web/index.html',
  'category': 'network_gear',
  'expected_indicators': ['login', 'Admin', 'username'],
  'priority': 7},
 {'path': '/webui', 'category': 'network_gear', 'expected_indicators': ['Web UI', 'login', 'username'], 'priority': 8},
 {'path': '/management.html',
  'category': 'network_gear',
  'expected_indicators': ['Management', 'login', 'username'],
  'priority': 7},
 {'path': '/network',
  'category': 'network_gear',
  'expected_indicators': ['Network', 'login', 'username'],
  'priority': 7},
 {'path': '/network/admin',
  'category': 'network_gear',
  'expected_indicators': ['Network', 'Admin', 'login'],
  'priority': 7},
 {'path': '/cgi-bin/config.exp',
  'category': 'network_gear',
  'expected_indicators': ['Config', 'login', 'username'],
  'priority': 7},
 {'path': '/cisco/admin',
  'category': 'network_gear',
  'expected_indicators': ['Cisco', 'Admin', 'login'],
  'priority': 8},
 {'path': '/sysadmin',
  'category': 'network_gear',
  'expected_indicators': ['System Admin', 'login', 'username'],
  'priority': 7},
 {'path': '/fw/login',
  'category': 'network_gear',
  'expected_indicators': ['Firewall', 'login', 'username'],
  'priority': 7},
 {'path': '/cgi-bin/webproc',
  'category': 'network_gear',
  'expected_indicators': ['login', 'Admin', 'username'],
  'priority': 7},
 {'path': '/apply.cgi',
  'category': 'network_gear',
  'expected_indicators': ['login', 'Admin', 'username'],
  'priority': 6},
 {'path': '/cgi-bin/home.asp',
  'category': 'network_gear',
  'expected_indicators': ['login', 'Admin', 'username'],
  'priority': 6},
 {'path': '/cgi-bin/admin_login',
  'category': 'network_gear',
  'expected_indicators': ['Admin', 'login', 'username'],
  'priority': 6},
 {'path': '/console', 'category': 'cloud_saas', 'expected_indicators': ['Console', 'login', 'username'], 'priority': 9},
 {'path': '/control-panel',
  'category': 'cloud_saas',
  'expected_indicators': ['Control Panel', 'login', 'username'],
  'priority': 9},
 {'path': '/admin/console',
  'category': 'cloud_saas',
  'expected_indicators': ['Admin', 'Console', 'login'],
  'priority': 8},
 {'path': '/cloud/admin', 'category': 'cloud_saas', 'expected_indicators': ['Cloud', 'Admin', 'login'], 'priority': 8},
 {'path': '/saas/admin', 'category': 'cloud_saas', 'expected_indicators': ['SaaS', 'Admin', 'login'], 'priority': 7},
 {'path': '/manager', 'category': 'cloud_saas', 'expected_indicators': ['Manager', 'login', 'username'], 'priority': 8},
 {'path': '/manager/html',
  'category': 'cloud_saas',
  'expected_indicators': ['Tomcat', 'Manager', 'login'],
  'priority': 9},
 {'path': '/host-manager/html',
  'category': 'cloud_saas',
  'expected_indicators': ['Tomcat', 'Manager', 'login'],
  'priority': 8},
 {'path': '/admin/manage',
  'category': 'cloud_saas',
  'expected_indicators': ['Admin', 'Manage', 'login'],
  'priority': 7},
 {'path': '/service/admin',
  'category': 'cloud_saas',
  'expected_indicators': ['Service', 'Admin', 'login'],
  'priority': 7},
 {'path': '/cloud/console',
  'category': 'cloud_saas',
  'expected_indicators': ['Cloud', 'Console', 'login'],
  'priority': 7},
 {'path': '/api/admin', 'category': 'cloud_saas', 'expected_indicators': ['API', 'Admin', 'login'], 'priority': 7},
 {'path': '/tenant/admin',
  'category': 'cloud_saas',
  'expected_indicators': ['Tenant', 'Admin', 'login'],
  'priority': 6},
 {'path': '/billing/admin',
  'category': 'cloud_saas',
  'expected_indicators': ['Billing', 'Admin', 'login'],
  'priority': 6},
 {'path': '/identity/admin',
  'category': 'cloud_saas',
  'expected_indicators': ['Identity', 'Admin', 'login'],
  'priority': 6},
 {'path': '/cpanel',
  'category': 'hosting_panel',
  'expected_indicators': ['cPanel', 'login', 'username'],
  'priority': 10},
 {'path': '/cpanel/login',
  'category': 'hosting_panel',
  'expected_indicators': ['cPanel', 'login', 'username'],
  'priority': 9},
 {'path': '/whm', 'category': 'hosting_panel', 'expected_indicators': ['WHM', 'login', 'username'], 'priority': 10},
 {'path': '/whm/index.cgi',
  'category': 'hosting_panel',
  'expected_indicators': ['WHM', 'login', 'username'],
  'priority': 9},
 {'path': '/plesk', 'category': 'hosting_panel', 'expected_indicators': ['Plesk', 'login', 'username'], 'priority': 10},
 {'path': '/plesk/login',
  'category': 'hosting_panel',
  'expected_indicators': ['Plesk', 'login', 'username'],
  'priority': 9},
 {'path': '/directadmin',
  'category': 'hosting_panel',
  'expected_indicators': ['DirectAdmin', 'login', 'username'],
  'priority': 10},
 {'path': '/webmin',
  'category': 'hosting_panel',
  'expected_indicators': ['Webmin', 'login', 'username'],
  'priority': 10},
 {'path': '/webmin/session_login.cgi',
  'category': 'hosting_panel',
  'expected_indicators': ['Webmin', 'login', 'username'],
  'priority': 9},
 {'path': '/usermin',
  'category': 'hosting_panel',
  'expected_indicators': ['Usermin', 'login', 'username'],
  'priority': 9},
 {'path': '/usermin/session_login.cgi',
  'category': 'hosting_panel',
  'expected_indicators': ['Usermin', 'login', 'username'],
  'priority': 8},
 {'path': '/2082', 'category': 'hosting_panel', 'expected_indicators': ['cPanel', 'login', 'username'], 'priority': 8},
 {'path': '/2083', 'category': 'hosting_panel', 'expected_indicators': ['cPanel', 'login', 'username'], 'priority': 8},
 {'path': '/2086', 'category': 'hosting_panel', 'expected_indicators': ['WHM', 'login', 'username'], 'priority': 8},
 {'path': '/2087', 'category': 'hosting_panel', 'expected_indicators': ['WHM', 'login', 'username'], 'priority': 8},
 {'path': '/2095', 'category': 'hosting_panel', 'expected_indicators': ['cPanel', 'Webmail', 'login'], 'priority': 7},
 {'path': '/2096', 'category': 'hosting_panel', 'expected_indicators': ['cPanel', 'Webmail', 'login'], 'priority': 7},
 {'path': '/vhcs', 'category': 'hosting_panel', 'expected_indicators': ['VHCS', 'login', 'username'], 'priority': 6},
 {'path': '/ispconfig',
  'category': 'hosting_panel',
  'expected_indicators': ['ISPConfig', 'login', 'username'],
  'priority': 7},
 {'path': '/ispmanager',
  'category': 'hosting_panel',
  'expected_indicators': ['ISPManager', 'login', 'username'],
  'priority': 7},
 {'path': '/doc/page/login.asp',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['login', 'username', 'password'],
  'priority': 10},
 {'path': '/cgi-bin/login.cgi',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['login', 'username', 'password'],
  'priority': 10},
 {'path': '/webadmin',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['Web Admin', 'login', 'username'],
  'priority': 9},
 {'path': '/cgi-bin/viewer/video.jpg',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['login', 'camera', 'username'],
  'priority': 8},
 {'path': '/cgi-bin/user.cgi',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['login', 'username', 'camera'],
  'priority': 8},
 {'path': '/view/index.shtml',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['login', 'camera', 'username'],
  'priority': 8},
 {'path': '/cgi-bin/main.cgi',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['login', 'username', 'camera'],
  'priority': 8},
 {'path': '/login.asp',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['login', 'username', 'password'],
  'priority': 8},
 {'path': '/cgi-bin/login.asp',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['login', 'username', 'password'],
  'priority': 8},
 {'path': '/webapi', 'category': 'iot_camera_nvr', 'expected_indicators': ['API', 'login', 'username'], 'priority': 7},
 {'path': '/cgi-bin/admin/setup.cgi',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['Admin', 'Setup', 'login'],
  'priority': 7},
 {'path': '/dvr', 'category': 'iot_camera_nvr', 'expected_indicators': ['DVR', 'login', 'username'], 'priority': 8},
 {'path': '/nvr', 'category': 'iot_camera_nvr', 'expected_indicators': ['NVR', 'login', 'username'], 'priority': 8},
 {'path': '/nvr/login',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['NVR', 'login', 'username'],
  'priority': 7},
 {'path': '/cgi-bin/initial_setup.cgi',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['Setup', 'login', 'username'],
  'priority': 7},
 {'path': '/pages/login.html',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['login', 'username', 'password'],
  'priority': 7},
 {'path': '/camera',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['Camera', 'login', 'username'],
  'priority': 7},
 {'path': '/camera/admin',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['Camera', 'Admin', 'login'],
  'priority': 7},
 {'path': '/HNAP1', 'category': 'iot_camera_nvr', 'expected_indicators': ['HNAP', 'login', 'username'], 'priority': 7},
 {'path': '/system/deviceInfo',
  'category': 'iot_camera_nvr',
  'expected_indicators': ['Device', 'login', 'username'],
  'priority': 6},
 {'path': '/scada',
  'category': 'industrial_scada',
  'expected_indicators': ['SCADA', 'login', 'username'],
  'priority': 9},
 {'path': '/hmi', 'category': 'industrial_scada', 'expected_indicators': ['HMI', 'login', 'username'], 'priority': 9},
 {'path': '/ics-admin',
  'category': 'industrial_scada',
  'expected_indicators': ['ICS', 'Admin', 'login'],
  'priority': 9},
 {'path': '/plc', 'category': 'industrial_scada', 'expected_indicators': ['PLC', 'login', 'username'], 'priority': 8},
 {'path': '/modbus',
  'category': 'industrial_scada',
  'expected_indicators': ['Modbus', 'login', 'username'],
  'priority': 8},
 {'path': '/dcs', 'category': 'industrial_scada', 'expected_indicators': ['DCS', 'login', 'username'], 'priority': 8},
 {'path': '/industrial/admin',
  'category': 'industrial_scada',
  'expected_indicators': ['Industrial', 'Admin', 'login'],
  'priority': 8},
 {'path': '/scada/login',
  'category': 'industrial_scada',
  'expected_indicators': ['SCADA', 'login', 'username'],
  'priority': 8},
 {'path': '/hmi/login',
  'category': 'industrial_scada',
  'expected_indicators': ['HMI', 'login', 'username'],
  'priority': 8},
 {'path': '/ot/admin', 'category': 'industrial_scada', 'expected_indicators': ['OT', 'Admin', 'login'], 'priority': 7},
 {'path': '/ifix', 'category': 'industrial_scada', 'expected_indicators': ['iFIX', 'login', 'username'], 'priority': 7},
 {'path': '/wonderware',
  'category': 'industrial_scada',
  'expected_indicators': ['Wonderware', 'login', 'username'],
  'priority': 7},
 {'path': '/ignition',
  'category': 'industrial_scada',
  'expected_indicators': ['Ignition', 'login', 'username'],
  'priority': 8},
 {'path': '/factorytalk',
  'category': 'industrial_scada',
  'expected_indicators': ['FactoryTalk', 'login', 'username'],
  'priority': 7},
 {'path': '/rockwelladmin',
  'category': 'industrial_scada',
  'expected_indicators': ['Rockwell', 'Admin', 'login'],
  'priority': 7},
 {'path': '/jenkins',
  'category': 'devops_panel',
  'expected_indicators': ['Jenkins', 'login', 'username'],
  'priority': 10},
 {'path': '/jenkins/login',
  'category': 'devops_panel',
  'expected_indicators': ['Jenkins', 'login', 'username'],
  'priority': 9},
 {'path': '/gitlab',
  'category': 'devops_panel',
  'expected_indicators': ['GitLab', 'Sign in', 'username'],
  'priority': 10},
 {'path': '/gitlab/users/sign_in',
  'category': 'devops_panel',
  'expected_indicators': ['GitLab', 'Sign in', 'username'],
  'priority': 9},
 {'path': '/grafana',
  'category': 'devops_panel',
  'expected_indicators': ['Grafana', 'login', 'username'],
  'priority': 10},
 {'path': '/grafana/login',
  'category': 'devops_panel',
  'expected_indicators': ['Grafana', 'login', 'username'],
  'priority': 9},
 {'path': '/kibana',
  'category': 'devops_panel',
  'expected_indicators': ['Kibana', 'login', 'username'],
  'priority': 10},
 {'path': '/kibana/login',
  'category': 'devops_panel',
  'expected_indicators': ['Kibana', 'login', 'username'],
  'priority': 9},
 {'path': '/prometheus',
  'category': 'devops_panel',
  'expected_indicators': ['Prometheus', 'login', 'username'],
  'priority': 9},
 {'path': '/argo', 'category': 'devops_panel', 'expected_indicators': ['Argo', 'login', 'username'], 'priority': 9},
 {'path': '/argocd',
  'category': 'devops_panel',
  'expected_indicators': ['Argo CD', 'login', 'username'],
  'priority': 9},
 {'path': '/spinnaker',
  'category': 'devops_panel',
  'expected_indicators': ['Spinnaker', 'login', 'username'],
  'priority': 8},
 {'path': '/nexus', 'category': 'devops_panel', 'expected_indicators': ['Nexus', 'login', 'username'], 'priority': 9},
 {'path': '/sonarqube',
  'category': 'devops_panel',
  'expected_indicators': ['SonarQube', 'login', 'username'],
  'priority': 9},
 {'path': '/portainer',
  'category': 'devops_panel',
  'expected_indicators': ['Portainer', 'login', 'username'],
  'priority': 9},
 {'path': '/rancher',
  'category': 'devops_panel',
  'expected_indicators': ['Rancher', 'login', 'username'],
  'priority': 9},
 {'path': '/kubernetes',
  'category': 'devops_panel',
  'expected_indicators': ['Kubernetes', 'login', 'username'],
  'priority': 8},
 {'path': '/k8s',
  'category': 'devops_panel',
  'expected_indicators': ['Kubernetes', 'login', 'username'],
  'priority': 8},
 {'path': '/vault', 'category': 'devops_panel', 'expected_indicators': ['Vault', 'login', 'username'], 'priority': 8},
 {'path': '/consul', 'category': 'devops_panel', 'expected_indicators': ['Consul', 'login', 'username'], 'priority': 8},
 {'path': '/drone', 'category': 'devops_panel', 'expected_indicators': ['Drone', 'login', 'username'], 'priority': 7},
 {'path': '/teamcity',
  'category': 'devops_panel',
  'expected_indicators': ['TeamCity', 'login', 'username'],
  'priority': 8},
 {'path': '/bamboo', 'category': 'devops_panel', 'expected_indicators': ['Bamboo', 'login', 'username'], 'priority': 7},
 {'path': '/horde', 'category': 'mail_admin', 'expected_indicators': ['Horde', 'login', 'username'], 'priority': 9},
 {'path': '/horde/login.php',
  'category': 'mail_admin',
  'expected_indicators': ['Horde', 'login', 'username'],
  'priority': 9},
 {'path': '/squirrelmail',
  'category': 'mail_admin',
  'expected_indicators': ['SquirrelMail', 'login', 'username'],
  'priority': 9},
 {'path': '/squirrelmail/src/login.php',
  'category': 'mail_admin',
  'expected_indicators': ['SquirrelMail', 'login', 'username'],
  'priority': 8},
 {'path': '/roundcube',
  'category': 'mail_admin',
  'expected_indicators': ['Roundcube', 'login', 'username'],
  'priority': 10},
 {'path': '/roundcube/login',
  'category': 'mail_admin',
  'expected_indicators': ['Roundcube', 'login', 'username'],
  'priority': 9},
 {'path': '/webmail/admin',
  'category': 'mail_admin',
  'expected_indicators': ['Webmail', 'Admin', 'login'],
  'priority': 9},
 {'path': '/webmail', 'category': 'mail_admin', 'expected_indicators': ['Webmail', 'login', 'username'], 'priority': 9},
 {'path': '/webmail/login',
  'category': 'mail_admin',
  'expected_indicators': ['Webmail', 'login', 'username'],
  'priority': 8},
 {'path': '/mail/admin', 'category': 'mail_admin', 'expected_indicators': ['Mail', 'Admin', 'login'], 'priority': 8},
 {'path': '/mail', 'category': 'mail_admin', 'expected_indicators': ['Mail', 'login', 'username'], 'priority': 8},
 {'path': '/zimbra', 'category': 'mail_admin', 'expected_indicators': ['Zimbra', 'login', 'username'], 'priority': 9},
 {'path': '/postfix/admin',
  'category': 'mail_admin',
  'expected_indicators': ['Postfix', 'Admin', 'login'],
  'priority': 8},
 {'path': '/rainloop',
  'category': 'mail_admin',
  'expected_indicators': ['RainLoop', 'login', 'username'],
  'priority': 7},
 {'path': '/after-login',
  'category': 'mail_admin',
  'expected_indicators': ['login', 'username', 'Welcome'],
  'priority': 5},
 {'path': '/syno',
  'category': 'backup_storage',
  'expected_indicators': ['Synology', 'login', 'username'],
  'priority': 10},
 {'path': '/synology',
  'category': 'backup_storage',
  'expected_indicators': ['Synology', 'login', 'username'],
  'priority': 9},
 {'path': '/diskstation',
  'category': 'backup_storage',
  'expected_indicators': ['DiskStation', 'login', 'username'],
  'priority': 10},
 {'path': '/qnap', 'category': 'backup_storage', 'expected_indicators': ['QNAP', 'login', 'username'], 'priority': 10},
 {'path': '/qnap/cgi-bin/login.cgi',
  'category': 'backup_storage',
  'expected_indicators': ['QNAP', 'login', 'username'],
  'priority': 9},
 {'path': '/nas', 'category': 'backup_storage', 'expected_indicators': ['NAS', 'login', 'username'], 'priority': 9},
 {'path': '/nas/admin', 'category': 'backup_storage', 'expected_indicators': ['NAS', 'Admin', 'login'], 'priority': 8},
 {'path': '/storage',
  'category': 'backup_storage',
  'expected_indicators': ['Storage', 'login', 'username'],
  'priority': 8},
 {'path': '/storage/admin',
  'category': 'backup_storage',
  'expected_indicators': ['Storage', 'Admin', 'login'],
  'priority': 7},
 {'path': '/backup',
  'category': 'backup_storage',
  'expected_indicators': ['Backup', 'login', 'username'],
  'priority': 8},
 {'path': '/backup/admin',
  'category': 'backup_storage',
  'expected_indicators': ['Backup', 'Admin', 'login'],
  'priority': 7},
 {'path': '/backupexec',
  'category': 'backup_storage',
  'expected_indicators': ['Backup Exec', 'login', 'username'],
  'priority': 7},
 {'path': '/veeam', 'category': 'backup_storage', 'expected_indicators': ['Veeam', 'login', 'username'], 'priority': 8},
 {'path': '/veeam/admin',
  'category': 'backup_storage',
  'expected_indicators': ['Veeam', 'Admin', 'login'],
  'priority': 7},
 {'path': '/netatalk',
  'category': 'backup_storage',
  'expected_indicators': ['Netatalk', 'login', 'username'],
  'priority': 6},
 {'path': '/freepbx', 'category': 'voip_pbx', 'expected_indicators': ['FreePBX', 'login', 'username'], 'priority': 10},
 {'path': '/freepbx/admin',
  'category': 'voip_pbx',
  'expected_indicators': ['FreePBX', 'Admin', 'login'],
  'priority': 9},
 {'path': '/asterisk',
  'category': 'voip_pbx',
  'expected_indicators': ['Asterisk', 'login', 'username'],
  'priority': 10},
 {'path': '/asterisk/admin',
  'category': 'voip_pbx',
  'expected_indicators': ['Asterisk', 'Admin', 'login'],
  'priority': 9},
 {'path': '/admin/config.php',
  'category': 'voip_pbx',
  'expected_indicators': ['Admin', 'Config', 'login'],
  'priority': 9},
 {'path': '/pbx', 'category': 'voip_pbx', 'expected_indicators': ['PBX', 'login', 'username'], 'priority': 9},
 {'path': '/pbx/admin', 'category': 'voip_pbx', 'expected_indicators': ['PBX', 'Admin', 'login'], 'priority': 8},
 {'path': '/voip', 'category': 'voip_pbx', 'expected_indicators': ['VoIP', 'login', 'username'], 'priority': 8},
 {'path': '/voip/admin', 'category': 'voip_pbx', 'expected_indicators': ['VoIP', 'Admin', 'login'], 'priority': 8},
 {'path': '/fusionpbx',
  'category': 'voip_pbx',
  'expected_indicators': ['FusionPBX', 'login', 'username'],
  'priority': 8}]
