"""msf_payload_generation_test - findings rules.

Severity model:
  MEDIUM   msfvenom installed but produced 0 bytes (broken install)
  INFO     msfvenom missing / probe error / informational result
  POSITIVE benign payload generated within expected size band

The benign payload is `windows/x64/exec CMD=calc.exe` - it pops the
Windows calculator on detonation. Generated bytes are SHA-256 hashed
for the report but NEVER written to disk and NEVER delivered to the
target; this is a health check of the customer's MSF install.
"""


def rule_binary_missing(s):
    if not s.get("msf_payload_generation_test_binary_missing"):
        return None
    return {
        "name": "msfvenom binary not installed on scanner host",
        "severity": "INFO",
        "evidence": ("shutil.which('msfvenom') returned None. The benign "
                     "payload-generation probe could not run."),
        "remediation": (
            "Install Metasploit Framework: "
            "apt install metasploit-framework. msfvenom ships as part of "
            "the framework package."
        ),
        "cwe": "CWE-1006",
    }


def rule_no_payload_produced(s):
    if not s.get("msf_payload_generation_test_no_payload_produced"):
        return None
    if s.get("msf_payload_generation_test_binary_missing"):
        return None
    return {
        "name": ("msfvenom returned 0 bytes for benign windows/x64/exec "
                 "CMD=calc.exe payload"),
        "severity": "MEDIUM",
        "cvss": "4.3",
        "cwe": "CWE-1357",
        "evidence": (
            "msfvenom -p windows/x64/exec CMD=calc.exe -f raw produced "
            "an empty stdout stream. The customer's Metasploit install "
            "cannot currently generate shellcode for the most basic "
            "Windows payload module - likely a broken Ruby bundle, "
            "missing payload tree, or insufficient permissions on the "
            "msfvenom cache directory."
        ),
        "remediation": (
            "1. Re-run msfvenom manually: `msfvenom -p windows/x64/exec "
            "CMD=calc.exe -f raw | wc -c` (expect ~272 bytes). 2. If 0 "
            "bytes, run `msfconsole -q -x 'version; exit'` to confirm "
            "the framework boots at all. 3. Reinstall: `apt install "
            "--reinstall metasploit-framework`. 4. Re-run this probe."
        ),
    }


def rule_out_of_band(s):
    if s.get("msf_payload_generation_test_binary_missing"):
        return None
    if s.get("msf_payload_generation_test_no_payload_produced"):
        return None
    if s.get("msf_payload_generation_test_within_expected_band"):
        return None
    bc = s.get("msf_payload_generation_test_byte_count")
    if bc is None:
        return None
    return {
        "name": (f"msfvenom produced unexpected payload size ({bc} bytes) "
                 "for benign windows/x64/exec CMD=calc.exe"),
        "severity": "INFO",
        "evidence": (
            f"Expected band: 32-4096 bytes. Got: {bc} bytes. SHA-256: "
            f"{(s.get('msf_payload_generation_test_sha256') or '')[:32]}.... "
            "Either the payload module shape changed in a new MSF release "
            "(in which case this rule needs an update) or msfvenom is "
            "injecting extra wrappers (encoders, NOP sleds) we didn't ask for."
        ),
        "remediation": (
            "1. Confirm the MSF version: `msfvenom --version`. 2. Compare "
            "the byte count against the rapid7/metasploit-framework "
            "release notes for that version. 3. Verify no global encoder "
            "is set in ~/.msf4/msfconsole.rc (`setg ENCODER`)."
        ),
        "cwe": "CWE-1357",
    }


def rule_probe_error(s):
    err = s.get("msf_payload_generation_test_error")
    if not err:
        return None
    return {
        "name": "msfvenom benign-payload probe failed",
        "severity": "INFO",
        "evidence": f"Probe error: {str(err)[:300]}",
        "remediation": (
            "1. Run `msfvenom -p windows/x64/exec CMD=calc.exe -f raw "
            "> /dev/null` manually to reproduce. 2. Check msfvenom's "
            "stderr for Ruby exceptions. 3. Re-run this probe."
        ),
        "cwe": "CWE-754",
    }


def rule_positive_generated(s):
    if s.get("msf_payload_generation_test_binary_missing"):
        return None
    if s.get("msf_payload_generation_test_no_payload_produced"):
        return None
    if s.get("msf_payload_generation_test_error"):
        return None
    if not s.get("msf_payload_generation_test_within_expected_band"):
        return None
    bc = s.get("msf_payload_generation_test_byte_count") or 0
    sha = (s.get("msf_payload_generation_test_sha256") or "")[:16]
    return {
        "name": (f"msfvenom generated benign windows/x64/exec CMD=calc.exe "
                 f"payload successfully ({bc} bytes)"),
        "severity": "POSITIVE",
        "evidence": (
            f"msfvenom emitted {bc} byte(s) of shellcode for the benign "
            f"calc.exe payload (SHA-256 prefix: {sha}...). The bytes were "
            "hashed and discarded - nothing was written to disk and no "
            "target traffic was generated."
        ),
        "remediation": (
            "No action needed. Keep Metasploit Framework current via "
            "`apt update && apt install --only-upgrade metasploit-framework` "
            "weekly so new payload formats land as Rapid7 ships them."
        ),
        "cwe": "CWE-1357",
        "mitre": "T1027.002",
    }


MSF_PAYLOAD_GENERATION_TEST_FINDING_RULES = [
    rule_binary_missing,
    rule_no_payload_produced,
    rule_out_of_band,
    rule_probe_error,
    rule_positive_generated,
]
