"""origin_discovery — generated dev-time by Claude. Recon module asset.
"""

ORIGIN_DISCOVERY = [{'name': 'SecurityTrails DNS A Record History',
  'technique': 'dns_history',
  'query_pattern': 'https://api.securitytrails.com/v1/history/{DOMAIN}/dns/a',
  'difficulty': 'easy',
  'success_rate': 'high'},
 {'name': 'FarsightDNS DNSDB Passive DNS Lookup',
  'technique': 'dns_history',
  'query_pattern': 'https://api.dnsdb.info/lookup/rrset/name/{DOMAIN}/A',
  'difficulty': 'easy',
  'success_rate': 'high'},
 {'name': 'WhoisXMLAPI DNS History A Records',
  'technique': 'dns_history',
  'query_pattern': 'https://dns-history.whoisxmlapi.com/api/v1?apiKey=KEY&domainName={DOMAIN}&type=A',
  'difficulty': 'easy',
  'success_rate': 'high'},
 {'name': 'Censys Certificate SAN IP Extraction',
  'technique': 'cert_san',
  'query_pattern': 'https://search.censys.io/search?resource=certificates&q=parsed.names%3A{DOMAIN}',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'Censys IPv4 Host TLS Common Name Search',
  'technique': 'censys',
  'query_pattern': 'https://search.censys.io/search?resource=hosts&q=services.tls.certificates.leaf_data.names%3A{DOMAIN}',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'Shodan SSL Certificate Subject Search',
  'technique': 'shodan',
  'query_pattern': 'https://www.shodan.io/search?query=ssl.cert.subject.cn%3A{DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'high'},
 {'name': 'Shodan Host History IP Lookup',
  'technique': 'shodan',
  'query_pattern': 'https://api.shodan.io/shodan/host/search?key=KEY&query=hostname:{DOMAIN}&history=true',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'FOFA Certificate Hash Origin Search',
  'technique': 'cert_san',
  'query_pattern': 'https://fofa.info/result?qbase64=Y2VydC5kb21haW49IntET01BSU59Ig==',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'crt.sh Certificate Transparency Log Parsing',
  'technique': 'dns_history',
  'query_pattern': 'https://crt.sh/?q=%25.{DOMAIN}&output=json',
  'difficulty': 'easy',
  'success_rate': 'high'},
 {'name': 'Wayback Machine CDX IP History',
  'technique': 'wayback',
  'query_pattern': 'http://web.archive.org/cdx/search/cdx?url={DOMAIN}&output=json&fl=timestamp,original,urlkey,statuscode,digest',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'SPF Record Origin IP Leak',
  'technique': 'email_leak',
  'query_pattern': 'dig TXT {DOMAIN} | grep spf | grep ip4',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'DMARC Report URI Origin Reveal',
  'technique': 'email_leak',
  'query_pattern': 'dig TXT _dmarc.{DOMAIN} +short',
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'MX Record Mail Server IP Leak',
  'technique': 'email_leak',
  'query_pattern': "dig MX {DOMAIN} +short && dig A $(dig MX {DOMAIN} +short | awk '{print $2}')",
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Direct Dev Subdomain CDN Bypass',
  'technique': 'misconfig',
  'query_pattern': "dig A dev.{DOMAIN} +short && curl -sk https://dev.{DOMAIN} -o /dev/null -w '%{http_code}'",
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Direct Staging Subdomain Probe',
  'technique': 'misconfig',
  'query_pattern': "dig A staging.{DOMAIN} +short && curl -sk https://staging.{DOMAIN} -H 'Host: {DOMAIN}'",
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Direct Origin Subdomain Probe',
  'technique': 'misconfig',
  'query_pattern': 'dig A origin.{DOMAIN} +short',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Direct Backend Subdomain Probe',
  'technique': 'misconfig',
  'query_pattern': 'dig A backend.{DOMAIN} +short',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'SMTP EHLO Banner IP Extraction',
  'technique': 'email_leak',
  'query_pattern': "nc -w3 $(dig MX {DOMAIN} +short | sort -n | head -1 | awk '{print $2}') 25",
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'Bounce Email Header IP Trace',
  'technique': 'email_leak',
  'query_pattern': 'Send email to nonexistent@{DOMAIN} and parse Received headers in bounce',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'Shodan SSL SAN Wildcard Match',
  'technique': 'shodan',
  'query_pattern': 'https://api.shodan.io/shodan/host/search?key=KEY&query=ssl.cert.subject.cn:*.{DOMAIN}',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'Censys ASN Range Certificate Correlation',
  'technique': 'censys',
  'query_pattern': 'https://search.censys.io/search?resource=hosts&q=autonomous_system.name%3A{DOMAIN}+AND+services.tls.certificates.leaf_data.names%3A{DOMAIN}',
  'difficulty': 'hard',
  'success_rate': 'medium'},
 {'name': 'SecurityTrails Subdomain Enumeration',
  'technique': 'dns_history',
  'query_pattern': 'https://api.securitytrails.com/v1/domain/{DOMAIN}/subdomains?includeInactive=true',
  'difficulty': 'easy',
  'success_rate': 'high'},
 {'name': 'ViewDNS IP History Lookup',
  'technique': 'dns_history',
  'query_pattern': 'https://viewdns.info/iphistory/?domain={DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'RiskIQ PassiveTotal DNS History',
  'technique': 'dns_history',
  'query_pattern': 'https://api.passivetotal.org/v2/dns/passive?query={DOMAIN}',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'FOFA HTTP Header Server Fingerprint',
  'technique': 'cert_san',
  'query_pattern': 'https://fofa.info/result?qbase64=aGVhZGVyPSJTZXJ2ZXI6IiAmJiBkb21haW49IntET01BSU59Ig==',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'Netcraft Site Report Origin History',
  'technique': 'dns_history',
  'query_pattern': 'https://toolbar.netcraft.com/site_report?url=https://{DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Direct IP Host Header Brute Force',
  'technique': 'misconfig',
  'query_pattern': "curl -sk https://{ORIGIN_IP} -H 'Host: {DOMAIN}' -o /dev/null -w '%{http_code}'",
  'difficulty': 'hard',
  'success_rate': 'medium'},
 {'name': 'TXT Record Verification Token IP Leak',
  'technique': 'email_leak',
  'query_pattern': "dig TXT {DOMAIN} +short | grep -E 'google|facebook|verify|mailgun|sendgrid'",
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'Shodan HTTP Title Fingerprint Search',
  'technique': 'shodan',
  'query_pattern': 'https://www.shodan.io/search?query=http.title%3A"{DOMAIN}"+http.html%3A{DOMAIN}',
  'difficulty': 'medium',
  'success_rate': 'low'},
 {'name': 'GitHub Leaked Config IP Discovery',
  'technique': 'misconfig',
  'query_pattern': 'https://github.com/search?q={DOMAIN}+server+ip+config&type=code',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'Censys Certificate Fingerprint Pivot',
  'technique': 'cert_san',
  'query_pattern': 'https://search.censys.io/search?resource=hosts&q=services.tls.certificates.leaf_data.fingerprint%3A$(curl '
                   "-s 'https://crt.sh/?q={DOMAIN}&output=json' | jq -r '.[0].id')",
  'difficulty': 'hard',
  'success_rate': 'high'},
 {'name': 'Direct API Subdomain Probe',
  'technique': 'misconfig',
  'query_pattern': 'dig A api.{DOMAIN} +short && curl -sk https://api.{DOMAIN}/health',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Direct Admin Subdomain Probe',
  'technique': 'misconfig',
  'query_pattern': 'dig A admin.{DOMAIN} +short',
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'Passive DNS Mnemonic DNSDB Query',
  'technique': 'dns_history',
  'query_pattern': 'https://api.mnemonic.no/pdns/v3/{DOMAIN}?limit=25&includeAnonymousResults=false',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'HackerTarget DNS History Lookup',
  'technique': 'dns_history',
  'query_pattern': 'https://api.hackertarget.com/hostsearch/?q={DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Reverse IP Lookup Non-CDN Range',
  'technique': 'misconfig',
  'query_pattern': 'https://api.hackertarget.com/reverseiplookup/?q=$(dig A {DOMAIN} +short | head -1)',
  'difficulty': 'medium',
  'success_rate': 'low'},
 {'name': 'Shodan Favicon Hash Search',
  'technique': 'shodan',
  'query_pattern': 'https://www.shodan.io/search?query=http.favicon.hash:{FAVICON_HASH}',
  'difficulty': 'hard',
  'success_rate': 'medium'},
 {'name': 'FOFA Favicon Hash Origin Pivot',
  'technique': 'cert_san',
  'query_pattern': 'https://fofa.info/result?qbase64=aWNvbl9oYXNoPXtGQVZJQ09OX0hBU0h9',
  'difficulty': 'hard',
  'success_rate': 'medium'},
 {'name': 'Subdomain Permutation Direct Resolve',
  'technique': 'misconfig',
  'query_pattern': 'for sub in direct server host app web internal; do dig A $sub.{DOMAIN} +short; done',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'PTR Record Reverse DNS Enumeration',
  'technique': 'dns_history',
  'query_pattern': 'dig -x $(dig A {DOMAIN} +short | head -1) +short',
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'Zone Transfer Attempt AXFR',
  'technique': 'misconfig',
  'query_pattern': 'dig AXFR {DOMAIN} @$(dig NS {DOMAIN} +short | head -1)',
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'Shodan HTTP Headers X-Powered-By Search',
  'technique': 'shodan',
  'query_pattern': 'https://www.shodan.io/search?query=http.headers.server%3A{SERVER_HEADER}+hostname%3A{DOMAIN}',
  'difficulty': 'hard',
  'success_rate': 'low'},
 {'name': 'BinaryEdge Certificate SAN Discovery',
  'technique': 'cert_san',
  'query_pattern': 'https://api.binaryedge.io/v2/query/domains/subdomain/{DOMAIN}',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'GreyNoise IP Context CDN Bypass Check',
  'technique': 'censys',
  'query_pattern': 'https://api.greynoise.io/v3/community/$(dig A {DOMAIN} +short | head -1)',
  'difficulty': 'medium',
  'success_rate': 'low'},
 {'name': 'AlienVault OTX Passive DNS Query',
  'technique': 'dns_history',
  'query_pattern': 'https://otx.alienvault.com/api/v1/indicators/domain/{DOMAIN}/passive_dns',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Wayback Machine Robots.txt Historical IP',
  'technique': 'wayback',
  'query_pattern': 'https://web.archive.org/web/2010*/http://{DOMAIN}/robots.txt',
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'SSL Certificate Serial Number Pivot',
  'technique': 'cert_san',
  'query_pattern': 'https://crt.sh/?serial=$(openssl s_client -connect {DOMAIN}:443 </dev/null 2>/dev/null | openssl '
                   'x509 -noout -serial | cut -d= -f2)',
  'difficulty': 'hard',
  'success_rate': 'medium'},
 {'name': 'Sendgrid/Mailgun Custom Domain IP Leak',
  'technique': 'email_leak',
  'query_pattern': 'dig A email.{DOMAIN} +short && dig A smtp.{DOMAIN} +short && dig A mail.{DOMAIN} +short',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'NetDB Passive DNS Resolution History',
  'technique': 'dns_history',
  'query_pattern': 'https://www.netdb.io/query/dns?query={DOMAIN}&type=A',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Shodan ASN Correlated Origin Search',
  'technique': 'shodan',
  'query_pattern': 'https://www.shodan.io/search?query=ssl%3A{DOMAIN}+asn%3A{TARGET_ASN}',
  'difficulty': 'hard',
  'success_rate': 'medium'},
 {'name': 'HTTP Options/Trace Method Origin Header Leak',
  'technique': 'misconfig',
  'query_pattern': "curl -sk -X TRACE https://{DOMAIN} -D - | grep -i 'X-Forwarded-For\\|X-Real-IP\\|Via\\|X-Origin'",
  'difficulty': 'medium',
  'success_rate': 'low'}]
