"""origin_discovery — generated dev-time by Claude. Recon module asset.
"""

ORIGIN_DISCOVERY = [{'name': 'SecurityTrails DNS A Record History',
  'technique': 'dns_history',
  'query_pattern': 'https://api.securitytrails.com/v1/history/{DOMAIN}/dns/a',
  'difficulty': 'easy',
  'success_rate': 'high'},
 {'name': 'FarsightDNS DNSDB Passive A Records',
  'technique': 'dns_history',
  'query_pattern': 'https://api.dnsdb.info/lookup/rrset/name/{DOMAIN}/A',
  'difficulty': 'easy',
  'success_rate': 'high'},
 {'name': 'WhoisXML DNS History API',
  'technique': 'dns_history',
  'query_pattern': 'https://dns-history.whoisxmlapi.com/api/v1?apiKey=KEY&domain={DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Censys Certificate SAN IP Extraction',
  'technique': 'cert_san',
  'query_pattern': 'https://search.censys.io/certificates?q=parsed.names%3A{DOMAIN}',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'Censys IPv4 Host Serving Certificate',
  'technique': 'censys',
  'query_pattern': 'https://search.censys.io/search?resource=hosts&q=services.tls.certificates.leaf_data.names%3A{DOMAIN}',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'Shodan SSL Certificate Hostname Search',
  'technique': 'shodan',
  'query_pattern': 'https://www.shodan.io/search?query=ssl%3A{DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'high'},
 {'name': 'Shodan Host History IP Lookup',
  'technique': 'shodan',
  'query_pattern': 'https://api.shodan.io/shodan/host/search?key=KEY&query=hostname%3A{DOMAIN}&history=true',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'FOFA Certificate Hash Origin Search',
  'technique': 'cert_san',
  'query_pattern': 'https://fofa.info/result?qbase64=base64(cert%3D"{DOMAIN}")',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'crt.sh CT Log IP Discovery',
  'technique': 'dns_history',
  'query_pattern': 'https://crt.sh/?q={DOMAIN}&output=json',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Wayback Machine CDX IP History',
  'technique': 'wayback',
  'query_pattern': 'http://web.archive.org/cdx/search/cdx?url={DOMAIN}&output=json&fl=timestamp,original,urlkey,statuscode,digest',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'SPF Record Origin IP Leak',
  'technique': 'email_leak',
  'query_pattern': 'dig TXT {DOMAIN} | grep spf',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'DMARC Report URI Leak',
  'technique': 'email_leak',
  'query_pattern': 'dig TXT _dmarc.{DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'MX Record Mail Server IP',
  'technique': 'email_leak',
  'query_pattern': "dig MX {DOMAIN} && dig A $(dig MX {DOMAIN} | awk '{print $5}')",
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Dev Subdomain Direct CDN Bypass',
  'technique': 'misconfig',
  'query_pattern': 'dig A dev.{DOMAIN} && curl -sk https://dev.{DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Staging Subdomain Direct Pointer',
  'technique': 'misconfig',
  'query_pattern': 'dig A staging.{DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Direct IP in X-Forwarded-For Header Response',
  'technique': 'misconfig',
  'query_pattern': 'curl -sk -D - https://{DOMAIN} | grep -i x-real-ip',
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'Netcraft Site Report Historical IPs',
  'technique': 'dns_history',
  'query_pattern': 'https://sitereport.netcraft.com/?url={DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'RiskIQ PassiveTotal DNS Resolution History',
  'technique': 'dns_history',
  'query_pattern': 'https://api.passivetotal.org/v2/dns/passive?query={DOMAIN}',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'VirusTotal Historical DNS Resolutions',
  'technique': 'dns_history',
  'query_pattern': 'https://www.virustotal.com/api/v3/domains/{DOMAIN}/resolutions',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'FOFA IP Behind CDN with HTTP Header',
  'technique': 'censys',
  'query_pattern': 'https://fofa.info/result?qbase64=base64(host="{DOMAIN}" && server!="cloudflare")',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'Shodan HTTP Title Match for Origin',
  'technique': 'shodan',
  'query_pattern': 'https://api.shodan.io/shodan/host/search?key=KEY&query=http.title%3A"{DOMAIN}"',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'TLS Certificate Serial Number Cross-Reference',
  'technique': 'cert_san',
  'query_pattern': 'openssl s_client -connect {DOMAIN}:443 | openssl x509 -serial -noout',
  'difficulty': 'hard',
  'success_rate': 'medium'},
 {'name': 'ZoomEye Certificate SAN Search',
  'technique': 'cert_san',
  'query_pattern': 'https://www.zoomeye.org/searchResult?q=ssl.cert.subject.cn%3A{DOMAIN}',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'BGP Ranking ASN to IP Block Mapping',
  'technique': 'dns_history',
  'query_pattern': "https://bgpranking.circl.lu/asn?asn=$(whois {DOMAIN} | grep -i origin | awk '{print $2}')",
  'difficulty': 'hard',
  'success_rate': 'low'},
 {'name': 'Direct /robots.txt Request on IP Range',
  'technique': 'misconfig',
  'query_pattern': "for ip in $(prips CIDR); do curl -sk -H 'Host: {DOMAIN}' http://$ip/robots.txt; done",
  'difficulty': 'hard',
  'success_rate': 'medium'},
 {'name': 'Email Header Analysis for Originating IP',
  'technique': 'email_leak',
  'query_pattern': 'Send email to {DOMAIN} contact form and parse Received headers',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Subdomain Enumeration for Non-CDN Hosts',
  'technique': 'misconfig',
  'query_pattern': 'amass enum -d {DOMAIN} | while read sub; do dig +short $sub; done | sort -u',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'ARIN WHOIS IP Block Lookup',
  'technique': 'dns_history',
  'query_pattern': 'https://search.arin.net/rdap/?query={DOMAIN}&searchFilter=orgRef',
  'difficulty': 'medium',
  'success_rate': 'low'},
 {'name': 'Certificate Transparency Log SAN IPs via Censys',
  'technique': 'cert_san',
  'query_pattern': 'censys search \'parsed.subject_dn: "CN={DOMAIN}"\' --index certificates',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'Old TXT Record IP Artifact Discovery',
  'technique': 'dns_history',
  'query_pattern': 'dig TXT {DOMAIN} && SecurityTrails TXT history for {DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'Favicon Hash Shodan Fingerprint',
  'technique': 'shodan',
  'query_pattern': 'https://www.shodan.io/search?query=http.favicon.hash%3A$(python3 -c "import mmh3,requests,base64; '
                   'print(mmh3.hash(base64.encodebytes(requests.get(\'https://{DOMAIN}/favicon.ico\').content)))")',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'Favicon Hash FOFA Fingerprint',
  'technique': 'cert_san',
  'query_pattern': 'https://fofa.info/result?qbase64=base64(icon_hash="HASH_FROM_{DOMAIN}")',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'HTTP Response Header Unique Value Search',
  'technique': 'misconfig',
  'query_pattern': "curl -sk -I https://{DOMAIN} | grep -i 'x-powered-by\\|server\\|x-application'",
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'Source Code Hardcoded IP References',
  'technique': 'misconfig',
  'query_pattern': "curl -sk https://{DOMAIN} | grep -oE '([0-9]{1,3}\\.){3}[0-9]{1,3}'",
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'JavaScript File Origin IP Reference',
  'technique': 'misconfig',
  'query_pattern': 'curl -sk https://{DOMAIN} | grep -oP \'src="[^"]+"\' | xargs -I {} curl -sk {} | grep -oE '
                   "'([0-9]{1,3}\\.){3}[0-9]{1,3}'",
  'difficulty': 'medium',
  'success_rate': 'low'},
 {'name': 'DNS Zone Transfer Attempt',
  'technique': 'misconfig',
  'query_pattern': "dig axfr {DOMAIN} @$(dig NS {DOMAIN} | awk '/NS/{print $5}' | head -1)",
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'Shodan ASN Search for Org Infrastructure',
  'technique': 'shodan',
  'query_pattern': 'https://api.shodan.io/shodan/host/search?key=KEY&query=org%3A"{DOMAIN}"',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'Censys ASN Org Certificate Match',
  'technique': 'censys',
  'query_pattern': 'censys search \'autonomous_system.name: "{DOMAIN}" and services.tls.certificates.leaf_data.names: '
                   '"{DOMAIN}"\'',
  'difficulty': 'hard',
  'success_rate': 'medium'},
 {'name': 'GitHub Code Search for Origin IP',
  'technique': 'misconfig',
  'query_pattern': 'https://github.com/search?q={DOMAIN}+origin+IP&type=code',
  'difficulty': 'medium',
  'success_rate': 'low'},
 {'name': 'Pastebin Leak Search for IP',
  'technique': 'misconfig',
  'query_pattern': 'https://www.google.com/search?q=site:pastebin.com+"{DOMAIN}"+IP',
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'Google Dork for Exposed Config Files',
  'technique': 'misconfig',
  'query_pattern': 'site:{DOMAIN} ext:env OR ext:config OR ext:xml intext:origin',
  'difficulty': 'easy',
  'success_rate': 'low'},
 {'name': 'SMTP EHLO Banner IP Disclosure',
  'technique': 'email_leak',
  'query_pattern': "swaks --to test@{DOMAIN} --server $(dig MX {DOMAIN} | awk '{print $5}') 2>&1 | grep "
                   "'Received\\|ehlo'",
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'SSRF Probe via Application Endpoint',
  'technique': 'misconfig',
  'query_pattern': "curl -sk 'https://{DOMAIN}/fetch?url=http://169.254.169.254/latest/meta-data/'",
  'difficulty': 'hard',
  'success_rate': 'low'},
 {'name': 'ClouDNS / HackerTarget DNS History',
  'technique': 'dns_history',
  'query_pattern': 'https://api.hackertarget.com/hostsearch/?q={DOMAIN}',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'Cloudflare IP Bypass via Direct IP TLS SNI',
  'technique': 'misconfig',
  'query_pattern': "curl -sk --resolve {DOMAIN}:443:CANDIDATE_IP https://{DOMAIN}/ -o /dev/null -w '%{http_code}'",
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'Subfinder + Resolve for Non-CDN Subdomains',
  'technique': 'misconfig',
  'query_pattern': 'subfinder -d {DOMAIN} -silent | dnsx -silent -a -resp | grep -v cloudflare',
  'difficulty': 'medium',
  'success_rate': 'high'},
 {'name': 'Wayback Machine Direct IP URL Archives',
  'technique': 'wayback',
  'query_pattern': 'http://web.archive.org/cdx/search/cdx?url={DOMAIN}/*&output=json&filter=statuscode:200&fl=original,timestamp&from=20100101&to=20200101',
  'difficulty': 'easy',
  'success_rate': 'medium'},
 {'name': 'FOFA HTTP Header Unique String Match',
  'technique': 'censys',
  'query_pattern': 'https://fofa.info/result?qbase64=base64(header="X-Custom-Header-From-{DOMAIN}")',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'Shodan HTTP HTML Content Fingerprint',
  'technique': 'shodan',
  'query_pattern': 'https://api.shodan.io/shodan/host/search?key=KEY&query=http.html%3A"{DOMAIN}+unique-string"',
  'difficulty': 'medium',
  'success_rate': 'medium'},
 {'name': 'DNS PTR Reverse Lookup on ASN Block',
  'technique': 'dns_history',
  'query_pattern': 'for ip in $(prips ASN_CIDR_OF_{DOMAIN}); do dig +short -x $ip; done | grep {DOMAIN}',
  'difficulty': 'hard',
  'success_rate': 'medium'},
 {'name': 'Censys Historical Certificate IP Binding',
  'technique': 'censys',
  'query_pattern': 'censys search \'parsed.names: "{DOMAIN}"\' --index certificates | jq '
                   "'.[].parsed.subject_key_info'",
  'difficulty': 'hard',
  'success_rate': 'high'}]
