"""shodan_dorks — generated dev-time by Claude. Recon module asset.
"""

SHODAN_DORKS = [{'name': 'Exposed Jenkins Admin Panel',
  'platform': 'shodan',
  'query': 'http.title:"Dashboard [Jenkins]"',
  'category': 'ci_cd',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed MongoDB No Auth',
  'platform': 'shodan',
  'query': 'product:"MongoDB" port:27017',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Elasticsearch',
  'platform': 'shodan',
  'query': 'port:9200 json:{"cluster_name"',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Redis No Auth',
  'platform': 'shodan',
  'query': 'product:"Redis" port:6379',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Kubernetes API Server',
  'platform': 'shodan',
  'query': 'port:6443 product:"Kubernetes"',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Docker API',
  'platform': 'shodan',
  'query': 'port:2375 product:"Docker"',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed phpinfo Page',
  'platform': 'shodan',
  'query': 'http.title:"phpinfo()"',
  'category': 'debug',
  'severity_if_found': 'HIGH'},
 {'name': 'Default Cisco Router Login',
  'platform': 'shodan',
  'query': 'http.title:"Cisco" http.html:"default password"',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed GitLab Instance',
  'platform': 'shodan',
  'query': 'http.title:"GitLab" http.html:"Sign in"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Drone CI',
  'platform': 'shodan',
  'query': 'http.title:"Drone"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed IP Cameras Axis',
  'platform': 'shodan',
  'query': 'product:"Axis" http.title:"AXIS" port:80',
  'category': 'camera',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Webcam Streams',
  'platform': 'shodan',
  'query': 'http.title:"webcamXP" OR http.title:"webcam 7"',
  'category': 'camera',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed MikroTik Router',
  'platform': 'shodan',
  'query': 'http.title:"RouterOS" product:"MikroTik"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Netgear Admin',
  'platform': 'shodan',
  'query': 'http.title:"NETGEAR" http.html:"routerlogin"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Fortinet VPN',
  'platform': 'shodan',
  'query': 'http.title:"SSL VPN" product:"Fortinet"',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Prometheus Metrics',
  'platform': 'shodan',
  'query': 'http.title:"Prometheus" port:9090',
  'category': 'debug',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed Grafana Dashboard',
  'platform': 'shodan',
  'query': 'http.title:"Grafana" port:3000',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Hadoop HDFS',
  'platform': 'shodan',
  'query': 'port:50070 http.title:"Hadoop"',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Apache Cassandra',
  'platform': 'shodan',
  'query': 'port:9042 product:"Cassandra"',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Memcached',
  'platform': 'shodan',
  'query': 'port:11211 product:"Memcached"',
  'category': 'database',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed RabbitMQ Management',
  'platform': 'shodan',
  'query': 'port:15672 http.title:"RabbitMQ Management"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Kubernetes Dashboard',
  'platform': 'shodan',
  'query': 'http.title:"Kubernetes Dashboard"',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed etcd',
  'platform': 'shodan',
  'query': 'port:2379 product:"etcd"',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Sonarqube',
  'platform': 'shodan',
  'query': 'http.title:"SonarQube"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed FTP Anonymous Login',
  'platform': 'shodan',
  'query': 'port:21 "230 Login successful" "Anonymous"',
  'category': 'config',
  'severity_if_found': 'HIGH'},
 {'name': 'Default Tomcat Manager',
  'platform': 'shodan',
  'query': 'http.title:"Apache Tomcat" http.html:"manager"',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed ZooKeeper',
  'platform': 'shodan',
  'query': 'port:2181 product:"ZooKeeper"',
  'category': 'database',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Splunk Web',
  'platform': 'shodan',
  'query': 'http.title:"Splunk" port:8000',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Kibana Dashboard',
  'platform': 'shodan',
  'query': 'http.title:"Kibana" port:5601',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Jupyter Notebook',
  'platform': 'shodan',
  'query': 'http.title:"Jupyter Notebook" port:8888',
  'category': 'debug',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed phpMyAdmin',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:phpmyadmin',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed .env Config File',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:".env" filetype:env',
  'category': 'config',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed wp-config.php',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:wp-config.php',
  'category': 'config',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Debug Page',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:/debug',
  'category': 'debug',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Trace Endpoint',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:/trace',
  'category': 'debug',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed phpinfo',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:phpinfo.php',
  'category': 'debug',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Jenkins on Domain',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:/jenkins intitle:"Dashboard [Jenkins]"',
  'category': 'ci_cd',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed GitLab on Domain',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:gitlab intitle:"GitLab"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Admin Panel',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:admin intitle:"Admin Panel"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Login Page',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:login intitle:"Login"',
  'category': 'admin_panel',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed Database Config',
  'platform': 'google',
  'query': 'site:{DOMAIN} filetype:sql intext:password',
  'category': 'config',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Backup Files',
  'platform': 'google',
  'query': 'site:{DOMAIN} filetype:bak inurl:backup',
  'category': 'config',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed XML Config',
  'platform': 'google',
  'query': 'site:{DOMAIN} filetype:xml inurl:config',
  'category': 'config',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed YAML Config',
  'platform': 'google',
  'query': 'site:{DOMAIN} filetype:yaml inurl:config',
  'category': 'config',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed PHP Error Logs',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:error_log filetype:log',
  'category': 'debug',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed Credentials in URL',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:password filetype:txt',
  'category': 'config',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Kubernetes on Domain',
  'platform': 'google',
  'query': 'site:{DOMAIN} intitle:"Kubernetes Dashboard"',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Grafana on Domain',
  'platform': 'google',
  'query': 'site:{DOMAIN} intitle:"Grafana" inurl:/login',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Swagger API Docs',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:swagger-ui.html',
  'category': 'debug',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed API Documentation',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:/api/docs',
  'category': 'debug',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed .git Directory',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:"/.git" intitle:"Index of"',
  'category': 'config',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Directory Listing',
  'platform': 'google',
  'query': 'site:{DOMAIN} intitle:"Index of /"',
  'category': 'config',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed AWS Keys in Code',
  'platform': 'github',
  'query': 'org:{DOMAIN} AKIA filename:.env',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked AWS Secret Key',
  'platform': 'github',
  'query': 'org:{DOMAIN} aws_secret_access_key',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked Database Password',
  'platform': 'github',
  'query': 'org:{DOMAIN} DB_PASSWORD filename:.env',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked Private Key',
  'platform': 'github',
  'query': 'org:{DOMAIN} "BEGIN RSA PRIVATE KEY"',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked API Key in Code',
  'platform': 'github',
  'query': 'org:{DOMAIN} api_key language:python',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Leaked Slack Token',
  'platform': 'github',
  'query': 'org:{DOMAIN} xoxb- OR xoxp- filename:*.js',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Leaked GitHub Token',
  'platform': 'github',
  'query': 'org:{DOMAIN} ghp_ OR github_token',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked Stripe Key',
  'platform': 'github',
  'query': 'org:{DOMAIN} sk_live_ filename:*.js',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked Twilio Credentials',
  'platform': 'github',
  'query': 'org:{DOMAIN} TWILIO_AUTH_TOKEN',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Leaked SendGrid API Key',
  'platform': 'github',
  'query': 'org:{DOMAIN} SENDGRID_API_KEY',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed wp-config Credentials',
  'platform': 'github',
  'query': 'org:{DOMAIN} filename:wp-config.php DB_PASSWORD',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked .env File in Repo',
  'platform': 'github',
  'query': 'org:{DOMAIN} filename:.env SECRET_KEY',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked JDBC Connection String',
  'platform': 'github',
  'query': 'org:{DOMAIN} jdbc:mysql:// password',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked SSH Private Key',
  'platform': 'github',
  'query': 'org:{DOMAIN} "BEGIN OPENSSH PRIVATE KEY"',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked GCP Service Account',
  'platform': 'github',
  'query': 'org:{DOMAIN} "type": "service_account" filename:*.json',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked Heroku API Key',
  'platform': 'github',
  'query': 'org:{DOMAIN} HEROKU_API_KEY',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Leaked Kubernetes Config',
  'platform': 'github',
  'query': 'org:{DOMAIN} filename:kubeconfig clusters',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked Docker Registry Password',
  'platform': 'github',
  'query': 'org:{DOMAIN} DOCKER_PASSWORD filename:*.yml',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Leaked NPM Auth Token',
  'platform': 'github',
  'query': 'org:{DOMAIN} //registry.npmjs.org/:_authToken',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Elasticsearch Censys',
  'platform': 'censys',
  'query': 'services.port:9200 and services.http.response.body:"cluster_name"',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed MongoDB Censys',
  'platform': 'censys',
  'query': 'services.port:27017 and services.service_name:MONGODB',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Redis Censys',
  'platform': 'censys',
  'query': 'services.port:6379 and services.service_name:REDIS',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Kubernetes API Censys',
  'platform': 'censys',
  'query': 'services.port:6443 and services.tls.certificates.leaf_data.subject.organization:Kubernetes',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Docker API Censys',
  'platform': 'censys',
  'query': 'services.port:2375 and services.http.response.body:"DockerVersion"',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Jenkins Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"Dashboard [Jenkins]"',
  'category': 'ci_cd',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Kibana Censys',
  'platform': 'censys',
  'query': 'services.port:5601 and services.http.response.html_title:"Kibana"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Grafana Censys',
  'platform': 'censys',
  'query': 'services.port:3000 and services.http.response.html_title:"Grafana"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed etcd Censys',
  'platform': 'censys',
  'query': 'services.port:2379 and services.http.response.body:"etcdserver"',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Jupyter Censys',
  'platform': 'censys',
  'query': 'services.port:8888 and services.http.response.html_title:"Jupyter Notebook"',
  'category': 'debug',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Hadoop HDFS Censys',
  'platform': 'censys',
  'query': 'services.port:50070 and services.http.response.html_title:"Hadoop"',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed phpMyAdmin Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"phpMyAdmin"',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed RabbitMQ Censys',
  'platform': 'censys',
  'query': 'services.port:15672 and services.http.response.html_title:"RabbitMQ Management"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Prometheus Censys',
  'platform': 'censys',
  'query': 'services.port:9090 and services.http.response.html_title:"Prometheus"',
  'category': 'debug',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed Memcached Censys',
  'platform': 'censys',
  'query': 'services.port:11211 and services.service_name:MEMCACHED',
  'category': 'database',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed CouchDB Censys',
  'platform': 'censys',
  'query': 'services.port:5984 and services.http.response.body:"couchdb"',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Default Camera Login Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"IP Camera" and services.http.response.html_title:"Login"',
  'category': 'camera',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Splunk Censys',
  'platform': 'censys',
  'query': 'services.port:8000 and services.http.response.html_title:"Splunk"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Swagger UI Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"Swagger UI"',
  'category': 'debug',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed ZooKeeper Censys',
  'platform': 'censys',
  'query': 'services.port:2181 and services.banner:"Zookeeper"',
  'category': 'database',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Sonarqube Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"SonarQube"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Kubernetes Dashboard Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"Kubernetes Dashboard"',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed GitLab Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"GitLab" and services.http.response.body:"Sign in"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Drone CI Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"Drone"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed phpinfo Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"phpinfo()"',
  'category': 'debug',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Fortinet SSL VPN Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"SSL VPN" and services.software.product:Fortinet',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Default Tomcat Manager Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"Apache Tomcat" and services.http.response.body:"Manager App"',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed CassandraDB Shodan',
  'platform': 'shodan',
  'query': 'port:9042 "Cassandra"',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Default Hikvision Camera Login',
  'platform': 'shodan',
  'query': 'http.title:"Hikvision" port:80',
  'category': 'camera',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed D-Link Camera',
  'platform': 'shodan',
  'query': 'http.title:"D-Link" http.html:"stream"',
  'category': 'camera',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Dahua Camera',
  'platform': 'shodan',
  'query': 'http.title:"Dahua" port:37777',
  'category': 'camera',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed RTSP Camera Stream',
  'platform': 'shodan',
  'query': 'port:554 product:"RTSP"',
  'category': 'camera',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Siemens PLC',
  'platform': 'shodan',
  'query': 'product:"Siemens" port:102',
  'category': 'iot',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Modbus IoT',
  'platform': 'shodan',
  'query': 'port:502 product:"Modbus"',
  'category': 'iot',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Building Automation BACnet',
  'platform': 'shodan',
  'query': 'port:47808 product:"BACnet"',
  'category': 'iot',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Industrial SCADA',
  'platform': 'shodan',
  'query': 'port:102 "SIMATIC"',
  'category': 'iot',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Philips Hue Bridge',
  'platform': 'shodan',
  'query': 'http.title:"Philips hue"',
  'category': 'iot',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Default Asus Router Login',
  'platform': 'shodan',
  'query': 'http.title:"ASUS" http.html:"router"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed TP-Link Admin',
  'platform': 'shodan',
  'query': 'http.title:"TP-LINK" http.html:"admin"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Default Ubiquiti Admin',
  'platform': 'shodan',
  'query': 'http.title:"UniFi" product:"Ubiquiti"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Juniper Router',
  'platform': 'shodan',
  'query': 'http.title:"J-Web" product:"Juniper"',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Palo Alto Admin',
  'platform': 'shodan',
  'query': 'http.title:"Palo Alto Networks" port:443',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed CouchDB No Auth',
  'platform': 'shodan',
  'query': 'port:5984 http.title:"Overview" product:"CouchDB"',
  'category': 'database',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Portainer Docker UI',
  'platform': 'shodan',
  'query': 'http.title:"Portainer" port:9000',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Traefik Dashboard',
  'platform': 'shodan',
  'query': 'http.title:"Traefik" port:8080',
  'category': 'admin_panel',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed Consul UI',
  'platform': 'shodan',
  'query': 'port:8500 http.title:"Consul"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Vault UI',
  'platform': 'shodan',
  'query': 'port:8200 http.title:"Vault"',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Airflow UI',
  'platform': 'shodan',
  'query': 'http.title:"Airflow" port:8080',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Drone CI Shodan',
  'platform': 'shodan',
  'query': 'http.title:"Drone" port:80',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Artifactory',
  'platform': 'shodan',
  'query': 'http.title:"Artifactory" port:8081',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Nexus Repository',
  'platform': 'shodan',
  'query': 'http.title:"Nexus Repository" port:8081',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Bamboo CI',
  'platform': 'shodan',
  'query': 'http.title:"Bamboo" http.html:"Atlassian"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed TeamCity',
  'platform': 'shodan',
  'query': 'http.title:"TeamCity" port:8111',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed CircleCI Webhook',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:circleci',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Spring Boot Actuator',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:/actuator/env',
  'category': 'debug',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Spring Boot Mappings',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:/actuator/mappings',
  'category': 'debug',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Laravel Debug Page',
  'platform': 'google',
  'query': 'site:{DOMAIN} intitle:"Whoops!" intext:"APP_KEY"',
  'category': 'debug',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Django Debug Page',
  'platform': 'google',
  'query': 'site:{DOMAIN} intitle:"Django" intext:"DEBUG = True"',
  'category': 'debug',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Rails Error Page',
  'platform': 'google',
  'query': 'site:{DOMAIN} intitle:"Rails" intext:"Application Trace"',
  'category': 'debug',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Nginx Status',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:/nginx_status',
  'category': 'debug',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed Apache Server Status',
  'platform': 'google',
  'query': 'site:{DOMAIN} inurl:/server-status',
  'category': 'debug',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed Sensitive JSON Files',
  'platform': 'google',
  'query': 'site:{DOMAIN} filetype:json inurl:credentials',
  'category': 'config',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed AWS Config File',
  'platform': 'google',
  'query': 'site:{DOMAIN} filetype:cfg inurl:aws',
  'category': 'config',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Docker Compose File',
  'platform': 'google',
  'query': 'site:{DOMAIN} filetype:yml inurl:docker-compose',
  'category': 'config',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Terraform State File',
  'platform': 'google',
  'query': 'site:{DOMAIN} filetype:tfstate',
  'category': 'config',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Ansible Playbook',
  'platform': 'google',
  'query': 'site:{DOMAIN} filetype:yml inurl:playbook',
  'category': 'config',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Vault Token in Code',
  'platform': 'github',
  'query': 'org:{DOMAIN} VAULT_TOKEN filename:*.sh',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked Terraform State',
  'platform': 'github',
  'query': 'org:{DOMAIN} filename:terraform.tfstate password',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked Azure Credentials',
  'platform': 'github',
  'query': 'org:{DOMAIN} AZURE_CLIENT_SECRET OR AZURE_SUBSCRIPTION_ID',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked JWT Secret',
  'platform': 'github',
  'query': 'org:{DOMAIN} JWT_SECRET OR jwt_secret_key',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked Database URL',
  'platform': 'github',
  'query': 'org:{DOMAIN} DATABASE_URL filename:.env',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked FTP Credentials',
  'platform': 'github',
  'query': 'org:{DOMAIN} FTP_PASSWORD OR ftp_pass',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Leaked Mailgun API Key',
  'platform': 'github',
  'query': 'org:{DOMAIN} MAILGUN_API_KEY',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Leaked Firebase Config',
  'platform': 'github',
  'query': 'org:{DOMAIN} firebaseio.com apiKey',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Leaked Okta Token',
  'platform': 'github',
  'query': 'org:{DOMAIN} OKTA_API_TOKEN',
  'category': 'leaked_secrets',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Leaked Datadog API Key',
  'platform': 'github',
  'query': 'org:{DOMAIN} DATADOG_API_KEY',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Leaked PagerDuty Token',
  'platform': 'github',
  'query': 'org:{DOMAIN} PAGERDUTY_API_KEY',
  'category': 'leaked_secrets',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Leaked New Relic License Key',
  'platform': 'github',
  'query': 'org:{DOMAIN} NEW_RELIC_LICENSE_KEY',
  'category': 'leaked_secrets',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Leaked Salesforce Credentials',
  'platform': 'github',
  'query': 'org:{DOMAIN} SALESFORCE_PASSWORD OR SF_PASSWORD',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Leaked Jira API Token',
  'platform': 'github',
  'query': 'org:{DOMAIN} JIRA_API_TOKEN',
  'category': 'leaked_secrets',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Leaked Confluence Credentials',
  'platform': 'github',
  'query': 'org:{DOMAIN} CONFLUENCE_PASSWORD',
  'category': 'leaked_secrets',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Portainer Censys',
  'platform': 'censys',
  'query': 'services.port:9000 and services.http.response.html_title:"Portainer"',
  'category': 'kubernetes',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Vault UI Censys',
  'platform': 'censys',
  'query': 'services.port:8200 and services.http.response.html_title:"Vault"',
  'category': 'admin_panel',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Consul Censys',
  'platform': 'censys',
  'query': 'services.port:8500 and services.http.response.html_title:"Consul"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Traefik Censys',
  'platform': 'censys',
  'query': 'services.port:8080 and services.http.response.html_title:"Traefik"',
  'category': 'admin_panel',
  'severity_if_found': 'MEDIUM'},
 {'name': 'Exposed Airflow Censys',
  'platform': 'censys',
  'query': 'services.port:8080 and services.http.response.html_title:"Airflow"',
  'category': 'admin_panel',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed TeamCity Censys',
  'platform': 'censys',
  'query': 'services.port:8111 and services.http.response.html_title:"TeamCity"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Nexus Censys',
  'platform': 'censys',
  'query': 'services.port:8081 and services.http.response.html_title:"Nexus Repository"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Artifactory Censys',
  'platform': 'censys',
  'query': 'services.port:8081 and services.http.response.html_title:"Artifactory"',
  'category': 'ci_cd',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Hikvision Camera Censys',
  'platform': 'censys',
  'query': 'services.http.response.html_title:"Hikvision"',
  'category': 'camera',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed RTSP Stream Censys',
  'platform': 'censys',
  'query': 'services.port:554 and services.service_name:RTSP',
  'category': 'camera',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed BACnet IoT Censys',
  'platform': 'censys',
  'query': 'services.port:47808 and services.service_name:BACNET',
  'category': 'iot',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Modbus IoT Censys',
  'platform': 'censys',
  'query': 'services.port:502 and services.service_name:MODBUS',
  'category': 'iot',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Default Credentials IoT',
  'platform': 'shodan',
  'query': 'http.html:"admin" http.html:"password" "default"',
  'category': 'iot',
  'severity_if_found': 'CRITICAL'},
 {'name': 'Exposed Samsung SmartCam',
  'platform': 'shodan',
  'query': 'http.title:"SmartCam" product:"Samsung"',
  'category': 'camera',
  'severity_if_found': 'HIGH'},
 {'name': 'Exposed Foscam Camera',
  'platform': 'shodan',
  'query': 'http.title:"Foscam" port:88',
  'category': 'camera',
  'severity_if_found': 'HIGH'}]
