"""takeover_signatures — generated dev-time by Claude. Recon module asset.
"""

TAKEOVER_SIGNATURES = [{'service': 'AWS S3',
  'cname_patterns': ['s3\\.amazonaws\\.com$', 's3-website[.-][a-z0-9-]+\\.amazonaws\\.com$'],
  'fingerprint_body': 'NoSuchBucket|The specified bucket does not exist',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Unclaimed S3 bucket; register the bucket name to serve arbitrary content under the victim domain.'},
 {'service': 'AWS S3 Website',
  'cname_patterns': ['s3-website\\.amazonaws\\.com$', 's3-website-[a-z0-9-]+\\.amazonaws\\.com$'],
  'fingerprint_body': 'NoSuchBucket|The specified bucket does not exist|Code: NoSuchBucket',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'S3 static website endpoint pointing to deleted bucket; create the bucket to take over the '
                   'subdomain.'},
 {'service': 'AWS CloudFront',
  'cname_patterns': ['cloudfront\\.net$'],
  'fingerprint_body': 'Bad request|ERROR: The request could not be satisfied|d[0-9a-z]+\\.cloudfront\\.net',
  'fingerprint_status': 403,
  'severity': 'HIGH',
  'documentation': 'CloudFront distribution origin misconfigured or distribution deleted; claim the distribution to '
                   'intercept traffic.'},
 {'service': 'AWS Elastic Beanstalk',
  'cname_patterns': ['elasticbeanstalk\\.com$', '[a-z0-9-]+\\.elasticbeanstalk\\.com$'],
  'fingerprint_body': '404 Not Found|No Application|There is no application deployed',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Elastic Beanstalk environment deleted but CNAME remains; recreate the environment name to take '
                   'over.'},
 {'service': 'AWS Elastic Beanstalk (regional)',
  'cname_patterns': ['[a-z0-9-]+\\.[a-z0-9-]+\\.elasticbeanstalk\\.com$'],
  'fingerprint_body': '404 Not Found|No Application',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Regional Elastic Beanstalk CNAME pointing to unclaimed environment; register environment to '
                   'control the subdomain.'},
 {'service': 'Heroku',
  'cname_patterns': ['\\.herokuapp\\.com$', '\\.herokussl\\.com$', '\\.herokudns\\.com$'],
  'fingerprint_body': "No such app|herokucdn\\.com/error-pages/no-such-app\\.html|There's nothing here",
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Heroku app deleted but custom domain CNAME still points to Heroku; register a new app with the '
                   'same name.'},
 {'service': 'Heroku SSL',
  'cname_patterns': ['\\.herokussl\\.com$'],
  'fingerprint_body': 'No such app|herokucdn',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Heroku SSL endpoint CNAME dangling after app removal; claim the app name on Heroku to take over.'},
 {'service': 'Fly.io',
  'cname_patterns': ['\\.fly\\.dev$', '\\.flycast\\.dev$'],
  'fingerprint_body': '404 Not Found|fly\\.io|Unknown app|App not found',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Fly.io app removed but subdomain CNAME remains; deploy a new app with the matching hostname.'},
 {'service': 'Render',
  'cname_patterns': ['\\.onrender\\.com$'],
  'fingerprint_body': 'Service not found|onrender\\.com|404|No such service',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Render service deleted; re-register the service name on Render to control the subdomain.'},
 {'service': 'GitHub Pages',
  'cname_patterns': ['\\.github\\.io$', '\\.github\\.com$'],
  'fingerprint_body': "There isn't a GitHub Pages site here|404 There is nothing here|For root URLs.*github\\.io",
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'GitHub Pages site removed or repo deleted; create a repo with the matching name to serve content.'},
 {'service': 'GitLab Pages',
  'cname_patterns': ['\\.gitlab\\.io$'],
  'fingerprint_body': "404|GitLab Pages.*not found|The page you're looking for could not be found",
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'GitLab Pages project deleted; register a GitLab project with the matching namespace/project name.'},
 {'service': 'Cloudflare Pages',
  'cname_patterns': ['\\.pages\\.dev$'],
  'fingerprint_body': 'NOT_FOUND|There is nothing here|1000|Cloudflare Pages project not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Cloudflare Pages project removed; create a Pages project with the same subdomain name.'},
 {'service': 'Vercel',
  'cname_patterns': ['\\.vercel\\.app$', '\\.now\\.sh$', 'cname\\.vercel-dns\\.com$'],
  'fingerprint_body': 'The deployment could not be found|DEPLOYMENT_NOT_FOUND|This deployment has been removed',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Vercel deployment removed but CNAME or alias remains; deploy a Vercel project claiming the alias.'},
 {'service': 'Vercel (now.sh)',
  'cname_patterns': ['\\.now\\.sh$'],
  'fingerprint_body': '404|The deployment could not be found|DEPLOYMENT_NOT_FOUND',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Legacy Vercel/Zeit now.sh deployment removed; claim alias by deploying to Vercel with matching '
                   'domain.'},
 {'service': 'Netlify',
  'cname_patterns': ['\\.netlify\\.app$', '\\.netlify\\.com$'],
  'fingerprint_body': 'Not Found|netlify|No such site|Page Not Found',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Netlify site removed; register a new site on Netlify with the same subdomain name.'},
 {'service': 'Netlify Custom Domain',
  'cname_patterns': ['[a-z0-9-]+\\.netlify\\.com$'],
  'fingerprint_body': 'No such site|Not Found|Netlify',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Netlify custom domain CNAME pointing to unclaimed site; claim the site name on Netlify.'},
 {'service': 'Azure Blob Storage',
  'cname_patterns': ['\\.blob\\.core\\.windows\\.net$'],
  'fingerprint_body': 'BlobNotFound|The specified container does not exist|ResourceNotFound|StorageErrorCode',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Azure Blob Storage container deleted; recreate the storage account and container to take over.'},
 {'service': 'Azure CDN',
  'cname_patterns': ['\\.azureedge\\.net$'],
  'fingerprint_body': 'CDN endpoint not found|The resource you are looking for has been removed|404|azureedge',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Azure CDN endpoint deleted; register a new CDN endpoint with the same name in Azure.'},
 {'service': 'Azure Front Door',
  'cname_patterns': ['\\.azurefd\\.net$'],
  'fingerprint_body': 'Front Door|404|The resource you are looking for|azurefd\\.net',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Azure Front Door profile/endpoint removed; create a new Front Door with matching hostname.'},
 {'service': 'Azure App Service',
  'cname_patterns': ['\\.azurewebsites\\.net$'],
  'fingerprint_body': '404 Web Site not found|Error 404 - Web app not found|Web App not found|No website is configured',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Azure App Service app deleted; register the app name on Azure to serve content under the '
                   'subdomain.'},
 {'service': 'Azure App Service (SCM)',
  'cname_patterns': ['\\.scm\\.azurewebsites\\.net$'],
  'fingerprint_body': '404 Web Site not found|No website is configured|Web App not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Azure App Service SCM endpoint dangling; register the app name to access deployment interface.'},
 {'service': 'Azure Traffic Manager',
  'cname_patterns': ['\\.trafficmanager\\.net$'],
  'fingerprint_body': '404|Traffic Manager profile.*not found|No traffic manager endpoint',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Azure Traffic Manager profile removed; register a new profile with the same name.'},
 {'service': 'GCP Cloud Storage',
  'cname_patterns': ['storage\\.googleapis\\.com$', 'c\\.storage\\.googleapis\\.com$'],
  'fingerprint_body': 'NoSuchBucket|The specified bucket does not exist|BucketNotFound|404',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'GCP Cloud Storage bucket deleted; create a bucket with the matching name to serve content.'},
 {'service': 'GCP App Engine',
  'cname_patterns': ['\\.appspot\\.com$', '[a-z0-9-]+\\.appspot\\.com$'],
  'fingerprint_body': '404 Not Found|This application does not exist|Error: Application not found|appspot',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'GCP App Engine application removed; register the project ID on GCP App Engine to take over.'},
 {'service': 'Firebase Hosting',
  'cname_patterns': ['\\.firebaseapp\\.com$', '\\.web\\.app$'],
  'fingerprint_body': 'Firebase App Not Found|404|No site configured|The hosting site.*not found',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Firebase Hosting site deleted; register the Firebase project with matching name to serve arbitrary '
                   'content.'},
 {'service': 'Firebase Hosting (web.app)',
  'cname_patterns': ['\\.web\\.app$'],
  'fingerprint_body': 'Firebase App Not Found|404|No site configured',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Firebase web.app hosting site removed; claim the project name on Firebase to take over the '
                   'subdomain.'},
 {'service': 'Fastly',
  'cname_patterns': ['\\.fastly\\.net$', '\\.fastlylb\\.net$', 'global\\.prod\\.fastly\\.net$'],
  'fingerprint_body': 'Fastly error: unknown domain|Please check that this domain has been added to a service|fastly',
  'fingerprint_status': 500,
  'severity': 'CRITICAL',
  'documentation': 'Fastly service removed but CNAME remains; configure a new Fastly service with the matching '
                   'domain.'},
 {'service': 'Fastly (SSL)',
  'cname_patterns': ['ssl\\.fastly\\.net$'],
  'fingerprint_body': 'Fastly error: unknown domain|fastly\\.net',
  'fingerprint_status': 500,
  'severity': 'HIGH',
  'documentation': 'Fastly SSL endpoint unclaimed; register service on Fastly pointing to the dangling subdomain.'},
 {'service': 'BunnyCDN',
  'cname_patterns': ['\\.b-cdn\\.net$', '\\.bunnycdn\\.com$'],
  'fingerprint_body': 'Pull Zone Not Found|404|BunnyCDN|The pull zone you are trying to access does not exist',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'BunnyCDN pull zone deleted; create a pull zone with matching hostname to intercept traffic.'},
 {'service': 'Zendesk',
  'cname_patterns': ['\\.zendesk\\.com$'],
  'fingerprint_body': "Help Center Closed|This help center no longer exists|Oops.*We couldn't find the page you're "
                      'looking for',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Zendesk Help Center removed; register a Zendesk account with the matching subdomain.'},
 {'service': 'Zendesk Custom Domain',
  'cname_patterns': ['[a-z0-9-]+\\.zendesk\\.com$'],
  'fingerprint_body': 'Help Center Closed|Oops|Page Not Found|zendesk',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Custom Zendesk help center CNAME dangling after account cancellation; claim the Zendesk '
                   'subdomain.'},
 {'service': 'Statuspage',
  'cname_patterns': ['\\.statuspage\\.io$'],
  'fingerprint_body': 'You are being redirected|StatusPage.*not found|status page.*not found|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Atlassian Statuspage removed; create a new status page with the matching subdomain.'},
 {'service': 'Tilda',
  'cname_patterns': ['\\.tilda\\.ws$', '\\.tildacdn\\.com$'],
  'fingerprint_body': 'Please renew your plan|Domain is not connected|Tilda.*404|This page is no longer available',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Tilda project expired or deleted; register a new Tilda project and connect the domain.'},
 {'service': 'Surge.sh',
  'cname_patterns': ['\\.surge\\.sh$'],
  'fingerprint_body': "project not found|surge\\.sh|doesn't exist here|404",
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Surge.sh project unpublished; run surge on any directory with the matching domain name to take '
                   'over.'},
 {'service': 'Webflow',
  'cname_patterns': ['\\.webflow\\.io$'],
  'fingerprint_body': "The page you are looking for doesn't exist|webflow|404|Site Not Found",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Webflow project deleted; create a Webflow project and publish it to the matching subdomain.'},
 {'service': 'Tumblr',
  'cname_patterns': ['\\.tumblr\\.com$', 'domains\\.tumblr\\.com$'],
  'fingerprint_body': "There's nothing here|Whatever you were looking for doesn't live here|tumblr|404",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Tumblr blog deleted; create a Tumblr blog and configure custom domain to serve content.'},
 {'service': 'Shopify',
  'cname_patterns': ['\\.myshopify\\.com$', 'shops\\.myshopify\\.com$'],
  'fingerprint_body': 'Sorry, this shop is currently unavailable|myshopify|Store not found|Only one step left',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Shopify store closed or subdomain unclaimed; register a Shopify store with the matching myshopify '
                   'subdomain.'},
 {'service': 'ReadTheDocs',
  'cname_patterns': ['\\.readthedocs\\.io$', '\\.readthedocs\\.org$'],
  'fingerprint_body': 'This domain is not connected to a project|Project not found|Read the Docs|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'ReadTheDocs project removed; register a new RTD project and configure custom domain to take over.'},
 {'service': 'GitBook',
  'cname_patterns': ['\\.gitbook\\.io$', '\\.gitbook\\.com$'],
  'fingerprint_body': 'This space does not exist|Page not found|gitbook|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'GitBook space deleted; create a GitBook space and configure DNS to serve content under the victim '
                   'domain.'},
 {'service': 'Pantheon',
  'cname_patterns': ['\\.pantheonsite\\.io$', '\\.pantheon\\.io$'],
  'fingerprint_body': 'The gods are wise|404 error unknown site|Pantheon.*site.*not found|unknown site',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Pantheon site environment removed; register a Pantheon site with the matching environment name.'},
 {'service': 'WPEngine',
  'cname_patterns': ['\\.wpengine\\.com$'],
  'fingerprint_body': 'Install not found|This install has been deleted|404|wpengine',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'WPEngine WordPress install deleted; create an install with the matching name on WPEngine.'},
 {'service': 'Mailgun',
  'cname_patterns': ['email\\.mailgun\\.org$', '\\.mailgun\\.org$'],
  'fingerprint_body': 'The URL.*is not configured|404|mailgun|Domain not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Mailgun sending domain removed; register the domain on Mailgun to intercept or spoof emails.'},
 {'service': 'SendGrid',
  'cname_patterns': ['sendgrid\\.net$', 'u[0-9]+\\.wl[0-9]+\\.sendgrid\\.net$'],
  'fingerprint_body': 'The requested URL was not found|404|sendgrid',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'SendGrid whitelabel domain removed; claim the domain on SendGrid to send email appearing from the '
                   'victim domain.'},
 {'service': 'Postmark',
  'cname_patterns': ['pm\\.mtasv\\.net$', '\\.mtasv\\.net$'],
  'fingerprint_body': '404|The page you requested was not found|postmark|mtasv',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Postmark tracking/bounce domain CNAME dangling; register the domain on Postmark to intercept email '
                   'bounces.'},
 {'service': 'AWS S3 (us-east-1)',
  'cname_patterns': ['s3-us-east-1\\.amazonaws\\.com$'],
  'fingerprint_body': 'NoSuchBucket|The specified bucket does not exist',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'US-East-1 S3 bucket CNAME dangling; create the bucket in us-east-1 to take over the subdomain.'},
 {'service': 'AWS S3 (us-west-2)',
  'cname_patterns': ['s3-us-west-2\\.amazonaws\\.com$', 's3\\.us-west-2\\.amazonaws\\.com$'],
  'fingerprint_body': 'NoSuchBucket|The specified bucket does not exist',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'US-West-2 S3 bucket CNAME dangling; create the bucket in us-west-2 to take over the subdomain.'},
 {'service': 'AWS S3 (eu-west-1)',
  'cname_patterns': ['s3-eu-west-1\\.amazonaws\\.com$', 's3\\.eu-west-1\\.amazonaws\\.com$'],
  'fingerprint_body': 'NoSuchBucket|The specified bucket does not exist',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'EU-West-1 S3 bucket CNAME dangling; create the bucket in eu-west-1 to take over the subdomain.'},
 {'service': 'AWS S3 (ap-southeast-1)',
  'cname_patterns': ['s3-ap-southeast-1\\.amazonaws\\.com$', 's3\\.ap-southeast-1\\.amazonaws\\.com$'],
  'fingerprint_body': 'NoSuchBucket|The specified bucket does not exist',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'AP-Southeast-1 S3 bucket CNAME dangling; create bucket in ap-southeast-1 to take over the '
                   'subdomain.'},
 {'service': 'AWS CloudFront (alternate domain)',
  'cname_patterns': ['[a-z0-9]+\\.cloudfront\\.net$'],
  'fingerprint_body': 'ERROR: The request could not be satisfied|Bad request|CloudFront|403 ERROR',
  'fingerprint_status': 403,
  'severity': 'HIGH',
  'documentation': 'CloudFront alternate domain CNAME pointing to deleted distribution; recreate distribution to take '
                   'over.'},
 {'service': 'AWS Global Accelerator',
  'cname_patterns': ['\\.awsglobalaccelerator\\.com$'],
  'fingerprint_body': '404|The accelerator you requested was not found|Not Found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'AWS Global Accelerator endpoint removed; register the accelerator to redirect traffic.'},
 {'service': 'Heroku (custom domain)',
  'cname_patterns': ['proxy\\.heroku\\.com$', 'ssl\\.herokudns\\.com$'],
  'fingerprint_body': 'No such app|herokucdn|no app configured',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Heroku custom domain proxy CNAME pointing to deleted app; register app on Heroku to serve '
                   'content.'},
 {'service': 'Fly.io (custom domain)',
  'cname_patterns': ['[a-z0-9-]+\\.fly\\.dev$'],
  'fingerprint_body': '404|App not found|Unknown app|fly\\.io',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Fly.io app subdomain pointing to unclaimed application; deploy a new Fly app with matching name.'},
 {'service': 'Render (static site)',
  'cname_patterns': ['[a-z0-9-]+\\.onrender\\.com$'],
  'fingerprint_body': 'Service not found|404|No such service|onrender',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Render static site or web service removed; register service on Render with matching subdomain.'},
 {'service': 'GitHub Pages (org)',
  'cname_patterns': ['[a-z0-9-]+\\.github\\.io$'],
  'fingerprint_body': "There isn't a GitHub Pages site here|404|For root URLs",
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'GitHub org/user Pages site removed; create the matching GitHub Pages repository to take over.'},
 {'service': 'Cloudflare Pages (custom)',
  'cname_patterns': ['[a-z0-9-]+\\.pages\\.dev$'],
  'fingerprint_body': 'NOT_FOUND|1000|Cloudflare|There is nothing here',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Cloudflare Pages project with custom domain deleted; register new Pages project with same '
                   'subdomain.'},
 {'service': 'Vercel (preview)',
  'cname_patterns': ['[a-z0-9-]+-[a-z0-9]+\\.vercel\\.app$'],
  'fingerprint_body': 'DEPLOYMENT_NOT_FOUND|The deployment could not be found|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Vercel preview deployment URL dangling; redeploy to Vercel with matching preview URL pattern.'},
 {'service': 'Netlify (branch deploy)',
  'cname_patterns': ['[a-z0-9-]+--[a-z0-9-]+\\.netlify\\.app$'],
  'fingerprint_body': 'Not Found|No such site|netlify|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Netlify branch deploy URL dangling after site deletion; register the site name to take over.'},
 {'service': 'Azure Static Web Apps',
  'cname_patterns': ['\\.azurestaticapps\\.net$'],
  'fingerprint_body': '404 Not Found|Azure Static Web Apps|This Azure Static Web App is waiting',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Azure Static Web Apps site removed; register a new static web app with the matching hostname.'},
 {'service': 'Azure API Management',
  'cname_patterns': ['\\.azure-api\\.net$'],
  'fingerprint_body': 'ResourceNotFound|404|The specified API management',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Azure API Management gateway deleted; create a new APIM instance with the same subdomain.'},
 {'service': 'GCP Firebase Realtime DB',
  'cname_patterns': ['\\.firebaseio\\.com$'],
  'fingerprint_body': '404|error.*not found|Firebase.*not found|This project does not exist',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Firebase Realtime Database project removed; register the project name on Firebase to serve data.'},
 {'service': 'GCP Cloud Run',
  'cname_patterns': ['\\.run\\.app$', '[a-z0-9-]+-[a-z0-9]+\\.run\\.app$'],
  'fingerprint_body': '404|Service not found|Cloud Run.*not found',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'GCP Cloud Run service deleted; deploy a new service with matching name to intercept traffic.'},
 {'service': 'Fastly (non-SNI)',
  'cname_patterns': ['prod\\.hosts\\.fastly\\.net$', 'nonssl\\.global\\.fastly\\.net$'],
  'fingerprint_body': 'Fastly error: unknown domain|fastly|please check that this domain',
  'fingerprint_status': 500,
  'severity': 'CRITICAL',
  'documentation': 'Fastly non-SNI endpoint unclaimed; configure a Fastly service to serve content on the victim '
                   'subdomain.'},
 {'service': 'BunnyCDN (pull zone)',
  'cname_patterns': ['[a-z0-9-]+\\.b-cdn\\.net$'],
  'fingerprint_body': 'Pull Zone Not Found|404|BunnyCDN|The pull zone',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'BunnyCDN pull zone removed; register a new pull zone with matching name.'},
 {'service': 'Zendesk (Guide)',
  'cname_patterns': ['[a-z0-9-]+\\.zendesk\\.com$'],
  'fingerprint_body': 'Zendesk.*closed|Help Center Closed|This help center no longer exists',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Zendesk Guide Help Center disabled; register new Zendesk account to serve content under the '
                   'CNAME.'},
 {'service': 'Statuspage (custom)',
  'cname_patterns': ['[a-z0-9-]+\\.statuspage\\.io$'],
  'fingerprint_body': '404|Status page not found|This status page no longer exists',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Custom Statuspage domain pointing to unclaimed page; register new status page with matching '
                   'subdomain.'},
 {'service': 'Shopify (custom domain)',
  'cname_patterns': ['shops\\.shopify\\.com$', '[a-z0-9-]+\\.myshopify\\.com$'],
  'fingerprint_body': 'Only one step left|myshopify|Store not found|Sorry, this shop',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Shopify custom domain CNAME dangling; register a Shopify store claiming the subdomain.'},
 {'service': 'ReadTheDocs (custom domain)',
  'cname_patterns': ['readthedocs\\.io$', 'readthedocs\\.org$'],
  'fingerprint_body': 'This domain is not connected|Read the Docs|Project not found|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'ReadTheDocs custom domain not connected to a project; register a project and add custom domain.'},
 {'service': 'GitBook (legacy)',
  'cname_patterns': ['[a-z0-9-]+\\.gitbooks\\.io$'],
  'fingerprint_body': 'gitbooks|Page not found|This space does not exist|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Legacy GitBook site removed; claim the GitBook subdomain by creating a new book/space.'},
 {'service': 'Pantheon (dev environment)',
  'cname_patterns': ['dev-[a-z0-9-]+\\.pantheonsite\\.io$'],
  'fingerprint_body': '404 error unknown site|The gods are wise|Pantheon|unknown site',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Pantheon dev environment CNAME dangling after site deletion; register the site on Pantheon.'},
 {'service': 'WPEngine (staging)',
  'cname_patterns': ['[a-z0-9-]+\\.staging\\.wpengine\\.com$'],
  'fingerprint_body': 'Install not found|404|wpengine|This install has been deleted',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'WPEngine staging environment removed; create a WPEngine install with the matching name.'},
 {'service': 'Mailgun (tracking)',
  'cname_patterns': ['[a-z0-9-]+\\.mailgun\\.org$'],
  'fingerprint_body': '404|Domain not found|mailgun|The URL.*is not configured',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Mailgun tracking domain CNAME dangling; register the domain on Mailgun to intercept email links.'},
 {'service': 'SendGrid (custom links)',
  'cname_patterns': ['em[0-9]+\\.[a-z0-9.-]+$', 'u[0-9]+\\.wl[0-9]+\\.sendgrid\\.net$'],
  'fingerprint_body': '404|The requested URL was not found|sendgrid',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'SendGrid custom link whitelabel CNAME unclaimed; register on SendGrid to control email click '
                   'tracking.'},
 {'service': 'Postmark (bounce)',
  'cname_patterns': ['pm-bounces\\.[a-z0-9.-]+$'],
  'fingerprint_body': '404|Not Found|postmark|mtasv',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Postmark bounce tracking CNAME dangling; register domain on Postmark to intercept bounce '
                   'notifications.'},
 {'service': 'AWS Amplify',
  'cname_patterns': ['\\.amplifyapp\\.com$', '[a-z0-9]+\\.amplifyapp\\.com$'],
  'fingerprint_body': '404|App not found|AWS Amplify|Branch not found',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'AWS Amplify app or branch removed; create an Amplify app with matching subdomain to take over.'},
 {'service': 'AWS API Gateway',
  'cname_patterns': ['[a-z0-9]+\\.execute-api\\.[a-z0-9-]+\\.amazonaws\\.com$'],
  'fingerprint_body': '403 Forbidden|Missing Authentication Token|404|Invalid API',
  'fingerprint_status': 403,
  'severity': 'HIGH',
  'documentation': 'AWS API Gateway custom domain pointing to deleted API; register new API Gateway to intercept '
                   'requests.'},
 {'service': 'Azure Functions',
  'cname_patterns': ['\\.azurewebsites\\.net$', '[a-z0-9-]+\\.azurewebsites\\.net$'],
  'fingerprint_body': 'Function not found|404|Azure Functions|This function app has been stopped',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Azure Functions app deleted; register the function app name on Azure to serve responses.'},
 {'service': 'GCP Cloud Functions',
  'cname_patterns': ['\\.cloudfunctions\\.net$', '[a-z0-9-]+-[a-z0-9]+\\.cloudfunctions\\.net$'],
  'fingerprint_body': '404|Not Found|Cloud Functions|Function not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'GCP Cloud Functions endpoint removed; deploy a function with matching name to take over.'},
 {'service': 'Cloudflare Workers',
  'cname_patterns': ['\\.workers\\.dev$', '[a-z0-9-]+\\.workers\\.dev$'],
  'fingerprint_body': '1101|Error 1101|workers\\.dev|Script not found|No route',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Cloudflare Workers script removed; deploy a Worker with matching subdomain to intercept requests.'},
 {'service': 'Surge.sh (custom)',
  'cname_patterns': ['na-west1\\.surge\\.sh$', 'na-east1\\.surge\\.sh$'],
  'fingerprint_body': "project not found|surge\\.sh|doesn't exist here",
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Surge.sh regional domain unclaimed; publish a Surge project with the matching domain name.'},
 {'service': 'Webflow (Enterprise)',
  'cname_patterns': ['proxy-ssl\\.webflow\\.com$', 'proxy\\.webflow\\.com$'],
  'fingerprint_body': 'Site Not Found|The page you are looking for|webflow|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Webflow enterprise proxy CNAME dangling; register a Webflow project and publish to claim the '
                   'domain.'},
 {'service': 'Tumblr (custom domain)',
  'cname_patterns': ['domains\\.tumblr\\.com$'],
  'fingerprint_body': "There's nothing here|tumblr|Whatever you were looking for|404",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Tumblr custom domain CNAME pointing to unclaimed blog; create a Tumblr blog with the custom '
                   'domain.'},
 {'service': 'Intercom',
  'cname_patterns': ['custom\\.intercom\\.help$', '[a-z0-9-]+\\.intercom\\.help$'],
  'fingerprint_body': "Uh oh. That page doesn't exist|intercom|404|This page is gone",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Intercom Help Center removed; register an Intercom workspace and configure custom domain.'},
 {'service': 'HubSpot',
  'cname_patterns': ['\\.hs-sites\\.com$', '\\.hubspot\\.net$'],
  'fingerprint_body': 'does not exist|404|HubSpot|This page.*not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'HubSpot CMS site or landing page removed; register a HubSpot account with the matching subdomain.'},
 {'service': 'Ghost',
  'cname_patterns': ['\\.ghost\\.io$'],
  'fingerprint_body': '404|Domain is not configured|Ghost.*not found|Failed to load',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Ghost Pro blog removed; register a Ghost Pro subscription with the matching subdomain.'},
 {'service': 'Squarespace',
  'cname_patterns': ['ext-cust\\.squarespace\\.com$', '\\.squarespace\\.com$'],
  'fingerprint_body': "If you're moving your domain away|squarespace|404|Page Not Found",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Squarespace site removed or domain disconnected; register a Squarespace site pointing to the '
                   'CNAME.'},
 {'service': 'Cargo Collective',
  'cname_patterns': ['\\.cargo\\.site$', '[a-z0-9-]+\\.cargo\\.site$'],
  'fingerprint_body': '404|Page not found|cargo|This site is no longer available',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Cargo Collective site deleted; register a Cargo site with matching subdomain to take over.'},
 {'service': 'Bitbucket Pages',
  'cname_patterns': ['\\.bitbucket\\.io$'],
  'fingerprint_body': "Repository not found|404|bitbucket|The page you've requested does not exist",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Bitbucket Pages repository deleted; create a repo with matching team/project name to serve '
                   'content.'},
 {'service': 'SourceForge',
  'cname_patterns': ['\\.sourceforge\\.net$', '[a-z0-9-]+\\.sourceforge\\.net$'],
  'fingerprint_body': 'Project not found|404|SourceForge|No such project',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'SourceForge project removed; register a SourceForge project with matching name.'},
 {'service': 'AWS Lightsail',
  'cname_patterns': ['\\.lightsail\\.com$', '[a-z0-9-]+\\.lightsailserver\\.net$'],
  'fingerprint_body': '404|Instance not found|lightsail',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'AWS Lightsail instance deleted; create a new instance or static IP with matching domain '
                   'assignment.'},
 {'service': 'Digital Ocean App Platform',
  'cname_patterns': ['\\.ondigitalocean\\.app$'],
  'fingerprint_body': 'App not found|404|ondigitalocean|No app configured',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'DigitalOcean App Platform app removed; deploy a new app with matching subdomain.'},
 {'service': 'Digital Ocean Spaces',
  'cname_patterns': ['\\.digitaloceanspaces\\.com$'],
  'fingerprint_body': 'NoSuchBucket|The specified bucket does not exist|404',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'DigitalOcean Spaces bucket deleted; create a Space with the matching name to serve content.'},
 {'service': 'Kinsta',
  'cname_patterns': ['\\.kinsta\\.cloud$'],
  'fingerprint_body': "404|This site can't be reached|kinsta|No site found",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Kinsta managed WordPress site deleted; register a Kinsta site with the matching subdomain.'},
 {'service': 'Strikingly',
  'cname_patterns': ['\\.strikingly\\.com$', 'custom\\.strikingly\\.com$'],
  'fingerprint_body': 'Oops|404|strikingly|Page not found|This site is no longer available',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Strikingly site deleted; register a Strikingly account and connect custom domain.'},
 {'service': 'Wix',
  'cname_patterns': ['[a-z0-9-]+\\.wix\\.com$'],
  'fingerprint_body': "404|This site isn't available|wix|Site not found",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Wix site CNAME pointing to unclaimed site; create a Wix site and connect the custom domain.'},
 {'service': 'Launchrock',
  'cname_patterns': ['\\.launchrock\\.com$'],
  'fingerprint_body': 'It looks like you may have taken a wrong turn|404|launchrock',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Launchrock landing page removed; register a Launchrock account with matching subdomain.'},
 {'service': 'UserVoice',
  'cname_patterns': ['\\.uservoice\\.com$'],
  'fingerprint_body': '404|UserVoice|This UserVoice subdomain is not active|No such account',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'UserVoice feedback forum removed; register a UserVoice account with matching subdomain.'},
 {'service': 'Desk.com',
  'cname_patterns': ['\\.desk\\.com$'],
  'fingerprint_body': "404|Desk\\.com|Sorry.*can't find|Not found",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Desk.com support site removed; register Desk.com account with matching subdomain.'},
 {'service': 'Freshdesk',
  'cname_patterns': ['\\.freshdesk\\.com$'],
  'fingerprint_body': 'There is no helpdesk with this URL|freshdesk|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Freshdesk helpdesk account deactivated; register a Freshdesk account with the matching subdomain.'},
 {'service': 'Help Scout',
  'cname_patterns': ['\\.helpscoutdocs\\.com$'],
  'fingerprint_body': "No Docs site found|helpscout|404|This site doesn't exist",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Help Scout Docs site removed; create a Help Scout Docs site with matching subdomain.'},
 {'service': 'Intercom Articles',
  'cname_patterns': ['\\.intercomcdn\\.com$'],
  'fingerprint_body': '404|intercomcdn|Not Found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Intercom CDN domain dangling; register Intercom workspace to serve help articles.'},
 {'service': 'Unbounce',
  'cname_patterns': ['unbouncepages\\.com$', '[a-z0-9-]+\\.unbouncepages\\.com$'],
  'fingerprint_body': "The requested URL was not found|Unbounce|404|This page doesn't exist",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Unbounce landing page removed; register an Unbounce account and publish a page with matching '
                   'subdomain.'},
 {'service': 'Leadpages',
  'cname_patterns': ['\\.lpages\\.co$', '\\.leadpages\\.net$'],
  'fingerprint_body': '404|Leadpages|Page not found|This page is not available',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Leadpages page removed; register a Leadpages account and create a page with the matching custom '
                   'domain.'},
 {'service': 'Kajabi',
  'cname_patterns': ['\\.kajabi\\.com$', '[a-z0-9-]+\\.kajabi\\.com$'],
  'fingerprint_body': 'This site is no longer available|Kajabi|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Kajabi online course site removed; register a Kajabi site with matching subdomain.'},
 {'service': 'Teachable',
  'cname_patterns': ['\\.teachable\\.com$'],
  'fingerprint_body': "This school doesn't exist|teachable|404|School not found",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Teachable school site removed; register a Teachable school with matching subdomain.'},
 {'service': 'Thinkific',
  'cname_patterns': ['\\.thinkific\\.com$'],
  'fingerprint_body': 'This school could not be found|thinkific|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Thinkific school account removed; register a Thinkific account with matching subdomain.'},
 {'service': 'Podia',
  'cname_patterns': ['\\.podia\\.com$'],
  'fingerprint_body': "404|podia|Page not found|This store doesn't exist",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Podia storefront deleted; register a Podia account and configure the matching custom domain.'},
 {'service': 'Typeform',
  'cname_patterns': ['\\.typeform\\.com$'],
  'fingerprint_body': 'Oops|404|typeform|This form no longer exists',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Typeform embed or form page removed; register a Typeform account with matching custom subdomain.'},
 {'service': 'Netlify Large Media',
  'cname_patterns': ['[a-z0-9-]+\\.netlify\\.com$'],
  'fingerprint_body': '404|Not Found|netlify',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Netlify large media or function URL dangling; register the Netlify site name to take over.'},
 {'service': 'Microsoft Azure Container Instances',
  'cname_patterns': ['\\.azurecontainer\\.io$'],
  'fingerprint_body': '404|Container group not found|azurecontainer',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Azure Container Instance group deleted; register container group with same FQDN in Azure.'},
 {'service': 'Papertrail',
  'cname_patterns': ['\\.papertrailapp\\.com$'],
  'fingerprint_body': '404|Papertrail|Log destination not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Papertrail log destination removed; register a Papertrail account with matching subdomain.'},
 {'service': 'Pingdom',
  'cname_patterns': ['\\.pingdom\\.com$'],
  'fingerprint_body': 'Public status page not found|pingdom|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Pingdom public status page removed; register a Pingdom account and configure the status page.'},
 {'service': 'Canny',
  'cname_patterns': ['\\.canny\\.io$'],
  'fingerprint_body': "Company not found|canny|404|This board doesn't exist",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Canny feedback board removed; register a Canny account with matching subdomain.'},
 {'service': 'Productboard',
  'cname_patterns': ['\\.productboard\\.com$'],
  'fingerprint_body': '404|productboard|This portal no longer exists',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Productboard portal removed; register a Productboard account with matching custom subdomain.'},
 {'service': 'Copper CRM',
  'cname_patterns': ['\\.copper\\.com$'],
  'fingerprint_body': '404|copper|Not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Copper CRM portal CNAME dangling; register Copper account with matching subdomain.'},
 {'service': 'Notion (public page)',
  'cname_patterns': ['[a-z0-9-]+\\.notion\\.site$'],
  'fingerprint_body': '404|This page could not be found|notion|Page not published',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Notion public site page unpublished; register a Notion account and publish page to matching '
                   'subdomain.'},
 {'service': 'Carrd',
  'cname_patterns': ['\\.carrd\\.co$'],
  'fingerprint_body': "404|carrd|This site doesn't exist",
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Carrd one-page site removed; register a Carrd account and publish a site with matching custom '
                   'domain.'},
 {'service': 'Format',
  'cname_patterns': ['\\.format\\.com$'],
  'fingerprint_body': '404|format|This website is no longer available',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Format portfolio site removed; register Format account and configure the custom domain.'},
 {'service': 'SmugMug',
  'cname_patterns': ['\\.smugmug\\.com$'],
  'fingerprint_body': 'Page Not Found|smugmug|404|This page no longer exists',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'SmugMug gallery removed; create a SmugMug account with matching custom domain.'},
 {'service': 'Webflow (Editor)',
  'cname_patterns': ['editor\\.wf\\.io$'],
  'fingerprint_body': '404|Site Not Found|webflow',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Webflow editor endpoint dangling; register a Webflow project to take over the editor subdomain.'},
 {'service': 'Heroku (pipeline)',
  'cname_patterns': ['[a-z0-9-]+-staging\\.herokuapp\\.com$', '[a-z0-9-]+-production\\.herokuapp\\.com$'],
  'fingerprint_body': 'No such app|herokucdn|404',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Heroku pipeline staging/production app deleted; register app with matching name on Heroku.'},
 {'service': 'AWS Cognito',
  'cname_patterns': ['[a-z0-9-]+\\.auth\\.[a-z0-9-]+\\.amazoncognito\\.com$'],
  'fingerprint_body': '404|Not found|Cognito|User pool not found',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'AWS Cognito custom auth domain removed; register user pool with same domain to intercept auth '
                   'tokens.'},
 {'service': 'AWS OpenSearch',
  'cname_patterns': ['[a-z0-9-]+\\.[a-z0-9-]+\\.es\\.amazonaws\\.com$'],
  'fingerprint_body': 'Domain not found|404|OpenSearch|Elasticsearch',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'AWS OpenSearch/Elasticsearch domain deleted; create a new domain with matching name.'},
 {'service': 'GCP Cloud Endpoints',
  'cname_patterns': ['[a-z0-9-]+\\.endpoints\\.[a-z0-9-]+\\.cloud\\.goog$'],
  'fingerprint_body': '404|Service not found|Cloud Endpoints',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'GCP Cloud Endpoints service removed; redeploy the endpoint configuration with matching service '
                   'name.'},
 {'service': 'Fastly CDN (ssl)',
  'cname_patterns': ['dualstack\\.n\\.sni\\.global\\.fastly\\.net$'],
  'fingerprint_body': 'Fastly error: unknown domain|fastly',
  'fingerprint_status': 500,
  'severity': 'CRITICAL',
  'documentation': 'Fastly dual-stack SNI endpoint unclaimed; configure Fastly service pointing to dangling CNAME.'},
 {'service': 'Squarespace Circle',
  'cname_patterns': ['[a-z0-9-]+\\.squarespace\\.com$'],
  'fingerprint_body': 'squarespace|404|This website is coming soon|Page Not Found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Squarespace site CNAME dangling after account cancellation; register Squarespace site with '
                   'matching name.'},
 {'service': 'Ghost Pro (custom)',
  'cname_patterns': ['[a-z0-9-]+\\.ghost\\.io$'],
  'fingerprint_body': '404|Ghost|Domain is not configured|This site is no longer available',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Ghost Pro subscription cancelled; register Ghost Pro plan with matching subdomain.'},
 {'service': 'ReadMe.io',
  'cname_patterns': ['\\.readme\\.io$', '\\.readme\\.com$'],
  'fingerprint_body': 'Project not found|readme|404|This project no longer exists',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'ReadMe documentation project removed; register a ReadMe project with matching custom subdomain.'},
 {'service': 'Gitea (hosted)',
  'cname_patterns': ['\\.gitea\\.io$'],
  'fingerprint_body': '404|gitea|Repository not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Hosted Gitea pages site removed; register Gitea account with matching name to serve content.'},
 {'service': 'AWS WorkMail',
  'cname_patterns': ['webmail\\.[a-z0-9.-]+\\.awsapps\\.com$', '[a-z0-9-]+\\.awsapps\\.com$'],
  'fingerprint_body': '404|Organization not found|WorkMail',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'AWS WorkMail organization subdomain removed; register WorkMail org with matching alias.'},
 {'service': 'Digital Ocean Managed DB',
  'cname_patterns': ['[a-z0-9-]+\\.[a-z0-9]+\\.db\\.ondigitalocean\\.com$'],
  'fingerprint_body': '404|Not found|Database not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'DigitalOcean managed database removed; register a new cluster with matching name.'},
 {'service': 'Akamai',
  'cname_patterns': ['\\.akamaiedge\\.net$', '\\.akamaitech\\.net$'],
  'fingerprint_body': 'Server Error|Reference.*akamai|404|The server encountered',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Akamai edge configuration removed; configure a new Akamai property with the dangling CNAME.'},
 {'service': 'MaxCDN / StackPath',
  'cname_patterns': ['\\.stackpathcdn\\.com$', '\\.maxcdn\\.com$'],
  'fingerprint_body': 'Pull Zone Not Found|404|stackpath|maxcdn',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'MaxCDN/StackPath pull zone deleted; create a new pull zone with matching hostname.'},
 {'service': 'KeyCDN',
  'cname_patterns': ['\\.kxcdn\\.com$'],
  'fingerprint_body': 'Zone Not Found|kxcdn|404|This zone does not exist',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'KeyCDN zone deleted; register a new zone with matching CNAME hostname.'},
 {'service': 'Hetzner',
  'cname_patterns': ['\\.hetzner\\.cloud$', '\\.your-server\\.de$'],
  'fingerprint_body': '404|Hetzner|No server found|Server not configured',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Hetzner Cloud server or load balancer removed; register a server with same domain configuration.'},
 {'service': 'Vultr Object Storage',
  'cname_patterns': ['\\.vultrobjects\\.com$'],
  'fingerprint_body': 'NoSuchBucket|The specified bucket does not exist|404',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Vultr Object Storage bucket removed; create a bucket with matching name to serve arbitrary '
                   'content.'},
 {'service': 'Cloudinary',
  'cname_patterns': ['\\.cloudinary\\.com$', 'res\\.cloudinary\\.com$'],
  'fingerprint_body': 'Resource not found|cloudinary|404|The resource.*does not exist',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Cloudinary cloud name or resource removed; register Cloudinary account with matching cloud name.'},
 {'service': 'Imgix',
  'cname_patterns': ['\\.imgix\\.net$'],
  'fingerprint_body': 'Source not found|imgix|404|No source configured',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Imgix source domain removed; register an Imgix source with matching subdomain.'},
 {'service': 'Stream',
  'cname_patterns': ['\\.getstream\\.io$'],
  'fingerprint_body': 'App not found|getstream|404|This application does not exist',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Stream app removed; register a Stream app with matching subdomain.'},
 {'service': 'Agile CRM',
  'cname_patterns': ['\\.agilecrm\\.com$'],
  'fingerprint_body': 'Account not found|agilecrm|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Agile CRM account deleted; register an account with matching subdomain.'},
 {'service': 'Zoho Sites',
  'cname_patterns': ['\\.zohowebstatic\\.com$', '\\.zohosites\\.com$'],
  'fingerprint_body': '404|zoho|Site not found|This site is not available',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Zoho Sites page removed; create a Zoho Sites account with matching subdomain.'},
 {'service': 'Salesforce Heroku Connect',
  'cname_patterns': ['heroku-appname\\.salesforce\\.com$'],
  'fingerprint_body': '404|Salesforce|Application not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Salesforce/Heroku Connect endpoint removed; register the app with matching Salesforce subdomain.'},
 {'service': 'Campaign Monitor',
  'cname_patterns': ['\\.createsend\\.com$'],
  'fingerprint_body': 'This account does not exist|createsend|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Campaign Monitor account removed; register an account with matching subdomain.'},
 {'service': 'ActiveCampaign',
  'cname_patterns': ['\\.activehosted\\.com$'],
  'fingerprint_body': '404|activehosted|This account does not exist',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'ActiveCampaign hosted page removed; register ActiveCampaign account with matching subdomain.'},
 {'service': 'Instapage',
  'cname_patterns': ['\\.instapage\\.com$', 'instapage\\.net$'],
  'fingerprint_body': 'Page not found|instapage|404|This landing page no longer exists',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Instapage landing page removed; register an Instapage workspace and publish to matching domain.'},
 {'service': 'Clickfunnels',
  'cname_patterns': ['\\.clickfunnels\\.com$', 'myclickfunnels\\.com$'],
  'fingerprint_body': '404|ClickFunnels|This page is not available|The funnel you requested',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Clickfunnels funnel page removed; register a Clickfunnels account with matching subdomain.'},
 {'service': 'Statio (Pagerduty)',
  'cname_patterns': ['\\.pagerduty\\.com$'],
  'fingerprint_body': '404|PagerDuty|Status page not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'PagerDuty status page removed; register a PagerDuty account with matching subdomain.'},
 {'service': 'OpsGenie',
  'cname_patterns': ['\\.opsgenie\\.com$'],
  'fingerprint_body': '404|OpsGenie|Account not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'OpsGenie account or status page removed; register account with matching subdomain.'},
 {'service': 'AWS Pinpoint',
  'cname_patterns': ['[a-z0-9-]+\\.pinpoint\\.amazonaws\\.com$'],
  'fingerprint_body': '404|Pinpoint|Application not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'AWS Pinpoint endpoint removed; register a Pinpoint application with matching domain.'},
 {'service': 'Fly.io (internal)',
  'cname_patterns': ['[a-z0-9-]+\\.internal\\.fly\\.io$'],
  'fingerprint_body': '404|fly\\.io|Not found',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Fly.io internal address dangling; deploy a Fly app to claim the internal address.'},
 {'service': 'Render (worker)',
  'cname_patterns': ['[a-z0-9-]+-worker\\.onrender\\.com$'],
  'fingerprint_body': 'Service not found|404|onrender',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Render background worker service removed; register service with matching name on Render.'},
 {'service': 'Cloudflare R2',
  'cname_patterns': ['\\.r2\\.dev$', '[a-z0-9]+\\.r2\\.dev$'],
  'fingerprint_body': 'NoSuchBucket|404|Bucket not found|R2',
  'fingerprint_status': 404,
  'severity': 'CRITICAL',
  'documentation': 'Cloudflare R2 bucket removed; create a new R2 bucket with matching public subdomain.'},
 {'service': 'WPEngine (headless)',
  'cname_patterns': ['[a-z0-9-]+\\.wpengine\\.com$'],
  'fingerprint_body': 'Install not found|wpengine|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'WPEngine headless WordPress install deleted; register a WPEngine install with matching name.'},
 {'service': 'Contentful',
  'cname_patterns': ['\\.contentful\\.com$', 'cdn\\.contentful\\.com$'],
  'fingerprint_body': 'Space not found|contentful|404|This space no longer exists',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Contentful space or delivery domain removed; register a Contentful space with matching custom '
                   'domain.'},
 {'service': 'Prismic',
  'cname_patterns': ['\\.prismic\\.io$', '[a-z0-9-]+\\.prismic\\.io$'],
  'fingerprint_body': 'Repository not found|prismic|404',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Prismic repository deleted; register a Prismic repository with matching name.'},
 {'service': 'Sanity',
  'cname_patterns': ['\\.sanity\\.io$'],
  'fingerprint_body': 'Project not found|sanity|404|This Studio is not configured',
  'fingerprint_status': 404,
  'severity': 'HIGH',
  'documentation': 'Sanity Studio project removed; register a Sanity project with matching subdomain.'}]
