"""tech_cve_map — generated dev-time by Claude. Recon module asset.
"""

TECH_CVE_MAP = [{'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2002-0392',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.0.x chunked encoding vulnerability allows remote attackers to execute arbitrary code via a '
                 'crafted HTTP request.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2004-0113',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.0.x mod_ssl null pointer dereference allows denial of service via malformed client '
                 'certificate.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2004-0747',
  'severity': 'HIGH',
  'cvss': '7.2',
  'description': 'Apache 2.0.x buffer overflow in mod_rewrite allows local users to execute arbitrary code via a long '
                 'regex.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2006-3747',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Off-by-one error in mod_rewrite in Apache 2.0.x allows remote attackers to execute arbitrary code '
                 'via a crafted URL.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2007-3304',
  'severity': 'MEDIUM',
  'cvss': '4.7',
  'description': 'Apache httpd 2.0.x allows local users to send signals to arbitrary processes via a crafted PID '
                 'file.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2007-6388',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'Cross-site scripting vulnerability in mod_status in Apache 2.0.x allows remote attackers to inject '
                 'arbitrary web script.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2009-1191',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'mod_proxy in Apache 2.0.x does not properly handle requests for URIs containing HTTP methods, '
                 'leading to information disclosure.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2009-1890',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'mod_proxy in Apache 2.0.x allows remote attackers to cause a denial of service via a request '
                 'containing a Content-Length header but no body.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2010-0408',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'mod_proxy_ajp in Apache 2.0.x allows remote attackers to cause denial of service via a malformed '
                 'HTTP request.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2011-3192',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'Apache 2.0.x ByteRange filter denial of service via crafted Range header causing memory exhaustion '
                 '(Apache Killer).'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2011-3192',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'Apache 2.2.x ByteRange filter denial of service via crafted Range header causing memory exhaustion '
                 '(Apache Killer).'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2012-0031',
  'severity': 'HIGH',
  'cvss': '7.2',
  'description': 'Apache 2.2.x scoreboard handling allows local users to cause a denial of service via a signal during '
                 'child process shutdown.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2012-0053',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'Apache 2.2.x error responses expose httpOnly cookies via a crafted request with a long HTTP header '
                 'allowing XSS.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2012-2687',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'Cross-site scripting vulnerability in mod_negotiation in Apache 2.2.x allows remote attackers to '
                 'inject arbitrary web script.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2013-1862',
  'severity': 'MEDIUM',
  'cvss': '5.1',
  'description': 'mod_rewrite in Apache 2.2.x does not sanitize HTTP request logs, allowing injection of terminal '
                 'escape sequences.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2013-2249',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'mod_session_dbd in Apache 2.2.x does not properly handle changes to session expiry times, allowing '
                 'session hijacking.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2014-0098',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'Apache 2.2.x mod_log_config denial of service via crafted cookies with log format specifiers.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2014-0117',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'mod_proxy in Apache 2.2.x allows remote attackers to cause denial of service via a crafted HTTP '
                 'Connection header.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2014-0118',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'mod_deflate in Apache 2.2.x allows remote attackers to cause denial of service via a request with a '
                 'body that requires decompression.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2014-0226',
  'severity': 'MEDIUM',
  'cvss': '6.8',
  'description': 'Race condition in mod_status in Apache 2.2.x allows remote attackers to cause denial of service or '
                 'execute arbitrary code.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2014-3523',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'WinNT MPM in Apache 2.2.x on Windows allows remote attackers to cause denial of service via a '
                 'crafted HTTP request.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2014-3569',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'OpenSSL used by Apache 2.2.x no_ssl3 option allows fallback to SSL 3.0 (POODLE) enabling protocol '
                 'downgrade attacks.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2015-3183',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'Apache 2.2.x HTTP request smuggling vulnerability via malformed chunked Transfer-Encoding headers.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2016-0736',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'mod_session_crypto in Apache 2.2.x does not properly pad data allowing padding oracle attacks.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2016-2161',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'mod_auth_digest in Apache 2.2.x allows remote attackers to cause denial of service via malformed '
                 'input.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2016-8743',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.2.x HTTP request parsing inconsistency allows HTTP request smuggling and cache poisoning.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2017-7679',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'mod_mime in Apache 2.2.x allows remote attackers to perform buffer overread attack via Content-Type '
                 'response header.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2017-9798',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Optionsbleed: Apache 2.2.x OPTIONS method response leaks arbitrary memory due to use-after-free bug '
                 'in .htaccess Limit directive.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2013-1896',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'Apache 2.4.x mod_dav denial of service via MERGE request with multiple DAV:response elements.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2014-0231',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'mod_cgid in Apache 2.4.x allows remote attackers to cause denial of service via a slow upload '
                 'request.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2014-8109',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'mod_lua in Apache 2.4.x LuaAuthzProvider allows remote attackers to bypass authorization '
                 'restrictions.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2015-0228',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'mod_lua in Apache 2.4.x allows remote attackers to cause denial of service via a crafted '
                 'RESPONSE_CHAIN request.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2015-3185',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'ap_some_auth_required function in Apache 2.4.x does not properly indicate authz requirements, '
                 'allowing authentication bypass.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2016-4979',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x with HTTP/2 enabled allows remote attackers to bypass authentication via X.509 client '
                 'certificate.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2016-8612',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'Apache 2.4.x mod_cluster allows remote attackers to cause a protocol parsing denial of service.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2017-7668',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x ap_find_token function buffer overread allows remote attackers to cause denial of '
                 'service.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2017-9788',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'mod_auth_digest in Apache 2.4.x allows memory problems due to uninitialized shared memory when '
                 'server is configured for Digest authentication.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2018-1283',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'mod_session in Apache 2.4.x improperly handles session data from CGI applications, allowing session '
                 'data manipulation.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2018-1301',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x out-of-bounds access after crafted requests cause a denial of service via memory '
                 'corruption.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2018-11763',
  'severity': 'MEDIUM',
  'cvss': '5.9',
  'description': 'Apache 2.4.x HTTP/2 DoS via continuations frame flood leading to memory exhaustion.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2018-17189',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Apache 2.4.x mod_http2 allows denial of service by sending short bodies on requests with slow '
                 'request body arrival.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2019-0190',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x with mod_ssl compiled against OpenSSL 1.1.1+ allows denial of service via TLSv1.3 '
                 'session ticket key negotiation.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2019-0197',
  'severity': 'MEDIUM',
  'cvss': '4.2',
  'description': 'Apache 2.4.x mod_http2 allows request inconsistencies when upgrade from HTTP/1.1 to HTTP/2 is not '
                 'properly rejected.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2019-10082',
  'severity': 'HIGH',
  'cvss': '9.1',
  'description': 'Apache 2.4.x mod_http2 session pool use-after-free during push promise evaluation allowing memory '
                 'corruption.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2019-10092',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'Apache 2.4.x limited cross-site scripting vulnerability via a specially crafted URI in proxy error '
                 'page.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2019-10097',
  'severity': 'HIGH',
  'cvss': '7.2',
  'description': 'Apache 2.4.x mod_remoteip null pointer dereference and stack overflow vulnerability via trusted '
                 'intermediaries.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2019-10098',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'Apache 2.4.x mod_rewrite potential open redirect via RewriteRule with unescaped substitution in '
                 'server context.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2020-1927',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'Apache 2.4.x mod_rewrite open redirect via specially crafted URLs with path confusion attack.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2020-1934',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Apache 2.4.x mod_proxy_ftp use of uninitialized value when proxying FTP connections to a backend '
                 'server.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2020-9490',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_http2 push diary vulnerability causes null pointer dereference via crafted request '
                 'header.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2020-11985',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Apache 2.4.x mod_remoteip allows IP spoofing when trusted proxies use a non-default configuration.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2020-35452',
  'severity': 'HIGH',
  'cvss': '7.3',
  'description': 'Apache 2.4.x mod_auth_digest single zero byte stack overflow via crafted Digest authentication '
                 'request.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2021-26690',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_session null pointer dereference via malformed SessionHeader value causing denial '
                 'of service.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2021-26691',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x mod_session heap overflow via malformed session data leading to memory corruption.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2021-30641',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Apache 2.4.x MergeSlashes feature causes unexpected URL handling due to regression in configuration '
                 'merging.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2021-31618',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x NULL pointer dereference crash when a crafted HTTP/2 request causes null pointer in '
                 'handling of incomplete requests.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2021-34798',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x NULL pointer dereference via malformed requests allowing denial of service.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2021-36160',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_proxy_uwsgi out-of-bound read via specially crafted request uri-path causing denial '
                 'of service.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[1-3][0-9]|40)$',
  'cve': 'CVE-2021-40438',
  'severity': 'CRITICAL',
  'cvss': '9.0',
  'description': 'Apache 2.4.x Server Side Request Forgery (SSRF) via crafted request to mod_proxy allows attacker to '
                 'redirect requests to origin server.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2021-41524',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.49-2.4.50 null pointer dereference via HTTP/2 request cancellation causing denial of '
                 'service.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.49$',
  'cve': 'CVE-2021-41773',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.49 path traversal and remote code execution vulnerability allows unauthenticated '
                 'attackers to execute arbitrary code via CGI.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(49|50)$',
  'cve': 'CVE-2021-42013',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.49-2.4.50 path traversal vulnerability fix was incomplete allowing remote code execution '
                 'via double URL encoding.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-22719',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_lua use of uninitialized value in r:parsebody allows denial of service via crafted '
                 'request body.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-22720',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x HTTP request smuggling vulnerability via improper handling of Transfer-Encoding header '
                 'allowing cache poisoning.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-22721',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'Apache 2.4.x possible integer overflow or out-of-bounds write if LimitXMLRequestBody is set to allow '
                 'large XML bodies.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-23943',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x mod_sed out-of-bounds write via specially crafted input to sed module allowing '
                 'arbitrary code execution.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-26377',
  'severity': 'HIGH',
  'cvss': '7.3',
  'description': 'Apache 2.4.x mod_proxy_ajp request smuggling via inconsistent interpretation of HTTP headers in AJP '
                 'connection.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-29404',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_lua denial of service via a request to a Lua script calling r:parsebody with large '
                 'upload bodies.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-30522',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_sed denial of service via large input bodies causing memory exhaustion in sed '
                 'processing.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-30556',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_lua information disclosure via crafted request allowing reading outside intended '
                 'scope via regex.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-31813',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x mod_proxy X-Forwarded-For header omission allows IP-based authentication bypass via '
                 'forwarded headers.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2023-25690',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x mod_proxy HTTP request smuggling via crafted request allows request splitting and cache '
                 'poisoning attacks.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2023-27522',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_proxy_uwsgi HTTP response splitting via crafted HTTP request header manipulation.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2023-31122',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_macro out-of-bounds read vulnerability via a crafted macro definition causing '
                 'denial of service.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2023-45802',
  'severity': 'MEDIUM',
  'cvss': '5.9',
  'description': 'Apache 2.4.x HTTP/2 stream memory not reclaimed after early stream reset causing memory exhaustion '
                 'DoS.'},
 {'tech': 'nginx',
  'version_match': '^0\\.',
  'cve': 'CVE-2009-2629',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'nginx 0.x buffer underflow in ngx_http_parse_complex_uri allows remote attackers to execute '
                 'arbitrary code.'},
 {'tech': 'nginx',
  'version_match': '^0\\.',
  'cve': 'CVE-2010-2263',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'nginx 0.x on Windows allows remote attackers to obtain source code of script files via a trailing '
                 'dot in URI.'},
 {'tech': 'nginx',
  'version_match': '^0\\.',
  'cve': 'CVE-2011-4315',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'Heap buffer overflow in nginx 0.x resolver via crafted DNS response allowing remote attackers to '
                 'cause denial of service.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2012-2089',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'nginx 1.0.x before 1.0.15 and 1.1.x buffer overflow in HTTP chunked transfer encoding allows denial '
                 'of service.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-4]\\.',
  'cve': 'CVE-2013-2028',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'nginx 1.3.9-1.4.0 stack buffer overflow via specially crafted HTTP chunked transfer encoding request '
                 'allows arbitrary code execution.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-5]\\.',
  'cve': 'CVE-2013-4547',
  'severity': 'HIGH',
  'cvss': '8.0',
  'description': 'nginx 0.8.41-1.5.6 remote exploitation via crafted URI with unescaped space followed by location '
                 'directive bypass.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-6]\\.',
  'cve': 'CVE-2014-0088',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'nginx 1.4.x SPDY implementation allows remote attackers to cause denial of service via a zero window '
                 'size.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2014-3616',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'nginx 1.x SSL session resumption vulnerability allows virtual host confusion attack enabling session '
                 'hijacking.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2016-0742',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x resolver null pointer dereference via crafted DNS response allows denial of service.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2016-0746',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'nginx 1.x use-after-free vulnerability in resolver module allows remote attackers to execute '
                 'arbitrary code.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2016-0747',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'nginx 1.x resolver insufficient limitation of CNAME resolution allows denial of service via crafted '
                 'DNS responses.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-1][0-9]\\.',
  'cve': 'CVE-2017-7529',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'nginx 0.5.6-1.13.2 range filter integer overflow allows information disclosure via crafted HTTP '
                 'range requests.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-1][0-9]\\.',
  'cve': 'CVE-2018-16843',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.9.5-1.15.5 HTTP/2 implementation excessive memory consumption allows denial of service via '
                 'crafted requests.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-1][0-9]\\.',
  'cve': 'CVE-2018-16844',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.9.5-1.15.5 HTTP/2 CPU resource exhaustion allows denial of service via specially crafted '
                 'HTTP/2 requests.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-1][0-9]\\.',
  'cve': 'CVE-2018-16845',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'nginx 1.1.3-1.15.5 ngx_http_mp4_module denial of service and memory disclosure via specially crafted '
                 'MP4 file.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-1][0-9]\\.',
  'cve': 'CVE-2019-9511',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'HTTP/2 Data Dribble attack in nginx allows remote attackers to cause denial of service via crafted '
                 'HTTP/2 stream.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-1][0-9]\\.',
  'cve': 'CVE-2019-9513',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'HTTP/2 Resource Loop attack in nginx allows remote attackers to cause CPU exhaustion via crafted '
                 'priority frames.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-1][0-9]\\.',
  'cve': 'CVE-2019-9516',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 0-byte header leak in HTTP/2 allows remote attackers to cause denial of service via crafted '
                 'zero-length headers.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-1][0-9]\\.',
  'cve': 'CVE-2021-23017',
  'severity': 'CRITICAL',
  'cvss': '9.4',
  'description': 'nginx 0.6.18-1.20.0 resolver off-by-one heap buffer overflow via crafted DNS response allows code '
                 'execution.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2013-0337',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x default Ubuntu configuration creates world-writable log files allowing local privilege '
                 'escalation.'},
 {'tech': 'nginx',
  'version_match': '^1\\.1[0-9]\\.',
  'cve': 'CVE-2019-20372',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'nginx 1.17.7 and earlier HTTP/2 allows request smuggling via improper handling of HTTP/1.x header in '
                 'intercepting proxy.'},
 {'tech': 'nginx',
  'version_match': '^1\\.1[0-9]\\.',
  'cve': 'CVE-2022-41741',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'nginx ngx_http_mp4_module memory corruption vulnerability via specially crafted MP4 file allowing '
                 'privilege escalation.'},
 {'tech': 'nginx',
  'version_match': '^1\\.1[0-9]\\.',
  'cve': 'CVE-2022-41742',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'nginx ngx_http_mp4_module out-of-bounds memory read via specially crafted MP4 file allowing '
                 'information disclosure.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-1][0-9]\\.',
  'cve': 'CVE-2014-0133',
  'severity': 'MEDIUM',
  'cvss': '6.8',
  'description': 'nginx 1.4.x and 1.5.x heap memory corruption in SPDY implementation allows remote code execution.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2012-4929',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'CRIME attack affects nginx when SSL/TLS compression is enabled allowing recovery of session tokens '
                 'via chosen-plaintext attack.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2020-11724',
  'severity': 'HIGH',
  'cvss': '8.6',
  'description': 'nginx 1.x HTTP request smuggling in OpenResty-based deployments via NGINX HTTP/1.1 proxy '
                 'configuration.'},
 {'tech': 'nginx',
  'version_match': '^1\\.1[0-9]\\.',
  'cve': 'CVE-2021-3618',
  'severity': 'HIGH',
  'cvss': '7.4',
  'description': 'ALPACA attack affects nginx allowing cross-protocol request smuggling via TLS with wildcard '
                 'certificates.'},
 {'tech': 'nginx',
  'version_match': '^1\\.1[0-9]\\.',
  'cve': 'CVE-2022-3638',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'nginx ModSecurity integration use-after-free vulnerability allows remote attackers to execute '
                 'arbitrary code.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2011-4968',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'nginx 1.x session resumption does not enforce SNI host verification allowing server impersonation '
                 'attacks.'},
 {'tech': 'nginx',
  'version_match': '^1\\.1[0-9]\\.',
  'cve': 'CVE-2023-44487',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'HTTP/2 Rapid Reset Attack (CVE-2023-44487) affects nginx allowing remote denial of service via '
                 'crafted HTTP/2 streams.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2010-4478',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'OpenSSH 5.x J-PAKE protocol does not properly validate public parameters allowing authentication '
                 'bypass.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2010-4755',
  'severity': 'MEDIUM',
  'cvss': '4.0',
  'description': 'OpenSSH 5.x sftp-server permits read access to sensitive files beyond intended restrictions.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2011-4327',
  'severity': 'MEDIUM',
  'cvss': '4.6',
  'description': 'ssh-keysign in OpenSSH 5.x does not properly check file descriptor before exiting, allowing local '
                 'privilege escalation.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2012-0814',
  'severity': 'MEDIUM',
  'cvss': '3.5',
  'description': 'OpenSSH 5.x auth_parse_options function allows memory corruption via crafted authorized_keys file '
                 'options field.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2014-1692',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'OpenSSH 5.x with HPN-SSH patch allows memory corruption via crafted kexinit message enabling code '
                 'execution.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2014-2532',
  'severity': 'MEDIUM',
  'cvss': '5.8',
  'description': 'OpenSSH 5.x AcceptEnv wildcard match processing allows restriction bypass for environment variable '
                 'acceptance.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2014-2653',
  'severity': 'MEDIUM',
  'cvss': '5.8',
  'description': 'OpenSSH 5.x verify_host_key function does not check SSHFP DNS records for failed hostname '
                 'verification.'},
 {'tech': 'OpenSSH',
  'version_match': '^[56]\\.',
  'cve': 'CVE-2015-5600',
  'severity': 'HIGH',
  'cvss': '8.5',
  'description': 'OpenSSH 5.x-6.x keyboard-interactive authentication allows brute force attacks by resetting the '
                 'maximum try count.'},
 {'tech': 'OpenSSH',
  'version_match': '^[56]\\.',
  'cve': 'CVE-2015-6563',
  'severity': 'MEDIUM',
  'cvss': '1.9',
  'description': 'OpenSSH 5.x-6.x privilege separation monitor does not validate username during PAM authentication '
                 'allowing privilege escalation.'},
 {'tech': 'OpenSSH',
  'version_match': '^[56]\\.',
  'cve': 'CVE-2015-6564',
  'severity': 'MEDIUM',
  'cvss': '6.9',
  'description': 'OpenSSH 5.x-6.x use-after-free vulnerability in PAM authentication allowing privilege escalation.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2012-3478',
  'severity': 'MEDIUM',
  'cvss': '4.6',
  'description': 'OpenSSH 6.x do_setup_env function in session.c allows local users to bypass intended environment '
                 'restrictions.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2013-4548',
  'severity': 'HIGH',
  'cvss': '6.0',
  'description': 'OpenSSH 6.2 and 6.3 mux_open_fwd function use-after-free allows remote authenticated attackers to '
                 'gain privileges.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2016-0777',
  'severity': 'MEDIUM',
  'cvss': '4.0',
  'description': 'OpenSSH 5.4-6.9 roaming feature information disclosure allows remote servers to read client memory '
                 'via roaming connection.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2016-0778',
  'severity': 'HIGH',
  'cvss': '8.1',
  'description': 'OpenSSH 5.x-6.6 roaming feature buffer overflow in client allows remote SSH servers to execute '
                 'arbitrary code.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-7]\\.',
  'cve': 'CVE-2016-1907',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'OpenSSH 6.x out-of-bounds read in packet.c allows remote attackers to cause denial of service via '
                 'crafted SSH packet.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2016-3115',
  'severity': 'MEDIUM',
  'cvss': '5.5',
  'description': 'OpenSSH 7.x x11_open_helper channel sanity check bypass allows remote authenticated users to inject '
                 'commands.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2016-6210',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'OpenSSH 7.x sshd user enumeration vulnerability via timing side-channel during authentication of '
                 'invalid users.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2016-6515',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'OpenSSH 7.x password authentication function does not limit password length enabling CPU consumption '
                 'denial of service.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2017-15906',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'OpenSSH 7.x process_open function in sftp-server allows creation of zero-length files despite write '
                 'restrictions.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-7]\\.',
  'cve': 'CVE-2018-15473',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'OpenSSH 7.7 and earlier username enumeration vulnerability via timing difference in authentication '
                 'failure responses.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-7]\\.',
  'cve': 'CVE-2018-15919',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'OpenSSH 7.x username enumeration via auth2-gss.c allows remote attackers to determine valid '
                 'usernames.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2018-20685',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'OpenSSH 7.x scp client allows a malicious server to modify directory permissions during file copy '
                 'operations.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2019-6109',
  'severity': 'MEDIUM',
  'cvss': '6.8',
  'description': 'OpenSSH 7.x scp client object manipulation via ANSI codes in filenames allows remote SSH server to '
                 'overwrite files.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2019-6110',
  'severity': 'MEDIUM',
  'cvss': '6.8',
  'description': 'OpenSSH 7.x scp client output manipulation allows remote SSH server to suppress transfer progress '
                 'reporting.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2019-6111',
  'severity': 'MEDIUM',
  'cvss': '5.9',
  'description': 'OpenSSH 7.x scp client missing validation allows malicious server to overwrite arbitrary files in '
                 'target directory.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-7]\\.',
  'cve': 'CVE-2019-16905',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'OpenSSH 7.7 and earlier xauth injection and integer overflow in private key parsing allows local '
                 'code execution.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-8]\\.',
  'cve': 'CVE-2020-14145',
  'severity': 'MEDIUM',
  'cvss': '5.9',
  'description': 'OpenSSH 5.7-8.4 observable discrepancy in client algorithm negotiation allows man-in-the-middle '
                 'downgrade attack.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-8]\\.',
  'cve': 'CVE-2020-15778',
  'severity': 'MEDIUM',
  'cvss': '7.8',
  'description': 'OpenSSH 8.3p1 and earlier scp function shell command injection via backtick characters in '
                 'destination filenames.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-8]\\.',
  'cve': 'CVE-2021-28041',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'OpenSSH 8.2-8.4 ssh-agent double free vulnerability in PKCS#11 provider module loading leading to '
                 'code execution.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-9]\\.',
  'cve': 'CVE-2021-41617',
  'severity': 'HIGH',
  'cvss': '7.0',
  'description': 'OpenSSH 6.2-8.7 privilege escalation via sshd supplemental group inheritance when '
                 'AuthorizedKeysCommand is configured.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-9]\\.',
  'cve': 'CVE-2023-38408',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'OpenSSH ssh-agent remote code execution via PKCS#11 provider loading allows remote code execution '
                 'when agent forwarding is enabled.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-9]\\.',
  'cve': 'CVE-2023-51385',
  'severity': 'MEDIUM',
  'cvss': '6.5',
  'description': 'OpenSSH ProxyCommand and ProxyJump OS command injection via shell metacharacters in host names in '
                 'SSH config.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-9]\\.',
  'cve': 'CVE-2024-6387',
  'severity': 'CRITICAL',
  'cvss': '8.1',
  'description': 'regreSSHion: OpenSSH race condition in SIGALRM handler allows unauthenticated remote code execution '
                 'as root via glibc.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-8]\\.',
  'cve': 'CVE-2006-5794',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'OpenSSH 5.x nss_ldap or pam_ldap usage allows authentication bypass when checking the validity of '
                 'user certificates.'},
 {'tech': 'OpenSSH',
  'version_match': '^[5-7]\\.',
  'cve': 'CVE-2010-3253',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'OpenSSH 5.x sftp chroot directory traversal allows authenticated users to access files outside '
                 'chroot jail.'},
 {'tech': 'PHP',
  'version_match': '^5\\.4\\.',
  'cve': 'CVE-2014-3981',
  'severity': 'MEDIUM',
  'cvss': '5.8',
  'description': 'PHP 5.4.x fileinfo module out-of-bounds read via specially crafted Composite Document File V2 (CDF) '
                 'file.'},
 {'tech': 'PHP',
  'version_match': '^5\\.4\\.',
  'cve': 'CVE-2014-4721',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'PHP 5.4.x type confusion vulnerability in phpinfo function allows remote attackers to disclose '
                 'memory contents.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[45]\\.',
  'cve': 'CVE-2014-8142',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4.x-5.5.x use-after-free in process_nested_data function allows remote code execution via '
                 'unserialize.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2015-0231',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4-5.6 use-after-free in unserialize with SPLDoublyLinkedList allows remote attackers to '
                 'execute arbitrary code.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2015-0232',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4-5.6 uninitialized pointer in exif_process_IFD_in_MAKERNOTE allows remote code execution via '
                 'crafted JPEG file.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2015-2325',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'PHP 5.4-5.6 PCRE library heap buffer overflow via crafted regular expression allowing denial of '
                 'service or code execution.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2015-4025',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4-5.6 phar_parse_zipfile insufficient validation allows remote code execution via specially '
                 'crafted ZIP archive.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2015-4026',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 5.4-5.6 pcntl_exec implementation does not validate path before passing to operating system.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2015-4644',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 5.4-5.6 NULL pointer dereference in spl_array.c allows remote attackers to cause denial of '
                 'service.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2015-6831',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4-5.6 use-after-free in SPL unserialize allows remote attackers to execute arbitrary code.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2015-7803',
  'severity': 'MEDIUM',
  'cvss': '6.8',
  'description': 'PHP 5.4-5.6 phar_get_entry_data function NULL pointer dereference via malformed .phar file.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2016-4073',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4-5.6 mb_ereg_replace and mb_eregi_replace negative length parameter allows arbitrary code '
                 'execution.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2016-4540',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4-5.6 grapheme_stripos out-of-bounds read via malformed UTF-8 string allows heap buffer '
                 'overflow.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2016-5093',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4-5.6 get_icu_value_internal function out-of-bounds read allows remote attackers to execute '
                 'arbitrary code.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2016-7124',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4-5.6 unserialize __wakeup bypass via object array count mismatch allowing type juggling '
                 'attacks.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2016-7411',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 7.0 unserialize type confusion vulnerability allows remote attackers to cause denial of service '
                 'or execute code.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2017-7272',
  'severity': 'MEDIUM',
  'cvss': '5.8',
  'description': 'PHP 7.x open_basedir bypass via stream_resolve_include_path function allowing access to files '
                 'outside restriction.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2017-11628',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'PHP 7.x stack buffer overflow in initializeString function via crafted INI file processing.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2018-7584',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 7.0-7.2 stack buffer overflow in HTTP BASIC authentication parsing allows remote code '
                 'execution.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2018-10548',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 7.x ext/ldap null pointer dereference via crafted LDAP response allows denial of service.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2018-17082',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'PHP 7.x Apache2 handler cross-site scripting via crafted URL in HTTP 404 error page.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2019-9641',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 7.x exif_read_data uninitialized read via malformed JPEG file allowing remote code execution.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2019-11041',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'PHP 7.x exif_scan_thumbnail heap buffer over-read via malformed JPEG file causing information '
                 'disclosure.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2019-11042',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'PHP 7.x exif_process_IFD_TAG heap buffer over-read via specially crafted EXIF data in images.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2020-7059',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'PHP 7.x fgets function out-of-bounds read via file stream with invalid length allowing information '
                 'disclosure.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2020-7060',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'PHP 7.x mb_strtolower buffer overflow via crafted string in Turkish locale enabling code execution.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2020-7062',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 7.x null pointer dereference in PHP session handling with session.save_path causing denial of '
                 'service.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2020-7063',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'PHP 7.x phar PHAR_FLAGS_IS_TARFILE flag missing in phar_parse_zipfile allowing bypass of file type '
                 'restriction.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2020-7064',
  'severity': 'MEDIUM',
  'cvss': '5.4',
  'description': 'PHP 7.x exif_read_data out-of-bounds read in exif processing via malformed EXIF data causing '
                 'information leak.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2021-21702',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 7.x null pointer dereference in SoapClient allowing remote denial of service via WSDL file.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2021-21703',
  'severity': 'HIGH',
  'cvss': '7.0',
  'description': 'PHP 7.x FPM local privilege escalation via out-of-bounds memory write in master process.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2021-21704',
  'severity': 'MEDIUM',
  'cvss': '5.9',
  'description': 'PHP 7.x Firebird PDO driver buffer over-read in ibm_db2 extension via crafted database response.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2021-21705',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'PHP 7.x SSRF in SoapClient via URL filter bypass allowing access to internal resources.'},
 {'tech': 'WordPress',
  'version_match': '^3\\.',
  'cve': 'CVE-2015-5714',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'WordPress 3.x-4.x cross-site scripting via shortcode tags in post content bypassing kses filtering.'},
 {'tech': 'WordPress',
  'version_match': '^3\\.',
  'cve': 'CVE-2015-5715',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'WordPress 3.x-4.x insufficient access control on sticky posts allows unauthorized stickying or '
                 'unstickying of posts.'},
 {'tech': 'WordPress',
  'version_match': '^[34]\\.',
  'cve': 'CVE-2016-6897',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'WordPress 3.x-4.x cross-site request forgery in image_process function via the '
                 'update-attachment-media action.'},
 {'tech': 'WordPress',
  'version_match': '^[34]\\.',
  'cve': 'CVE-2016-6896',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'WordPress 3.x-4.x cross-site request forgery in theme-delete-nonce allowing unauthorized theme '
                 'deletion.'},
 {'tech': 'WordPress',
  'version_match': '^[34]\\.',
  'cve': 'CVE-2017-14723',
  'severity': 'HIGH',
  'cvss': '8.1',
  'description': 'WordPress 4.x SQL injection in wpdb prepare function via unintended placeholder substitution.'},
 {'tech': 'WordPress',
  'version_match': '^[34]\\.',
  'cve': 'CVE-2017-9066',
  'severity': 'HIGH',
  'cvss': '8.6',
  'description': 'WordPress 4.x insufficient validation of post metadata allows SSRF via WP_HTTP class URL '
                 'redirection.'},
 {'tech': 'WordPress',
  'version_match': '^[34]\\.',
  'cve': 'CVE-2017-14726',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'WordPress 4.x cross-site scripting vulnerability in oEmbed support allowing injection via WordPress '
                 'site URL.'},
 {'tech': 'WordPress',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2018-20153',
  'severity': 'MEDIUM',
  'cvss': '5.4',
  'description': 'WordPress 4.x-5.x cross-site scripting via contributor-level user posting crafted content in comment '
                 'fields.'},
 {'tech': 'WordPress',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2019-8942',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'WordPress 5.0.0 path traversal in image editing via _wp_attached_file metadata enabling remote code '
                 'execution.'},
 {'tech': 'WordPress',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2019-8943',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'WordPress 5.0.0 remote code execution via image metadata crafting combined with directory traversal '
                 'vulnerability.'},
 {'tech': 'WordPress',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2019-17669',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'WordPress 5.x server-side request forgery via validation of PHP function is_url allowing localhost '
                 'requests.'},
 {'tech': 'WordPress',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2020-28032',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'WordPress 5.x object injection via deserialization of untrusted data in core functions allowing code '
                 'execution.'},
 {'tech': 'WordPress',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2020-28040',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'WordPress 5.x cross-site request forgery via heartbeat action allowing CSRF against authenticated '
                 'administrators.'},
 {'tech': 'WordPress',
  'version_match': '^[3456]\\.',
  'cve': 'CVE-2021-29447',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'WordPress 5.6-5.7 XXE injection via media file upload allowing authenticated users to read server '
                 'files.'},
 {'tech': 'WordPress',
  'version_match': '^[3456]\\.',
  'cve': 'CVE-2021-29450',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'WordPress 5.x authenticated user data exposure via REST API allowing subscriber role to access '
                 'private data.'},
 {'tech': 'WordPress',
  'version_match': '^[3456]\\.',
  'cve': 'CVE-2022-21663',
  'severity': 'HIGH',
  'cvss': '7.2',
  'description': 'WordPress multisite super admin privilege escalation via object injection in metadata allowing code '
                 'execution.'},
 {'tech': 'WordPress',
  'version_match': '^[3456]\\.',
  'cve': 'CVE-2022-21664',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'WordPress SQL injection via WP_Meta_Query in nested meta queries allowing privilege escalation.'},
 {'tech': 'WordPress Plugin: WooCommerce',
  'version_match': '^[1-5]\\.',
  'cve': 'CVE-2021-32790',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'WooCommerce WooCommerce Blocks plugin unauthenticated database access via improper input validation '
                 'in REST API.'},
 {'tech': 'WordPress Plugin: Yoast SEO',
  'version_match': '^(1[0-5]|[1-9])\\.',
  'cve': 'CVE-2021-25118',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Yoast SEO plugin information disclosure via IDOR in REST API exposing draft post content to '
                 'unauthenticated users.'},
 {'tech': 'WordPress Plugin: Contact Form 7',
  'version_match': '^[1-5]\\.',
  'cve': 'CVE-2020-35489',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Contact Form 7 unrestricted file upload vulnerability allows remote code execution via specially '
                 'crafted filename.'},
 {'tech': 'WordPress Plugin: Elementor',
  'version_match': '^[123]\\.',
  'cve': 'CVE-2022-1329',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Elementor Plugin for WordPress IDOR allowing subscriber-level authenticated users to execute '
                 'arbitrary code.'},
 {'tech': 'WordPress Plugin: All in One SEO',
  'version_match': '^[1-4]\\.',
  'cve': 'CVE-2021-25036',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'All in One SEO plugin privilege escalation via insufficient authorization checks in REST API '
                 'endpoints.'},
 {'tech': 'WordPress Plugin: Wordfence',
  'version_match': '^[67]\\.',
  'cve': 'CVE-2020-29156',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Wordfence Security plugin information disclosure via forceRoute function allowing access to '
                 'protected post data.'},
 {'tech': 'WordPress Plugin: WP File Manager',
  'version_match': '^[1-6]\\.',
  'cve': 'CVE-2020-25213',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'WP File Manager plugin unauthenticated arbitrary file upload and remote code execution via elFinder '
                 'connector.'},
 {'tech': 'WordPress Plugin: Duplicator',
  'version_match': '^1\\.',
  'cve': 'CVE-2020-11738',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Duplicator plugin directory traversal vulnerability allows unauthenticated users to read arbitrary '
                 'files.'},
 {'tech': 'WordPress Plugin: ThemeGrill Demo Importer',
  'version_match': '^1\\.',
  'cve': 'CVE-2020-8772',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'ThemeGrill Demo Importer plugin unauthenticated arbitrary database wipe and admin account creation.'},
 {'tech': 'WordPress Plugin: Ultimate Member',
  'version_match': '^[12]\\.',
  'cve': 'CVE-2020-36155',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Ultimate Member plugin allows unauthenticated privilege escalation to administrator via registration '
                 'form manipulation.'},
 {'tech': 'WordPress Plugin: Ninja Forms',
  'version_match': '^3\\.',
  'cve': 'CVE-2021-34621',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Ninja Forms plugin privilege escalation via user registration form manipulation allowing subscriber '
                 'to admin escalation.'},
 {'tech': 'WordPress Plugin: OptinMonster',
  'version_match': '^[12]\\.',
  'cve': 'CVE-2021-39341',
  'severity': 'HIGH',
  'cvss': '8.3',
  'description': 'OptinMonster plugin sensitive information disclosure and unauthorized settings modification via '
                 'improper API authentication.'},
 {'tech': 'WordPress Plugin: PHP Everywhere',
  'version_match': '^[123]\\.',
  'cve': 'CVE-2022-24663',
  'severity': 'CRITICAL',
  'cvss': '9.9',
  'description': 'PHP Everywhere plugin remote code execution via subscriber-level authenticated users executing '
                 'arbitrary PHP code.'},
 {'tech': 'WordPress Plugin: WPtouch',
  'version_match': '^[34]\\.',
  'cve': 'CVE-2020-8772',
  'severity': 'HIGH',
  'cvss': '7.2',
  'description': 'WPtouch plugin arbitrary file upload via insufficient mime type validation allowing '
                 'administrator-level code execution.'},
 {'tech': 'WordPress Plugin: Database Backup for WordPress',
  'version_match': '^[123]\\.',
  'cve': 'CVE-2020-11520',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Database Backup plugin CSRF allowing administrators to export full database to attacker-controlled '
                 'URL.'},
 {'tech': 'WordPress Plugin: Popup Builder',
  'version_match': '^[234]\\.',
  'cve': 'CVE-2023-6000',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Popup Builder plugin stored XSS via popup title field allows malicious script injection and admin '
                 'account takeover.'},
 {'tech': 'WordPress Plugin: Advanced Custom Fields',
  'version_match': '^[456]\\.',
  'cve': 'CVE-2023-30777',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'Advanced Custom Fields plugin reflected XSS via the field_name parameter allowing admin session '
                 'hijacking.'},
 {'tech': 'WordPress Plugin: Essential Addons for Elementor',
  'version_match': '^[45]\\.',
  'cve': 'CVE-2023-32243',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Essential Addons for Elementor unauthenticated privilege escalation via arbitrary password reset '
                 'without prior authentication.'},
 {'tech': 'WordPress Core',
  'version_match': '^[3456]\\.',
  'cve': 'CVE-2022-43497',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'WordPress cross-site scripting via crafted queries in admin panel search functionality.'},
 {'tech': 'WordPress Core',
  'version_match': '^[3456]\\.',
  'cve': 'CVE-2023-39999',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'WordPress core multiple information exposure vulnerabilities via unauthorized user access to comment '
                 'subscriptions.'},
 {'tech': 'WordPress Plugin: WPGateway',
  'version_match': '^3\\.',
  'cve': 'CVE-2022-3180',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'WPGateway plugin privilege escalation via unauthenticated administrator account creation in active '
                 'exploitation.'},
 {'tech': 'WordPress Plugin: BackupBuddy',
  'version_match': '^[678]\\.',
  'cve': 'CVE-2022-31474',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'BackupBuddy plugin arbitrary file read via crafted download-url parameter allowing server file '
                 'disclosure.'},
 {'tech': 'Drupal',
  'version_match': '^6\\.',
  'cve': 'CVE-2014-3704',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'Drupalgeddon: Drupal 6.x-7.x SQL injection via array parameter expansion in Drupal core allowing '
                 'unauthenticated RCE.'},
 {'tech': 'Drupal',
  'version_match': '^7\\.',
  'cve': 'CVE-2014-3704',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'Drupalgeddon: Drupal 7.x SQL injection via Form API array parameter allows unauthenticated remote '
                 'code execution.'},
 {'tech': 'Drupal',
  'version_match': '^7\\.',
  'cve': 'CVE-2018-7600',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupalgeddon2: Drupal 7.x-8.x remote code execution via form API #access callback insufficient input '
                 'sanitation.'},
 {'tech': 'Drupal',
  'version_match': '^8\\.',
  'cve': 'CVE-2018-7600',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupalgeddon2: Drupal 8.x remote code execution via Form API request allowing unauthenticated '
                 'arbitrary PHP execution.'},
 {'tech': 'Drupal',
  'version_match': '^[78]\\.',
  'cve': 'CVE-2018-7602',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupalgeddon3: Drupal 7.x-8.x remote code execution via session URL manipulation in DELETE '
                 'requests.'},
 {'tech': 'Drupal',
  'version_match': '^[789]\\.',
  'cve': 'CVE-2019-6340',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupal 8.x RESTful web services remote code execution via unsafe deserialization of typed data when '
                 'REST API is enabled.'},
 {'tech': 'Drupal',
  'version_match': '^[789]\\.',
  'cve': 'CVE-2020-13671',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupal 8.x-9.x file upload module renaming bypass via unrestricted file extension allowing arbitrary '
                 'code execution.'},
 {'tech': 'Drupal',
  'version_match': '^[789]\\.',
  'cve': 'CVE-2020-13664',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupal 8.x arbitrary PHP code execution via drupal_exec function when using dev environments.'},
 {'tech': 'Drupal',
  'version_match': '^[789]\\.',
  'cve': 'CVE-2021-41182',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'Drupal 9.x jQuery UI XSS via tooltip content in Drupal administration UI elements.'},
 {'tech': 'Drupal',
  'version_match': '^[789]\\.',
  'cve': 'CVE-2022-24728',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'Drupal 9.x CKEditor 4 XSS vulnerability via HTML processing in the WYSIWYG editor interface.'},
 {'tech': 'Drupal',
  'version_match': '^[78]\\.',
  'cve': 'CVE-2017-6377',
  'severity': 'HIGH',
  'cvss': '8.1',
  'description': 'Drupal 8.x access bypass vulnerability in file module when file field appears on non-default '
                 'display.'},
 {'tech': 'Drupal',
  'version_match': '^[78]\\.',
  'cve': 'CVE-2017-6381',
  'severity': 'HIGH',
  'cvss': '8.1',
  'description': 'Drupal 8.x development mode CSRF vulnerability allows attackers to execute arbitrary PHP code via '
                 'development settings.'},
 {'tech': 'Drupal',
  'version_match': '^9\\.',
  'cve': 'CVE-2022-25270',
  'severity': 'MEDIUM',
  'cvss': '6.5',
  'description': 'Drupal 9.x Quick Edit module access bypass allows unauthorized editing of arbitrary node content.'},
 {'tech': 'Drupal',
  'version_match': '^[9]\\.[34]|^10\\.',
  'cve': 'CVE-2023-31250',
  'severity': 'MEDIUM',
  'cvss': '6.5',
  'description': 'Drupal 9.5-10 access bypass in file module allows authenticated user to access private files under '
                 'certain conditions.'},
 {'tech': 'Drupal',
  'version_match': '^[789]\\.',
  'cve': 'CVE-2022-39261',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Drupal Twig template engine path traversal via template names allowing access to files outside '
                 'template directory.'},
 {'tech': 'Drupal',
  'version_match': '^[789]\\.',
  'cve': 'CVE-2019-10909',
  'severity': 'MEDIUM',
  'cvss': '5.4',
  'description': 'Drupal 8.x Symfony-based XSS in exception page via improper output escaping of PHP exception '
                 'messages.'},
 {'tech': 'Drupal',
  'version_match': '^[789]\\.',
  'cve': 'CVE-2021-32610',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Drupal 8.x-9.x Archive_Tar path traversal allows arbitrary file overwrite via malformed archive '
                 'files.'},
 {'tech': 'Drupal',
  'version_match': '^[789]\\.',
  'cve': 'CVE-2020-28949',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'Drupal PEAR Archive_Tar path traversal via symlink in compressed tar archives allowing arbitrary '
                 'file read/write.'},
 {'tech': 'Joomla',
  'version_match': '^1\\.5\\.',
  'cve': 'CVE-2015-8562',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'Joomla 1.5.x-3.4.x PHP object injection via HTTP user-agent header in session data leading to remote '
                 'code execution.'},
 {'tech': 'Joomla',
  'version_match': '^1\\.5\\.',
  'cve': 'CVE-2013-1453',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Joomla 1.5.x SQL injection via specially crafted URI in multiple Joomla 1.5 components.'},
 {'tech': 'Joomla',
  'version_match': '^2\\.5\\.',
  'cve': 'CVE-2015-8562',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'Joomla 2.5.x PHP object injection via HTTP header manipulation allows unauthenticated remote code '
                 'execution.'},
 {'tech': 'Joomla',
  'version_match': '^2\\.5\\.',
  'cve': 'CVE-2015-8564',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Joomla 2.5.x SQL injection via email parameter in com_users component password reset functionality.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2016-8869',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.x unauthorized user registration possible via account creation privileges in com_users '
                 'component.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2016-8870',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.4.x register privilege escalation via com_users component account registration with higher '
                 'group assignment.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2017-8917',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.7.x SQL injection via crafted URL in com_fields component without authentication required.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2018-6376',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.x unauthorized user account creation via crafted request to com_users registration '
                 'endpoint.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2019-10945',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.x directory traversal and arbitrary file deletion via media manager component path '
                 'traversal.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2019-18674',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Joomla 3.x CSRF in com_users backend user editing functionality allows unauthorized account '
                 'modifications.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2020-11890',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Joomla 3.x improper validation of URL parameters in com_users component allows unauthorized user '
                 'enumeration.'},
 {'tech': 'Joomla',
  'version_match': '^[34]\\.',
  'cve': 'CVE-2021-23132',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 4.x improper session token validation allows authentication bypass in web service endpoints.'},
 {'tech': 'Joomla',
  'version_match': '^4\\.',
  'cve': 'CVE-2022-23796',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Joomla 4.x inadequate filtering leading to reflected XSS in multiple frontend and backend pages.'},
 {'tech': 'Joomla',
  'version_match': '^4\\.',
  'cve': 'CVE-2023-23752',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Joomla 4.x unauthenticated information disclosure via web service endpoint exposing MySQL connection '
                 'credentials.'},
 {'tech': 'Joomla',
  'version_match': '^[34]\\.',
  'cve': 'CVE-2021-26027',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Joomla 3.x-4.x unauthorized access to com_users list via insufficient access controls.'},
 {'tech': 'Magento',
  'version_match': '^1\\.',
  'cve': 'CVE-2015-1397',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 1.x SQL injection vulnerability in admin panel allows unauthenticated remote code '
                 'execution.'},
 {'tech': 'Magento',
  'version_match': '^1\\.',
  'cve': 'CVE-2016-4010',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 1.x PHP object injection via customer billing address allowing unauthenticated remote code '
                 'execution.'},
 {'tech': 'Magento',
  'version_match': '^1\\.',
  'cve': 'CVE-2019-7139',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 1.x SQL injection via product list filtering functionality allowing unauthenticated database '
                 'extraction.'},
 {'tech': 'Magento',
  'version_match': '^1\\.',
  'cve': 'CVE-2019-7151',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Magento 1.x SSRF vulnerability via crafted URL in product image import functionality.'},
 {'tech': 'Magento',
  'version_match': '^1\\.',
  'cve': 'CVE-2019-7143',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Magento 1.x remote code execution via crafted serialized data in customer data forms.'},
 {'tech': 'Magento',
  'version_match': '^2\\.',
  'cve': 'CVE-2019-8118',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Magento 2.x information disclosure via admin activity log entries accessible to low-privilege '
                 'users.'},
 {'tech': 'Magento',
  'version_match': '^2\\.',
  'cve': 'CVE-2020-24407',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'Magento 2.x path traversal via media file upload allowing remote code execution with admin '
                 'privileges.'},
 {'tech': 'Magento',
  'version_match': '^2\\.',
  'cve': 'CVE-2020-24400',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Magento 2.x SQL injection in product review section allowing authenticated low-privilege user to '
                 'extract data.'},
 {'tech': 'Magento',
  'version_match': '^2\\.',
  'cve': 'CVE-2021-21015',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'Magento 2.x arbitrary code execution via CSRF in admin panel allowing unauthorized actions with '
                 'crafted request.'},
 {'tech': 'Magento',
  'version_match': '^2\\.',
  'cve': 'CVE-2021-21016',
  'severity': 'MEDIUM',
  'cvss': '5.4',
  'description': 'Magento 2.x stored cross-site scripting via malicious widget parameter allowing admin session '
                 'hijacking.'},
 {'tech': 'Magento',
  'version_match': '^2\\.',
  'cve': 'CVE-2022-24086',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 2.x improper input validation in checkout process allows unauthenticated remote code '
                 'execution via template injection.'},
 {'tech': 'Magento',
  'version_match': '^2\\.',
  'cve': 'CVE-2022-24087',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 2.x bypass for CVE-2022-24086 patch via alternate template injection vector in the checkout '
                 'process.'},
 {'tech': 'Magento',
  'version_match': '^2\\.',
  'cve': 'CVE-2022-42344',
  'severity': 'HIGH',
  'cvss': '8.0',
  'description': 'Magento 2.x stored XSS via crafted CMS page block content allowing admin privilege escalation.'},
 {'tech': 'Magento',
  'version_match': '^2\\.',
  'cve': 'CVE-2023-22247',
  'severity': 'HIGH',
  'cvss': '7.2',
  'description': 'Magento 2.x arbitrary file system access via admin store configuration editor allowing server file '
                 'reading.'},
 {'tech': 'Magento',
  'version_match': '^2\\.',
  'cve': 'CVE-2023-29296',
  'severity': 'HIGH',
  'cvss': '8.0',
  'description': 'Magento 2.x arbitrary code execution via crafted GraphQL request in product queries with '
                 'insufficient sanitization.'},
 {'tech': 'Spring Framework',
  'version_match': '^[23456]\\.',
  'cve': 'CVE-2010-1622',
  'severity': 'HIGH',
  'cvss': '8.1',
  'description': 'Spring Framework 2.x-3.x class.classLoader property manipulation via HTTP parameters allowing '
                 'arbitrary code execution.'},
 {'tech': 'Spring Framework',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2014-0097',
  'severity': 'HIGH',
  'cvss': '8.1',
  'description': 'Spring Security 3.x LDAP authentication bypass via empty password with Active Directory servers.'},
 {'tech': 'Spring Framework',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2016-5007',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Spring Security and MVC 3.x-5.x path matching inconsistency allows security filter bypass via '
                 'crafted URLs.'},
 {'tech': 'Spring Framework',
  'version_match': '^[34]\\.',
  'cve': 'CVE-2017-4971',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Spring Web Flow 2.x CSRF vulnerability via parameter manipulation allowing authentication bypass in '
                 'forms.'},
 {'tech': 'Spring Framework',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2018-1258',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Spring Framework 5.x method security bypass when combining Spring Security with @EnableWebMvc '
                 'annotation.'},
 {'tech': 'Spring Framework',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2018-1270',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Spring Framework 5.x remote code execution via STOMP messaging over WebSocket using malicious SpEL '
                 'expressions.'},
 {'tech': 'Spring Framework',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2018-1271',
  'severity': 'MEDIUM',
  'cvss': '5.9',
  'description': 'Spring Framework 5.x path traversal via dot-dot-semicolon sequences allowing access to unprotected '
                 'resources.'},
 {'tech': 'Spring Framework',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2018-1272',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Spring Framework 5.x client-side security bypass via multipart content-type header manipulation in '
                 'HTTP proxy.'},
 {'tech': 'Spring Framework',
  'version_match': '^[345]\\.',
  'cve': 'CVE-2020-5421',
  'severity': 'HIGH',
  'cvss': '8.0',
  'description': 'Spring Framework 5.x RFD attack protection bypass via semicolon suffix in URL allowing reflected '
                 'file download.'},
 {'tech': 'Apache Log4j',
  'version_match': '^2\\.(?:0|1[0-4])\\.',
  'cve': 'CVE-2021-44228',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'Log4Shell: Apache Log4j 2.0-2.14.1 JNDI injection via user-controlled log data allowing '
                 'unauthenticated remote code execution.'},
 {'tech': 'Apache Log4j',
  'version_match': '^2\\.(?:0|1[0-5])\\.',
  'cve': 'CVE-2021-45046',
  'severity': 'CRITICAL',
  'cvss': '9.0',
  'description': 'Apache Log4j 2.0-2.15 incomplete fix for CVE-2021-44228 allows information disclosure and RCE in '
                 'non-default configurations.'},
 {'tech': 'Apache Log4j',
  'version_match': '^2\\.(?:0|1[0-5])\\.',
  'cve': 'CVE-2021-45105',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache Log4j 2.0-2.16 self-referential lookup in ThreadContext map causes infinite recursion and '
                 'denial of service.'}]
