"""tech_cve_map — generated dev-time by Claude. Recon module asset.
"""

TECH_CVE_MAP = [{'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2002-0392',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.0.x chunked encoding vulnerability allows remote code execution via malformed HTTP '
                 'requests.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2004-0113',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.0.x mod_ssl NULL pointer dereference causes denial of service via malformed client '
                 'certificates.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2006-3747',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.0.x mod_rewrite off-by-one buffer overflow allows remote code execution via crafted URLs.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2007-3847',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.0.x mod_proxy DoS via crafted date headers causing infinite loop.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2003-0020',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'Apache 2.0.x error log injection via terminal escape sequences in HTTP requests.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2004-0811',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.0.x mod_ssl access control bypass using non-SSL requests on SSL-only resources.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2005-3352',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'Apache 2.0.x mod_imap cross-site scripting vulnerability via crafted referer headers.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2006-3918',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'Apache 2.0.x Expect header cross-site scripting vulnerability allows script injection.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2007-5000',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'Apache 2.0.x mod_imagemap cross-site scripting via crafted URI in imagemap files.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.0\\.',
  'cve': 'CVE-2008-2364',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'Apache 2.0.x mod_proxy denial of service via excessive interim responses from origin server.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2011-3192',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'Apache 2.2.x Range header DoS (Apache Killer) allows memory exhaustion via overlapping ranges.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2012-0031',
  'severity': 'HIGH',
  'cvss': '7.2',
  'description': 'Apache 2.2.x scoreboard parent process crash via child process exploitation.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2012-0053',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'Apache 2.2.x httpOnly cookie disclosure via HTTP 400 error response in error log.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2013-1862',
  'severity': 'HIGH',
  'cvss': '7.6',
  'description': 'Apache 2.2.x mod_rewrite terminal escape sequence injection via log entries.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2013-2249',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.2.x mod_session_dbd session fixation vulnerability allows session hijacking.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2014-0098',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.2.x mod_log_config crash via crafted cookies causing denial of service.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2014-0226',
  'severity': 'HIGH',
  'cvss': '7.6',
  'description': 'Apache 2.2.x mod_status race condition heap buffer overflow via crafted requests.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2014-0231',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.2.x mod_cgid DoS via slow CGI scripts leaving zombie processes.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2010-0408',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.2.x mod_proxy_ajp denial of service via malformed HTTP request.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2010-0425',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'Apache 2.2.x mod_isapi on Windows unloads ISAPI module allowing arbitrary code execution.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2011-0419',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'Apache 2.2.x apr_fnmatch flaw allows DoS via crafted request with wildcard URI.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2009-1891',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'Apache 2.2.x mod_deflate DoS via request cancellation during compression.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2009-3094',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'Apache 2.2.x mod_proxy_ftp NULL pointer dereference via crafted FTP response.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.2\\.',
  'cve': 'CVE-2010-1452',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.2.x mod_dav DoS via malformed URI causing NULL pointer dereference.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2014-0117',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'Apache 2.4.x mod_proxy crash via crafted HTTP requests causing NULL pointer dereference.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2014-3523',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x WinNT MPM memory leak via pipelined requests causing DoS.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2015-3183',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x chunked transfer encoding request smuggling via multiple Content-Length headers.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2016-0736',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_session_crypto padding oracle vulnerability via CBC ciphertext manipulation.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2016-4975',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'Apache 2.4.x CRLF injection in mod_userdir via HTTP response splitting.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2017-7679',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x mod_mime buffer overread via crafted Content-Type response header.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2017-7668',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x ap_find_token buffer overread via crafted Accept-Encoding header.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2017-9798',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x Optionsbleed use-after-free via OPTIONS method leaking server memory.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2018-1283',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Apache 2.4.x mod_session CGI session data exposure via crafted HTTP headers.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2018-1312',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x mod_auth_digest weak nonce generation allows authentication replay attacks.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2018-11763',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x HTTP/2 DoS via crafted requests causing NULL pointer dereference.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2019-0196',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x HTTP/2 use-after-free via crafted request sequence causing server crash.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2019-0197',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'Apache 2.4.x HTTP/2 upgrade over cleartext protocol crash via early SETTINGS frame.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2019-0220',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Apache 2.4.x URL normalization inconsistency in path component handling allows access control '
                 'bypass.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2019-10082',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'Apache 2.4.x HTTP/2 session use-after-free during push operations allows information disclosure.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2019-10092',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'Apache 2.4.x mod_proxy partial limited cross-site scripting via crafted error page.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2019-10098',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'Apache 2.4.x mod_rewrite open redirect via crafted URL containing newline characters.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2020-1927',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'Apache 2.4.x mod_rewrite open redirect in default configuration via crafted request URI.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2020-1934',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Apache 2.4.x mod_proxy_ftp use of uninitialized value allows information disclosure.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2020-9490',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x HTTP/2 push diary feature memory corruption via crafted PUSH_PROMISE frames.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2020-11993',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x HTTP/2 push with invalid header causes use-after-free and memory corruption.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2020-35452',
  'severity': 'HIGH',
  'cvss': '7.3',
  'description': 'Apache 2.4.x mod_auth_digest single zero byte stack overflow via crafted requests.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2021-26690',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_session NULL pointer dereference via crafted session content.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2021-26691',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x mod_session heap overflow via very long session data string.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2021-30641',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x MergeSlashes configuration regression allows bypassing access controls.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2021-31618',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x HTTP/2 NULL pointer dereference crash via crafted CANCEL request.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2021-33193',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x HTTP/2 request forgery via mixing special characters in request headers.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2021-34798',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x NULL pointer dereference in ap_escape_quotes via malformed request.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.(?:[0-9]|[12][0-9]|3[0-9]|40)$',
  'cve': 'CVE-2021-36160',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_proxy_uwsgi out-of-bounds read via crafted URI string.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2021-41773',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.49 path traversal and RCE via directory traversal with encoded path segments.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2021-42013',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.49/2.4.50 incomplete fix for CVE-2021-41773 allows further path traversal and RCE.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-22720',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x HTTP request smuggling via incorrect error handling in mod_proxy.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-22721',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'Apache 2.4.x mod_sed buffer overflow if LimitRequestBody is set to exceed 4GB.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-28614',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x ap_rwrite out-of-bounds read via ap_strcmp_match integer overflow.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-29404',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_lua DoS via crafted request to Lua handler script.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-30522',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_sed memory exhaustion DoS via very large request bodies.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-31813',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x X-Forwarded-For header omission allows forward proxy IP check bypass.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2022-36760',
  'severity': 'CRITICAL',
  'cvss': '9.0',
  'description': 'Apache 2.4.x mod_proxy_ajp request smuggling via inconsistent chunk parsing.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2023-25690',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x mod_proxy HTTP request smuggling via crafted RewriteRule or ProxyPassMatch.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2023-27522',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_proxy_uwsgi HTTP response splitting via crafted response headers.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2023-31122',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x mod_macro out-of-bounds read via substitution into long strings.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2023-45802',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x HTTP/2 memory not reclaimed after stream reset DoS vulnerability.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2024-27316',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Apache 2.4.x HTTP/2 CONTINUATION frames flood causes CPU exhaustion DoS.'},
 {'tech': 'Apache HTTP Server',
  'version_match': '^2\\.4\\.4[1-9]|^2\\.4\\.[5-9][0-9]',
  'cve': 'CVE-2024-38476',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Apache 2.4.x mod_proxy backend malicious response injection allows code execution.'},
 {'tech': 'nginx',
  'version_match': '^0\\.',
  'cve': 'CVE-2009-2629',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'nginx 0.x buffer underflow in proxy module via crafted URI allows remote code execution.'},
 {'tech': 'nginx',
  'version_match': '^0\\.',
  'cve': 'CVE-2010-2263',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'nginx 0.x Windows path traversal via crafted request allows reading arbitrary files.'},
 {'tech': 'nginx',
  'version_match': '^0\\.',
  'cve': 'CVE-2011-4315',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 0.x heap buffer overflow in resolver allows remote code execution via crafted DNS response.'},
 {'tech': 'nginx',
  'version_match': '^0\\.',
  'cve': 'CVE-2012-1180',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 0.x use-after-free in worker process via crafted HTTP request causes crash.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-5]\\.',
  'cve': 'CVE-2013-2028',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'nginx 1.3.9-1.4.0 stack heap overflow via chunked transfer encoding allows remote code execution.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-5]\\.',
  'cve': 'CVE-2013-4547',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x crafted URI with unescaped space allows bypassing access controls via fastcgi.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2014-0088',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.5.x SPDY memory corruption via specially crafted request.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2014-3616',
  'severity': 'MEDIUM',
  'cvss': '5.8',
  'description': 'nginx 1.x virtual host confusion via SSL session reuse across different server blocks.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2016-0742',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x invalid pointer dereference via DNS resolver allows remote code execution.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2016-0746',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'nginx 1.x use-after-free in resolver allows remote code execution via crafted DNS response.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2016-0747',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x CNAME resolution without infinite loop protection allows DoS via DNS.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2016-4450',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x NULL pointer dereference via crafted MP4 file via ngx_http_mp4_module.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2017-7529',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x integer overflow in range filter causes memory disclosure via crafted byte-range.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2018-16843',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x HTTP/2 implementation memory exhaustion via excess WINDOW_UPDATE frames.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2018-16844',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x HTTP/2 excessive CPU usage via crafted PRIORITY frames DoS.'},
 {'tech': 'nginx',
  'version_match': '^1\\.[0-9]\\.',
  'cve': 'CVE-2018-16845',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'nginx 1.x ngx_http_mp4_module infinite loop and memory disclosure via crafted MP4 files.'},
 {'tech': 'nginx',
  'version_match': '^1\\.(?:1[0-9]|20)\\.',
  'cve': 'CVE-2019-9511',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x HTTP/2 Data Dribble attack causes CPU exhaustion via small window sizes.'},
 {'tech': 'nginx',
  'version_match': '^1\\.(?:1[0-9]|20)\\.',
  'cve': 'CVE-2019-9513',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x HTTP/2 Resource Loop attack exhausts CPU via crafted PRIORITY frame flood.'},
 {'tech': 'nginx',
  'version_match': '^1\\.(?:1[0-9]|20)\\.',
  'cve': 'CVE-2019-9516',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 1.x HTTP/2 0-Length Headers Leak fills memory via repeated zero-length headers.'},
 {'tech': 'nginx',
  'version_match': '^1\\.(?:1[0-9]|20)\\.',
  'cve': 'CVE-2021-23017',
  'severity': 'HIGH',
  'cvss': '7.7',
  'description': 'nginx 1.x DNS resolver off-by-one error allows one-byte heap write via crafted DNS response.'},
 {'tech': 'nginx',
  'version_match': '^1\\.(?:1[0-9]|20)\\.',
  'cve': 'CVE-2022-41741',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'nginx 1.x ngx_http_mp4_module integer overflow and heap corruption via crafted MP4 files.'},
 {'tech': 'nginx',
  'version_match': '^1\\.(?:1[0-9]|20)\\.',
  'cve': 'CVE-2022-41742',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'nginx 1.x ngx_http_mp4_module memory disclosure via crafted MP4 files with atom sizes.'},
 {'tech': 'nginx',
  'version_match': '^1\\.',
  'cve': 'CVE-2009-3896',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'nginx 0.8.x-1.0.x null byte in URI allows serving .php source files via FastCGI.'},
 {'tech': 'nginx',
  'version_match': '^1\\.(?:[0-9]|1[0-9]|20)\\.',
  'cve': 'CVE-2013-2070',
  'severity': 'MEDIUM',
  'cvss': '5.8',
  'description': 'nginx 1.x proxy module memory disclosure via crafted HTTP backend responses.'},
 {'tech': 'nginx',
  'version_match': '^1\\.(?:[0-9]|1[0-9]|20)\\.',
  'cve': 'CVE-2020-12440',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'nginx 1.x request smuggling via Transfer-Encoding header handling inconsistency.'},
 {'tech': 'nginx',
  'version_match': '^1\\.(?:[0-9]|1[0-9]|20)\\.',
  'cve': 'CVE-2021-3618',
  'severity': 'HIGH',
  'cvss': '7.4',
  'description': 'nginx 1.x ALPACA cross-protocol request forgery via crafted SMTP/FTP server responses.'},
 {'tech': 'nginx',
  'version_match': '^1\\.(?:[0-9]|1[0-9]|20)\\.',
  'cve': 'CVE-2024-7347',
  'severity': 'MEDIUM',
  'cvss': '4.7',
  'description': 'nginx 1.x ngx_http_mp4_module out-of-bounds read via specially crafted MP4 video file.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2010-4478',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'OpenSSH 5.x J-PAKE authentication bypass allows login without proper credential verification.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2011-0539',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'OpenSSH 5.x legacy certificate signing information disclosure via debug output.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2011-4327',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'OpenSSH 5.x ssh-keysign unsafe file access allows local privilege escalation.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2012-0814',
  'severity': 'MEDIUM',
  'cvss': '4.0',
  'description': 'OpenSSH 5.x auth_parse_options function logs sensitive information via crafted keys.'},
 {'tech': 'OpenSSH',
  'version_match': '^5\\.',
  'cve': 'CVE-2008-5161',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'OpenSSH 5.x CBC mode plaintext recovery attack via timing side-channel in SSH protocol.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2012-4922',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'OpenSSH 6.x denial of service via memory corruption in pam_ssh_agent_auth module.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2014-2532',
  'severity': 'MEDIUM',
  'cvss': '5.8',
  'description': 'OpenSSH 6.x AcceptEnv wildcard pattern bypass allows environment variable injection.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2014-2653',
  'severity': 'MEDIUM',
  'cvss': '5.8',
  'description': 'OpenSSH 6.x SSHFP DNS record verification bypass via DNSSEC not checked properly.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2015-5352',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'OpenSSH 6.x X11 forwarding incomplete revocation after PermitOpen restriction change.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2015-5600',
  'severity': 'HIGH',
  'cvss': '8.5',
  'description': 'OpenSSH 6.x keyboard-interactive authentication bypass via MaxAuthTries limit circumvention.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2015-6564',
  'severity': 'MEDIUM',
  'cvss': '6.9',
  'description': 'OpenSSH 6.x use-after-free in PAM support allows privilege escalation via keyboard-interactive.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2015-6563',
  'severity': 'MEDIUM',
  'cvss': '1.9',
  'description': 'OpenSSH 6.x privilege separation monitor MONITOR_REQ_PWNAM issue allows username revelation.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2016-0777',
  'severity': 'MEDIUM',
  'cvss': '6.5',
  'description': 'OpenSSH 6.x client roaming feature information disclosure leaks private keys to rogue server.'},
 {'tech': 'OpenSSH',
  'version_match': '^6\\.',
  'cve': 'CVE-2016-0778',
  'severity': 'HIGH',
  'cvss': '8.1',
  'description': 'OpenSSH 6.x client roaming heap buffer overflow allows code execution via rogue SSH server.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2016-3115',
  'severity': 'MEDIUM',
  'cvss': '5.5',
  'description': 'OpenSSH 7.x X11 forwarding xauth command injection via crafted xauth data.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2016-6210',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'OpenSSH 7.x user enumeration via timing difference between valid and invalid usernames.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2016-6515',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'OpenSSH 7.x auth_password function CPU DoS via very long passwords.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2017-15906',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'OpenSSH 7.x sftp-server process_open function zero-length file truncation vulnerability.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2018-15473',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'OpenSSH 7.x user enumeration via asymmetric response for valid vs invalid usernames.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2018-15919',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'OpenSSH 7.x username enumeration via auth2-gss.c in GSS2 authentication handling.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2018-20685',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'OpenSSH 7.x scp client improper directory name validation allows server-side directory traversal.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2019-6109',
  'severity': 'MEDIUM',
  'cvss': '6.8',
  'description': 'OpenSSH 7.x scp client object name manipulation attack via crafted server-side file listing.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2019-6111',
  'severity': 'MEDIUM',
  'cvss': '6.8',
  'description': 'OpenSSH 7.x scp server-side file overwrite via crafted file names in server response.'},
 {'tech': 'OpenSSH',
  'version_match': '^7\\.',
  'cve': 'CVE-2019-16905',
  'severity': 'MEDIUM',
  'cvss': '6.3',
  'description': 'OpenSSH 7.x integer overflow in XMSS key parsing allows heap corruption.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:5|6|7)\\.',
  'cve': 'CVE-2010-5107',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'OpenSSH 5-7.x login grace time exhaustion DoS via many connections not completing login.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:5|6|7)\\.',
  'cve': 'CVE-2023-38408',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'OpenSSH ssh-agent remote code execution via malicious agent forwarding to crafted PKCS#11 provider.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:5|6|7|8|9)\\.',
  'cve': 'CVE-2023-51385',
  'severity': 'MEDIUM',
  'cvss': '6.5',
  'description': 'OpenSSH ProxyCommand and RemoteCommand injection via username containing shell metacharacters.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:[5-9]|[1-9][0-9])\\.',
  'cve': 'CVE-2024-6387',
  'severity': 'CRITICAL',
  'cvss': '8.1',
  'description': 'OpenSSH regreSSHion race condition in signal handling allows unauthenticated remote code execution.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:5|6|7)\\.',
  'cve': 'CVE-2021-28041',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'OpenSSH double-free in ssh-agent via crafted PKCS#11 provider response.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:5|6|7)\\.',
  'cve': 'CVE-2020-14145',
  'severity': 'MEDIUM',
  'cvss': '5.9',
  'description': 'OpenSSH client algorithm enumeration via observable behavioral differences in handshake.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:5|6|7)\\.',
  'cve': 'CVE-2020-15778',
  'severity': 'HIGH',
  'cvss': '7.8',
  'description': 'OpenSSH scp command injection in to-argument allows code execution via backtick characters.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:5|6|7)\\.',
  'cve': 'CVE-2006-5051',
  'severity': 'HIGH',
  'cvss': '9.3',
  'description': 'OpenSSH signal handler race condition allows remote code execution via login process.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:5|6|7)\\.',
  'cve': 'CVE-2007-2243',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'OpenSSH 4.6 S/KEY authentication information disclosure via incorrect challenge display.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:5|6|7)\\.',
  'cve': 'CVE-2008-4109',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'OpenSSH use of deprecated pam_ssh_agent_auth module allows privilege escalation.'},
 {'tech': 'OpenSSH',
  'version_match': '^(?:5|6|7)\\.',
  'cve': 'CVE-2014-1692',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'OpenSSH memory corruption in roaming connection support via large key exchange data.'},
 {'tech': 'PHP',
  'version_match': '^5\\.4\\.',
  'cve': 'CVE-2014-3515',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4.x SPL ArrayObject/SPLObjectStorage unserialize type confusion allows code execution.'},
 {'tech': 'PHP',
  'version_match': '^5\\.4\\.',
  'cve': 'CVE-2014-4721',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'PHP 5.4.x phpinfo() type confusion allows information disclosure via crafted requests.'},
 {'tech': 'PHP',
  'version_match': '^5\\.4\\.',
  'cve': 'CVE-2014-9425',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 5.4.x double-free in zend_ts_hash_graceful_destroy causes heap corruption.'},
 {'tech': 'PHP',
  'version_match': '^5\\.4\\.',
  'cve': 'CVE-2015-2787',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4.x use-after-free vulnerability in process_nested_data allows code execution.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[45]\\.',
  'cve': 'CVE-2015-4022',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.4/5.5 integer overflow in ftp_genlist allows heap buffer overflow.'},
 {'tech': 'PHP',
  'version_match': '^5\\.5\\.',
  'cve': 'CVE-2015-4025',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.5.x pcntl_exec insufficient validation of $env parameter allows code injection.'},
 {'tech': 'PHP',
  'version_match': '^5\\.6\\.',
  'cve': 'CVE-2015-8835',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 5.6.x SOAP HTTP Digest authentication use-after-free in make_http_soap_request.'},
 {'tech': 'PHP',
  'version_match': '^5\\.6\\.',
  'cve': 'CVE-2016-3142',
  'severity': 'HIGH',
  'cvss': '8.1',
  'description': 'PHP 5.6.x phar extension out-of-bounds read via crafted ZIP archive.'},
 {'tech': 'PHP',
  'version_match': '^5\\.6\\.',
  'cve': 'CVE-2016-4073',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.6.x multibyte string negative size parameter buffer overflow in mb_strcut.'},
 {'tech': 'PHP',
  'version_match': '^5\\.6\\.',
  'cve': 'CVE-2016-5114',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.6.x fpm_log.c out-of-bounds write allows heap-based buffer overflow.'},
 {'tech': 'PHP',
  'version_match': '^5\\.6\\.',
  'cve': 'CVE-2016-7124',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.6.x unserialize __wakeup() bypass allows injection via object property count manipulation.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2016-9137',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5.x use-after-free in CURLFile implementation allows arbitrary code execution.'},
 {'tech': 'PHP',
  'version_match': '^5\\.[456]\\.',
  'cve': 'CVE-2014-2497',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'PHP 5.x GD library NULL pointer dereference via crafted imageColor functions.'},
 {'tech': 'PHP',
  'version_match': '^7\\.0\\.',
  'cve': 'CVE-2016-3078',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 7.0.x integer overflow in php_zip_make_relative_path allows heap buffer overflow.'},
 {'tech': 'PHP',
  'version_match': '^7\\.0\\.',
  'cve': 'CVE-2016-5771',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 7.0.x SPL use-after-free in spl_array.c allows remote code execution.'},
 {'tech': 'PHP',
  'version_match': '^7\\.0\\.',
  'cve': 'CVE-2016-5772',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 7.0.x double-free in wddx_deserialize via malformed WDDX packet.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2017-9798',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 7.x use-after-free in unserialize() with object property destruction.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2018-7584',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 7.x stack buffer overflow in httpd through crafted HTTP request parsing.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2018-10545',
  'severity': 'MEDIUM',
  'cvss': '4.7',
  'description': 'PHP 7.x FPM worker memory disclosure from previous request via dereference of dangling pointer.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2018-14851',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'PHP 7.x exif_read_data out-of-bounds write via malformed JPEG image.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2019-11041',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'PHP 7.x exif_read_data heap buffer overflow via crafted image with exif data.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2019-11042',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'PHP 7.x exif_read_data heap buffer over-read via EXIF Thumbnail in crafted JPEG.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2019-11043',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 7.x FPM env_path_info underflow in fpm_main.c allows remote code execution with nginx.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2020-7059',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'PHP 7.x mbstring out-of-bounds read via mb_strtolower function with invalid UTF-8 input.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2020-7060',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'PHP 7.x mbstring global buffer overflow via mb_regex_encoding with long pattern.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[234]\\.',
  'cve': 'CVE-2020-7065',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'PHP 7.x mb_strtolower buffer overflow via crafted input string in specific locale.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2021-21702',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 7.x SOAP extension NULL pointer dereference in SoapClient allows server crash.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2021-21704',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 7.x Firebird PDO access violation via crafted SQL queries.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2021-21705',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'PHP 7.x SSRF bypass via URL validation inconsistency with filter_var FILTER_VALIDATE_URL.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2022-31625',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 7.x Postgres extension use-after-free via PostgreSQL API callback manipulation.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2022-31626',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 7.x pdo_mysql buffer overflow via long password during reconnect attempt.'},
 {'tech': 'PHP',
  'version_match': '^7\\.[01234]\\.',
  'cve': 'CVE-2023-0567',
  'severity': 'MEDIUM',
  'cvss': '6.2',
  'description': 'PHP 7.x password_verify bcrypt comparison side channel information disclosure.'},
 {'tech': 'PHP',
  'version_match': '^(?:5\\.[456]|7\\.[01234])\\.',
  'cve': 'CVE-2016-10712',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'PHP 5/7 iconv stream filter memory disclosure via crafted sequence of concatenation.'},
 {'tech': 'PHP',
  'version_match': '^(?:5\\.[456]|7\\.[01234])\\.',
  'cve': 'CVE-2015-3307',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'PHP 5/7 phar extension invalid pointer dereference allows code execution via crafted phar.'},
 {'tech': 'PHP',
  'version_match': '^(?:5\\.[456]|7\\.[01234])\\.',
  'cve': 'CVE-2020-7064',
  'severity': 'MEDIUM',
  'cvss': '5.4',
  'description': 'PHP 5/7 EXIF use-after-free on heap via exif_process_ICC_TAG allowing read beyond buffer.'},
 {'tech': 'WordPress',
  'version_match': '^3\\.',
  'cve': 'CVE-2015-5622',
  'severity': 'MEDIUM',
  'cvss': '5.4',
  'description': 'WordPress 3.x cross-site scripting vulnerability via shortcode tags and HTML in posts.'},
 {'tech': 'WordPress',
  'version_match': '^3\\.',
  'cve': 'CVE-2015-5731',
  'severity': 'MEDIUM',
  'cvss': '5.4',
  'description': 'WordPress 3.x cross-site request forgery in class-wp-customize-widgets.php.'},
 {'tech': 'WordPress',
  'version_match': '^3\\.',
  'cve': 'CVE-2014-0166',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'WordPress 3.x authentication bypass via forged auth cookies due to weak nonce validation.'},
 {'tech': 'WordPress',
  'version_match': '^3\\.',
  'cve': 'CVE-2014-5204',
  'severity': 'MEDIUM',
  'cvss': '6.8',
  'description': 'WordPress 3.x cross-site request forgery in wp-login.php action registration.'},
 {'tech': 'WordPress',
  'version_match': '^3\\.',
  'cve': 'CVE-2013-2173',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'WordPress 3.x denial of service in password checking via huge bcrypt cost factor.'},
 {'tech': 'WordPress',
  'version_match': '^4\\.',
  'cve': 'CVE-2019-8942',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'WordPress 4.x remote code execution via path traversal in image crop functionality.'},
 {'tech': 'WordPress',
  'version_match': '^4\\.',
  'cve': 'CVE-2017-5487',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'WordPress 4.x REST API user enumeration via /wp-json/wp/v2/users endpoint.'},
 {'tech': 'WordPress',
  'version_match': '^4\\.',
  'cve': 'CVE-2016-10033',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'WordPress 4.x PHPMailer injection via crafted From address in wp_mail function.'},
 {'tech': 'WordPress',
  'version_match': '^4\\.',
  'cve': 'CVE-2017-9066',
  'severity': 'MEDIUM',
  'cvss': '5.8',
  'description': 'WordPress 4.x SSRF via crafted URLs in HTTP redirect validation bypass.'},
 {'tech': 'WordPress',
  'version_match': '^4\\.',
  'cve': 'CVE-2018-6389',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'WordPress 4.x DoS via load-scripts.php crafted request loading many scripts.'},
 {'tech': 'WordPress',
  'version_match': '^4\\.',
  'cve': 'CVE-2019-16218',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'WordPress 4.x stored cross-site scripting in Customizer via crafted page title.'},
 {'tech': 'WordPress',
  'version_match': '^4\\.',
  'cve': 'CVE-2019-17675',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'WordPress 4.x CSRF via wp_validate_redirect insufficient validation of URLs.'},
 {'tech': 'WordPress',
  'version_match': '^5\\.',
  'cve': 'CVE-2020-28032',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'WordPress 5.x PHP object injection via deserialization in core wp-includes/Requests/.'},
 {'tech': 'WordPress',
  'version_match': '^5\\.',
  'cve': 'CVE-2020-28033',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'WordPress 5.x multisite SSRF via embed discovery requests with spoofed oEmbed requests.'},
 {'tech': 'WordPress',
  'version_match': '^5\\.',
  'cve': 'CVE-2020-28034',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'WordPress 5.x XSS via the global variables in wp-includes/class-wp.php.'},
 {'tech': 'WordPress',
  'version_match': '^5\\.',
  'cve': 'CVE-2021-29447',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'WordPress 5.7 XXE injection via crafted WAV file upload in media library.'},
 {'tech': 'WordPress',
  'version_match': '^5\\.',
  'cve': 'CVE-2021-29450',
  'severity': 'MEDIUM',
  'cvss': '4.3',
  'description': 'WordPress 5.x authenticated information disclosure via exposing private post content.'},
 {'tech': 'WordPress',
  'version_match': '^5\\.',
  'cve': 'CVE-2022-3590',
  'severity': 'MEDIUM',
  'cvss': '5.9',
  'description': 'WordPress 5.x SSRF via dns rebinding attack on local network hosts through pingback.'},
 {'tech': 'WordPress',
  'version_match': '^6\\.',
  'cve': 'CVE-2023-2745',
  'severity': 'MEDIUM',
  'cvss': '6.4',
  'description': 'WordPress 6.x directory traversal via locale parameter in wp-admin/load-scripts.'},
 {'tech': 'WordPress',
  'version_match': '^6\\.',
  'cve': 'CVE-2023-5692',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'WordPress 6.x information disclosure via REST API password-protected post exposure.'},
 {'tech': 'WordPress',
  'version_match': '^(?:3|4|5|6)\\.',
  'cve': 'CVE-2022-21663',
  'severity': 'HIGH',
  'cvss': '7.2',
  'description': 'WordPress core SQL injection via crafted queries in WP_Query meta_query parameter.'},
 {'tech': 'WordPress Plugin: WooCommerce',
  'version_match': '^[1-5]\\.',
  'cve': 'CVE-2021-32789',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'WooCommerce <= 5.5.0 SQL injection via order search in admin panel allowing data extraction.'},
 {'tech': 'WordPress Plugin: WooCommerce',
  'version_match': '^[1-5]\\.',
  'cve': 'CVE-2022-29455',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'WooCommerce reflected XSS via crafted URL in shop search functionality.'},
 {'tech': 'WordPress Plugin: Elementor',
  'version_match': '^[123]\\.',
  'cve': 'CVE-2022-1329',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Elementor <= 3.6.2 authenticated RCE via file upload to the plugin installer.'},
 {'tech': 'WordPress Plugin: Contact Form 7',
  'version_match': '^[1-5]\\.',
  'cve': 'CVE-2020-35489',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'Contact Form 7 < 5.3.2 unrestricted file upload via crafted multipart form submission.'},
 {'tech': 'WordPress Plugin: Yoast SEO',
  'version_match': '^(?:[1-9]|1[0-6])\\.',
  'cve': 'CVE-2021-25118',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Yoast SEO <= 16.7 unauthenticated information disclosure of internal server paths.'},
 {'tech': 'WordPress Plugin: All-in-One SEO Pack',
  'version_match': '^[123]\\.',
  'cve': 'CVE-2021-25036',
  'severity': 'CRITICAL',
  'cvss': '9.9',
  'description': 'All-in-One SEO < 4.1.5.2 authenticated privilege escalation via REST API endpoints.'},
 {'tech': 'WordPress Plugin: Ninja Forms',
  'version_match': '^3\\.',
  'cve': 'CVE-2021-20109',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Ninja Forms < 3.4.34 PHP object injection via deserialization of crafted form data.'},
 {'tech': 'WordPress Plugin: Rank Math SEO',
  'version_match': '^1\\.',
  'cve': 'CVE-2020-11514',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Rank Math < 1.0.41 unauthenticated privilege escalation via REST API role assignment.'},
 {'tech': 'WordPress Plugin: File Manager',
  'version_match': '^[1-6]\\.',
  'cve': 'CVE-2020-25213',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'File Manager (elFinderConnector) < 6.9 unauthenticated arbitrary file upload and RCE.'},
 {'tech': 'WordPress Plugin: WP Fastest Cache',
  'version_match': '^0\\.',
  'cve': 'CVE-2023-6063',
  'severity': 'HIGH',
  'cvss': '8.6',
  'description': 'WP Fastest Cache < 1.2.2 SQL injection via cookie parameter allowing unauthenticated DB access.'},
 {'tech': 'WordPress Plugin: WP Super Cache',
  'version_match': '^1\\.',
  'cve': 'CVE-2021-24209',
  'severity': 'HIGH',
  'cvss': '7.2',
  'description': 'WP Super Cache < 1.7.4 RCE via configuration page update by authenticated admin.'},
 {'tech': 'WordPress Plugin: Duplicator',
  'version_match': '^1\\.',
  'cve': 'CVE-2020-11738',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Duplicator < 1.3.28 unauthenticated arbitrary file download via installer.php.'},
 {'tech': 'WordPress Plugin: Slider Revolution',
  'version_match': '^[1-6]\\.',
  'cve': 'CVE-2014-9734',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Slider Revolution < 4.2 arbitrary file read via path traversal in file download.'},
 {'tech': 'WordPress Plugin: Wordfence',
  'version_match': '^[1-7]\\.',
  'cve': 'CVE-2020-13149',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Wordfence < 7.4.5 stored XSS via crafted user-agent string in login attempt logs.'},
 {'tech': 'WordPress Plugin: W3 Total Cache',
  'version_match': '^0\\.',
  'cve': 'CVE-2021-24869',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'W3 Total Cache < 0.15.2 SSRF via crafted cache path in page speed settings.'},
 {'tech': 'WordPress Plugin: WP-DB-Backup',
  'version_match': '^[12345]\\.',
  'cve': 'CVE-2014-9290',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'WP-DB-Backup predictable backup file path allows unauthenticated download of database.'},
 {'tech': 'WordPress Plugin: Advanced Custom Fields',
  'version_match': '^[1-6]\\.',
  'cve': 'CVE-2023-30777',
  'severity': 'HIGH',
  'cvss': '7.1',
  'description': 'Advanced Custom Fields < 6.1.6 reflected XSS via field label admin interface.'},
 {'tech': 'Drupal',
  'version_match': '^6\\.',
  'cve': 'CVE-2014-3704',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'Drupal 6/7 Drupalgeddon SQL injection via crafted array form request parameter.'},
 {'tech': 'Drupal',
  'version_match': '^7\\.',
  'cve': 'CVE-2014-3704',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'Drupal 7 Drupalgeddon SQL injection via crafted array in HTTP request allows RCE.'},
 {'tech': 'Drupal',
  'version_match': '^7\\.',
  'cve': 'CVE-2018-7600',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupal 7 Drupalgeddon2 remote code execution via multiple subsystem crafted requests.'},
 {'tech': 'Drupal',
  'version_match': '^8\\.',
  'cve': 'CVE-2018-7600',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupal 8 Drupalgeddon2 RCE via Forms API AJAX requests with crafted form data.'},
 {'tech': 'Drupal',
  'version_match': '^(?:7|8)\\.',
  'cve': 'CVE-2018-7602',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupal 7/8 Drupalgeddon3 remote code execution via authenticated form submission.'},
 {'tech': 'Drupal',
  'version_match': '^8\\.',
  'cve': 'CVE-2019-6340',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupal 8 arbitrary code execution via REST API with crafted serialized PHP objects.'},
 {'tech': 'Drupal',
  'version_match': '^(?:8|9)\\.',
  'cve': 'CVE-2020-13671',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupal 8/9 unrestricted file upload vulnerability allows remote code execution.'},
 {'tech': 'Drupal',
  'version_match': '^(?:8|9)\\.',
  'cve': 'CVE-2020-28948',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Drupal 8/9 pear/archive_tar arbitrary file write via crafted tar archives.'},
 {'tech': 'Drupal',
  'version_match': '^(?:9|10)\\.',
  'cve': 'CVE-2022-25271',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Drupal 9/10 access bypass in media module allowing unauthorized file download.'},
 {'tech': 'Drupal',
  'version_match': '^(?:9|10)\\.',
  'cve': 'CVE-2022-25275',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Drupal 9/10 media oEmbed iframe information disclosure via crafted URL request.'},
 {'tech': 'Drupal',
  'version_match': '^(?:9|10)\\.',
  'cve': 'CVE-2023-31250',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Drupal 9/10 file access bypass allows access to private files without permission.'},
 {'tech': 'Drupal',
  'version_match': '^(?:8|9|10)\\.',
  'cve': 'CVE-2021-41184',
  'severity': 'MEDIUM',
  'cvss': '6.5',
  'description': 'Drupal jQuery UI XSS via crafted component using datepicker widget.'},
 {'tech': 'Drupal',
  'version_match': '^(?:7|8|9)\\.',
  'cve': 'CVE-2017-6381',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Drupal 7/8 remote code execution via unsafe deserialize in update manager.'},
 {'tech': 'Drupal',
  'version_match': '^(?:6|7)\\.',
  'cve': 'CVE-2012-2922',
  'severity': 'MEDIUM',
  'cvss': '5.0',
  'description': 'Drupal 6/7 information disclosure via system information page exposure to anonymous users.'},
 {'tech': 'Drupal',
  'version_match': '^(?:6|7)\\.',
  'cve': 'CVE-2011-2726',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Drupal 6/7 access bypass via improper IP address blocking in access rules.'},
 {'tech': 'Drupal',
  'version_match': '^(?:7|8|9|10)\\.',
  'cve': 'CVE-2022-39261',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'Drupal Twig template engine path traversal via template_from_string function.'},
 {'tech': 'Drupal',
  'version_match': '^(?:9|10)\\.',
  'cve': 'CVE-2023-29885',
  'severity': 'HIGH',
  'cvss': '8.0',
  'description': 'Drupal 9/10 Cross-site scripting in filter module via crafted text input.'},
 {'tech': 'Joomla',
  'version_match': '^1\\.5\\.',
  'cve': 'CVE-2013-5576',
  'severity': 'MEDIUM',
  'cvss': '6.8',
  'description': 'Joomla 1.5 com_media directory traversal and arbitrary file upload.'},
 {'tech': 'Joomla',
  'version_match': '^1\\.5\\.',
  'cve': 'CVE-2012-1563',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Joomla 1.5 authentication bypass via remember-me cookie manipulation.'},
 {'tech': 'Joomla',
  'version_match': '^2\\.5\\.',
  'cve': 'CVE-2013-3242',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Joomla 2.5 PHP object injection via unserialize in com_users leads to code execution.'},
 {'tech': 'Joomla',
  'version_match': '^2\\.5\\.',
  'cve': 'CVE-2014-7228',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 2.5 arbitrary file upload via crafted Content-Type header in com_media.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2015-8566',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Joomla 3.x session hijacking via PHP object injection in session handler.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2016-8870',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.x unauthorized user registration via account creation without authentication.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2016-9838',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.x account creation privilege escalation via crafted user group assignment.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2017-8917',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.x SQL injection via com_fields component crafted list field query.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2019-10945',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.x directory traversal and remote code execution via media manager.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2020-10238',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.x access control bypass in com_templates allowing arbitrary file operations.'},
 {'tech': 'Joomla',
  'version_match': '^3\\.',
  'cve': 'CVE-2021-23132',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Joomla 3.x com_media server-side request forgery via crafted URL in media manager.'},
 {'tech': 'Joomla',
  'version_match': '^4\\.',
  'cve': 'CVE-2023-23752',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Joomla 4.x improper access check exposes API endpoints with configuration data.'},
 {'tech': 'Joomla',
  'version_match': '^4\\.',
  'cve': 'CVE-2022-23793',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Joomla 4.x path traversal via com_installer component download request.'},
 {'tech': 'Joomla',
  'version_match': '^(?:3|4)\\.',
  'cve': 'CVE-2021-26027',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Joomla 3/4 information disclosure via crafted request to various API endpoints.'},
 {'tech': 'Joomla',
  'version_match': '^(?:3|4)\\.',
  'cve': 'CVE-2022-27912',
  'severity': 'MEDIUM',
  'cvss': '6.1',
  'description': 'Joomla 3/4 open redirect via crafted return URL parameter in login redirect.'},
 {'tech': 'Magento',
  'version_match': '^1\\.',
  'cve': 'CVE-2016-4010',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 1.x PHP object injection via crafted serialized object in checkout process.'},
 {'tech': 'Magento',
  'version_match': '^1\\.',
  'cve': 'CVE-2015-1397',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 1.x SQL injection via crafted store cookie in admin authentication bypass.'},
 {'tech': 'Magento',
  'version_match': '^1\\.',
  'cve': 'CVE-2015-1398',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 1.x remote code execution via malicious script in admin product import.'},
 {'tech': 'Magento',
  'version_match': '^1\\.',
  'cve': 'CVE-2015-1399',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 1.x arbitrary file inclusion via crafted layout XML in CMS pages.'},
 {'tech': 'Magento',
  'version_match': '^1\\.',
  'cve': 'CVE-2019-7139',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 1.x SQL injection via crafted order comment in sales order processing.'},
 {'tech': 'Magento',
  'version_match': '^2\\.[012]\\.',
  'cve': 'CVE-2019-8118',
  'severity': 'MEDIUM',
  'cvss': '5.3',
  'description': 'Magento 2.x security log disclosure via crafted URL exposing admin activity log.'},
 {'tech': 'Magento',
  'version_match': '^2\\.[012]\\.',
  'cve': 'CVE-2020-24407',
  'severity': 'CRITICAL',
  'cvss': '9.1',
  'description': 'Magento 2.x path traversal in page builder template allows arbitrary file write.'},
 {'tech': 'Magento',
  'version_match': '^2\\.[012]\\.',
  'cve': 'CVE-2020-24400',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Magento 2.x SQL injection in catalog search filtering via crafted GET parameters.'},
 {'tech': 'Magento',
  'version_match': '^2\\.[0123]\\.',
  'cve': 'CVE-2022-24086',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 2.x improper input validation allows unauthenticated RCE via crafted checkout.'},
 {'tech': 'Magento',
  'version_match': '^2\\.[0123]\\.',
  'cve': 'CVE-2022-24087',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 2.x RCE bypass for CVE-2022-24086 via alternative template injection path.'},
 {'tech': 'Magento',
  'version_match': '^2\\.[0123]\\.',
  'cve': 'CVE-2021-21024',
  'severity': 'HIGH',
  'cvss': '7.7',
  'description': 'Magento 2.x SSRF in customer address saving feature via crafted street field.'},
 {'tech': 'Magento',
  'version_match': '^2\\.[0123]\\.',
  'cve': 'CVE-2021-28565',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 2.x deserialization of untrusted data in Zend_Mail leads to code execution.'},
 {'tech': 'Magento',
  'version_match': '^2\\.[0123]\\.',
  'cve': 'CVE-2023-22247',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Magento 2.x improper authorization allows deletion of other customer addresses.'},
 {'tech': 'Magento',
  'version_match': '^(?:1|2)\\.',
  'cve': 'CVE-2018-5268',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Magento 1/2 Magento Shoplift admin authentication bypass via APPSEC-1057.'},
 {'tech': 'Magento',
  'version_match': '^2\\.[0123]\\.',
  'cve': 'CVE-2023-38218',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Adobe Commerce/Magento 2.x OS command injection via crafted gift card account data.'},
 {'tech': 'Spring Framework',
  'version_match': '^(?:4|5)\\.',
  'cve': 'CVE-2018-1270',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Spring Framework 4/5 STOMP over WebSocket remote code execution via SpEL injection.'},
 {'tech': 'Spring Framework',
  'version_match': '^(?:4|5)\\.',
  'cve': 'CVE-2018-1275',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Spring Framework 4/5 remote code execution via Address partial fix bypass in STOMP messaging.'},
 {'tech': 'Spring Framework',
  'version_match': '^(?:5)\\.',
  'cve': 'CVE-2022-22965',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Spring4Shell: Spring Framework RCE via data binding on JDK 9+ with Tomcat as WAR deployment.'},
 {'tech': 'Spring Framework',
  'version_match': '^(?:5)\\.',
  'cve': 'CVE-2022-22950',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Spring Framework 5.x DoS via crafted SpEL expression causing excessive resource usage.'},
 {'tech': 'Spring Framework',
  'version_match': '^(?:4|5)\\.',
  'cve': 'CVE-2016-5007',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Spring Security/MVC path matching inconsistency allows authorization bypass.'},
 {'tech': 'Spring Framework',
  'version_match': '^(?:4|5)\\.',
  'cve': 'CVE-2017-8046',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Spring Data REST RCE via PATCH request with crafted JSON-patch document (SpEL injection).'},
 {'tech': 'Spring Framework',
  'version_match': '^(?:5)\\.',
  'cve': 'CVE-2022-22970',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Spring Framework 5.x DoS via data binding with multipart file crafted request.'},
 {'tech': 'Spring Framework',
  'version_match': '^(?:5)\\.',
  'cve': 'CVE-2022-22971',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Spring Framework 5.x DoS via STOMP subscription with crafted broker relay destination.'},
 {'tech': 'Log4j',
  'version_match': '^2\\.(?:[0-9]|1[0-6])\\.',
  'cve': 'CVE-2021-44228',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'Log4Shell: Apache Log4j2 JNDI injection RCE via crafted log messages in any field.'},
 {'tech': 'Log4j',
  'version_match': '^2\\.(?:[0-9]|1[0-6])\\.',
  'cve': 'CVE-2021-45046',
  'severity': 'CRITICAL',
  'cvss': '9.0',
  'description': 'Log4j2 incomplete fix for Log4Shell allows RCE via context lookup in non-default configurations.'},
 {'tech': 'Log4j',
  'version_match': '^2\\.(?:[0-9]|1[0-6])\\.',
  'cve': 'CVE-2021-45105',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Log4j2 2.x infinite recursion DoS via crafted lookup string in self-referential pattern.'},
 {'tech': 'Log4j',
  'version_match': '^2\\.(?:[0-9]|1[0-6])\\.',
  'cve': 'CVE-2021-44832',
  'severity': 'MEDIUM',
  'cvss': '6.6',
  'description': 'Log4j2 2.x RCE via attacker-controlled JDBC Appender configuration with JNDI URI.'},
 {'tech': 'Spring Boot',
  'version_match': '^2\\.',
  'cve': 'CVE-2022-22963',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Spring Cloud Function RCE via crafted SpEL expression in routing-expression header.'},
 {'tech': 'Spring Security',
  'version_match': '^(?:4|5)\\.',
  'cve': 'CVE-2018-1199',
  'severity': 'HIGH',
  'cvss': '8.1',
  'description': 'Spring Security 4/5 authentication bypass via race condition in security context clearing.'},
 {'tech': 'Spring Security',
  'version_match': '^(?:4|5)\\.',
  'cve': 'CVE-2022-22978',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Spring Security 5.x RegexRequestMatcher authentication bypass via crafted path with newlines.'},
 {'tech': 'Jenkins',
  'version_match': '^(?:1|2)\\.',
  'cve': 'CVE-2016-0792',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Jenkins < 1.650 JNLP agent remote code execution via crafted Jenkins agent protocol.'},
 {'tech': 'Jenkins',
  'version_match': '^(?:1|2)\\.',
  'cve': 'CVE-2016-0788',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Jenkins < 1.650 CLI deserialization vulnerability allows unauthenticated RCE.'},
 {'tech': 'Jenkins',
  'version_match': '^(?:1|2)\\.',
  'cve': 'CVE-2017-1000353',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Jenkins < 2.56 Java deserialization vulnerability via Jenkins CLI port allows RCE.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2018-1000861',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Jenkins < 2.138 Stapler web framework unauthenticated code execution via crafted URL.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2019-1003000',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Jenkins < 2.161 Script Security Plugin sandbox bypass via crafted Groovy script.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2019-1003005',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Jenkins Pipeline: Groovy Plugin sandbox bypass via method call in Pipeline scripts.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2019-10392',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Jenkins Git Client Plugin OS command injection via crafted repository URL.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2020-2100',
  'severity': 'HIGH',
  'cvss': '7.5',
  'description': 'Jenkins < 2.219 UDP amplification attack reflection via UDP broadcast discovery.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2020-2160',
  'severity': 'HIGH',
  'cvss': '8.0',
  'description': 'Jenkins < 2.228 CSRF via cross-domain POST requests to any endpoint.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2021-21607',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Jenkins < 2.274 graph console job XSS via crafted Graph labels in job name.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2022-36882',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Jenkins Git Plugin CSRF in checkout via crafted URL leading to code execution.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2023-27898',
  'severity': 'CRITICAL',
  'cvss': '9.6',
  'description': 'Jenkins < 2.393 XSS via update center response injection into administrator notifications.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2023-27905',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Jenkins update-center2 MITM RCE via unsigned update-center metadata download.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2024-23897',
  'severity': 'CRITICAL',
  'cvss': '9.8',
  'description': 'Jenkins < 2.441 arbitrary file read via CLI parser allows unauthenticated RCE.'},
 {'tech': 'Jenkins',
  'version_match': '^2\\.',
  'cve': 'CVE-2024-23898',
  'severity': 'HIGH',
  'cvss': '8.8',
  'description': 'Jenkins < 2.441 WebSocket CLI endpoint cross-site WebSocket hijacking.'},
 {'tech': 'GitLab',
  'version_match': '^(?:1[0-3])\\.',
  'cve': 'CVE-2021-22205',
  'severity': 'CRITICAL',
  'cvss': '10.0',
  'description': 'GitLab 11.9-13.10 ExifTool RCE via unauthenticated crafted image upload.'},
 {'tech': 'GitLab',
  'version_match': '^(?:1[2-4])\\.',
  'cve': 'CVE-2022-2185',
  'severity': 'CRITICAL',
  'cvss': '9.9',
  'description': 'GitLab 12.0-15.1 RCE via malicious Github repository import.'},
 {'tech': 'GitLab',
  'version_match': '^(?:1[0-5])\\.',
  'cve': 'CVE-2021-22214',
  'severity': 'HIGH',
  'cvss': '8.6',
  'description': 'GitLab SSRF via project import feature allows requesting internal network resources.'}]
