"""§22 API Security — 108 endpoints per 22_apisec.md.
10 sections: discovery, OWASP API Top 10, auth, authz, rate limit, GraphQL,
gRPC, WebSocket/SSE/WebTransport, SOAP/REST legacy, supply chain/versioning.
"""
from tools._pack_common import make_advisory_router

T = [
    # §1 API Discovery & Inventory (13)
    ("openapi_swagger_discovery", "OpenAPI/Swagger discovery.", "INFO", "0.0"),
    ("postman_collection_discovery", "Postman collection discovery.", "INFO", "0.0"),
    ("graphql_schema_discovery", "GraphQL schema discovery.", "INFO", "0.0"),
    ("grpc_reflection_discovery", "gRPC reflection discovery.", "INFO", "0.0"),
    ("api_endpoint_brute", "API endpoint brute-force.", "INFO", "0.0"),
    ("hidden_api_versions", "Hidden API versions discovery.", "MEDIUM", "5.5"),
    ("openapi_swagger_exposed", "OpenAPI/Swagger publicly exposed.", "MEDIUM", "5.5"),
    ("api_shadow_inventory", "API shadow inventory.", "HIGH", "7.0"),
    ("api_deprecated_endpoints", "Deprecated API endpoints still live.", "MEDIUM", "5.5"),
    ("api_developer_portal_audit", "API developer portal audit.", "MEDIUM", "5.5"),
    ("postman_workspace_audit", "Postman workspace audit.", "MEDIUM", "5.5"),
    ("readme_io_audit", "Readme.io audit.", "INFO", "0.0"),
    ("manual_api_discovery", "Manual API discovery.", "INFO", "0.0"),
    # §2 OWASP API Top 10 2023 (19)
    ("api1_bola_object_authz", "API1: BOLA (object-level authz).", "HIGH", "7.5"),
    ("api2_broken_auth", "API2: Broken auth.", "HIGH", "8.0"),
    ("api3_bopla_property_authz", "API3: BOPLA (property-level authz).", "HIGH", "7.5"),
    ("api4_unrestricted_resource_consumption", "API4: Unrestricted resource consumption (DoS class).", "HIGH", "7.0"),
    ("api5_bfla_function_authz", "API5: BFLA (function-level authz).", "HIGH", "7.5"),
    ("api6_unrestricted_sensitive_access", "API6: Unrestricted access to sensitive business flows.", "HIGH", "7.5"),
    ("api7_ssrf", "API7: SSRF.", "HIGH", "8.0"),
    ("api8_misconfig", "API8: Security misconfig.", "HIGH", "7.5"),
    ("api9_shadow_inventory_top10", "API9: Improper inventory management.", "MEDIUM", "5.5"),
    ("api10_3rd_party_consumption", "API10: Unsafe consumption of 3rd-party APIs.", "MEDIUM", "5.5"),
    ("api_mass_assignment", "API mass assignment.", "HIGH", "7.5"),
    ("api_xxe", "API XXE.", "HIGH", "8.0"),
    ("api_command_injection", "API command injection.", "HIGH", "8.5"),
    ("api_path_traversal", "API path traversal.", "HIGH", "7.5"),
    ("api_lfi_rfi", "API LFI/RFI.", "HIGH", "8.0"),
    ("api_csrf_state_changing", "API CSRF on state-changing endpoints.", "HIGH", "7.0"),
    ("api_open_redirect", "API open redirect.", "MEDIUM", "5.5"),
    ("manual_owasp_api_review", "Manual OWASP API Top 10 review.", "INFO", "0.0"),
    ("manual_business_logic_review", "Manual business logic review.", "INFO", "0.0"),
    # §3 Authentication API-specific (12)
    ("api_jwt_none_alg", "JWT alg=none API.", "CRITICAL", "9.0"),
    ("api_jwt_weak_hs256", "JWT weak HS256.", "HIGH", "8.0"),
    ("api_jwt_jku_x5u_ssrf", "JWT JKU/X5U SSRF.", "HIGH", "8.0"),
    ("api_jwt_kid_traversal", "JWT kid path traversal.", "HIGH", "8.0"),
    ("api_jwt_kid_sqli", "JWT kid SQLi.", "HIGH", "8.0"),
    ("api_oauth_pkce_missing", "OAuth PKCE missing.", "MEDIUM", "5.5"),
    ("api_oauth_redirect_hijack", "OAuth redirect_uri hijack.", "HIGH", "7.5"),
    ("api_oauth_state_csrf", "OAuth state CSRF.", "HIGH", "7.0"),
    ("api_oidc_nonce_audit", "OIDC nonce audit.", "MEDIUM", "5.5"),
    ("api_session_fixation", "Session fixation.", "MEDIUM", "5.5"),
    ("api_cookie_security_flags", "Cookie security flags.", "MEDIUM", "5.5"),
    ("manual_api_auth_review", "Manual API auth review.", "INFO", "0.0"),
    # §4 Authorization (10)
    ("api_idor_param_swap", "IDOR param swap.", "HIGH", "7.5"),
    ("api_horizontal_authz", "Horizontal authz bypass.", "HIGH", "7.5"),
    ("api_vertical_authz", "Vertical authz bypass.", "HIGH", "8.0"),
    ("api_role_in_jwt_tamper", "Role-in-JWT tamper.", "HIGH", "8.0"),
    ("api_admin_bypass_header", "Admin bypass via X-Forwarded header.", "HIGH", "8.0"),
    ("api_authz_method_override", "HTTP method override authz bypass.", "HIGH", "7.0"),
    ("api_authz_content_type_smuggle", "Content-Type smuggle authz bypass.", "MEDIUM", "5.5"),
    ("api_authz_path_traversal", "Authz path traversal.", "HIGH", "7.5"),
    ("manual_authz_review", "Manual authz review.", "INFO", "0.0"),
    ("manual_authz_matrix", "Manual authz matrix.", "INFO", "0.0"),
    # §5 Rate Limiting (7)
    ("rate_limit_ip_bypass", "Rate limit IP bypass.", "MEDIUM", "5.5"),
    ("rate_limit_header_bypass", "Rate limit X-Forwarded-For bypass.", "HIGH", "7.0"),
    ("rate_limit_path_normalize_bypass", "Path normalization rate-limit bypass.", "MEDIUM", "5.5"),
    ("rate_limit_method_bypass", "Method-based rate-limit bypass.", "MEDIUM", "5.5"),
    ("rate_limit_distributed_attack", "Distributed rate-limit attack.", "HIGH", "7.0"),
    ("billing_amplification_attack", "Billing amplification attack.", "HIGH", "7.0"),
    ("manual_rate_limit_review", "Manual rate-limit review.", "INFO", "0.0"),
    # §6 GraphQL Security (12)
    ("graphql_introspection_open", "GraphQL introspection open.", "HIGH", "7.5"),
    ("graphql_batching_dos", "GraphQL batching DoS.", "HIGH", "7.0"),
    ("graphql_depth_dos", "GraphQL query depth DoS.", "HIGH", "7.0"),
    ("graphql_aliases_dos", "GraphQL aliases DoS.", "HIGH", "7.0"),
    ("graphql_field_authz_bypass", "GraphQL field-level authz bypass.", "HIGH", "7.5"),
    ("graphql_mutation_authz", "GraphQL mutation authz.", "HIGH", "7.5"),
    ("graphql_inj_to_sqli", "GraphQL → SQLi propagation.", "HIGH", "8.0"),
    ("graphql_inj_to_ssrf", "GraphQL → SSRF propagation.", "HIGH", "8.0"),
    ("graphql_apollo_advisory", "Apollo Federation audit.", "MEDIUM", "5.5"),
    ("graphql_hasura_advisory", "Hasura audit.", "MEDIUM", "5.5"),
    ("manual_graphql_review", "Manual GraphQL review.", "INFO", "0.0"),
    ("manual_graphql_chain", "Manual GraphQL chain.", "INFO", "0.0"),
    # §7 gRPC Security (8) ⭐
    ("grpc_reflection_open", "⭐ gRPC reflection open.", "MEDIUM", "5.5"),
    ("grpc_no_mtls", "⭐ gRPC mTLS not enforced.", "HIGH", "7.5"),
    ("grpc_replay_attack", "⭐ gRPC replay attack.", "HIGH", "7.0"),
    ("grpc_metadata_injection", "⭐ gRPC metadata injection.", "HIGH", "7.0"),
    ("grpc_message_dos", "⭐ gRPC message-size DoS.", "HIGH", "7.0"),
    ("grpc_web_parity_audit", "⭐ gRPC-Web parity audit.", "MEDIUM", "5.5"),
    ("manual_grpc_review", "Manual gRPC review.", "INFO", "0.0"),
    ("manual_grpc_chain", "Manual gRPC chain.", "INFO", "0.0"),
    # §8 WebSocket / SSE / WebTransport (9) ⭐
    ("ws_origin_audit", "⭐ WebSocket origin audit.", "HIGH", "7.0"),
    ("ws_auth_audit", "⭐ WebSocket auth audit.", "HIGH", "7.5"),
    ("ws_injection_audit", "⭐ WebSocket injection.", "HIGH", "7.5"),
    ("ws_cross_origin_csrf", "⭐ WebSocket cross-origin CSRF.", "HIGH", "7.0"),
    ("sse_origin_audit", "⭐ SSE origin audit.", "MEDIUM", "5.5"),
    ("webtransport_audit", "⭐ WebTransport audit.", "MEDIUM", "5.5"),
    ("h2c_smuggling", "⭐ H2C smuggling.", "HIGH", "8.0"),
    ("http2_rapid_reset", "⭐ HTTP/2 Rapid Reset (CVE-2023-44487).", "HIGH", "7.5"),
    ("manual_modern_proto_review", "Manual modern protocol review.", "INFO", "0.0"),
    # §9 SOAP / REST Legacy (9)
    ("soap_wsdl_disclosure", "SOAP WSDL disclosure.", "INFO", "0.0"),
    ("soap_xxe", "SOAP XXE.", "HIGH", "8.0"),
    ("soap_action_spoof", "SOAP action spoofing.", "HIGH", "7.0"),
    ("soap_xml_signature_wrap", "SOAP XML signature wrap.", "HIGH", "8.0"),
    ("soap_xpath_injection", "SOAP XPath injection.", "HIGH", "7.5"),
    ("rest_jsonp_callback", "JSONP callback abuse.", "MEDIUM", "5.5"),
    ("rest_etag_csrf", "REST ETag CSRF.", "MEDIUM", "5.5"),
    ("rest_options_method_audit", "REST OPTIONS verb audit.", "INFO", "0.0"),
    ("manual_soap_rest_review", "Manual SOAP/REST review.", "INFO", "0.0"),
    # §10 API Supply Chain / Versioning (11) ⭐
    ("api_version_skew_audit", "⭐ API version skew audit.", "MEDIUM", "5.5"),
    ("api_key_in_url_leak", "⭐ API key in URL leak.", "HIGH", "7.5"),
    ("api_key_logging_audit", "⭐ API key logging audit.", "HIGH", "7.0"),
    ("api_3rd_party_consumption", "⭐ Unsafe 3rd-party API consumption.", "HIGH", "7.0"),
    ("api_webhook_ssrf", "⭐ API webhook SSRF.", "HIGH", "8.0"),
    ("api_oauth_introspection_abuse", "⭐ OAuth introspection abuse.", "MEDIUM", "5.5"),
    ("api_consumer_secret_rotation", "⭐ Consumer secret rotation.", "MEDIUM", "5.5"),
    ("api_deprecation_lifecycle", "⭐ API deprecation lifecycle.", "INFO", "0.0"),
    ("api_breaking_change_advisory", "⭐ Breaking change advisory.", "INFO", "0.0"),
    ("api_dependency_security_audit", "⭐ API dependency security audit.", "MEDIUM", "5.5"),
    ("manual_api_supply_chain", "Manual API supply chain review.", "INFO", "0.0"),
]

router = make_advisory_router("apisec", T,
    playbook_ref="See module_playbooks/22_apisec.md.")


def register(app):
    app.include_router(router)
