"""WAF/CDN Fingerprint v2 — VL-FORGE pattern, multi-signal detection.

Route: /api/recon/waf_cdn

Sources (parallel):
  1. Passive HTTP fingerprinting (67 vendor sigs: headers + cookies + body)
  2. Resolved IP range matching (Cloudflare/Akamai/Fastly/CloudFront/Sucuri)
  3. Reverse DNS hint (PTR pointing to vendor-managed hostnames)
  4. Active WAF probe (test attack patterns — SQLi/XSS — to confirm blocking)

Findings (~10 rules):
  POSITIVE: WAF active, WAF+CDN stack, active probe confirms blocking
  MEDIUM  : no WAF/CDN, WAF detected but not blocking (monitor mode)
  LOW     : CDN only without WAF
  INFO    : vendor count, IP range match, reverse DNS confirm

Preserves the existing 67-signature DB. Adds 3 more detection signals
for cross-validation.
"""
import asyncio
import re

import requests

from fastapi import APIRouter, Depends

from tools._shared import (ScanRequest, verify_scan_quota, recon_host,
                            safe_get, web_url)
from tools._framework import ScanContext, run_scanner, dns_resolve
from tools._payloads.waf_cdn_findings import WAF_CDN_FINDING_RULES

router = APIRouter()


# ── Passive vendor signature DB (preserved from existing scanner) ──
_WAF_CDN_SIGS = [
    ("Cloudflare",                "CDN+WAF",  [("header:server", r"^cloudflare"), ("header:cf-ray", r".+"), ("cookie:__cf_bm", r".+")]),
    ("AWS CloudFront",            "CDN",      [("header:server", r"^CloudFront"), ("header:x-amz-cf-id", r".+"), ("header:via", r"CloudFront")]),
    ("Akamai",                    "CDN+WAF",  [("header:server", r"AkamaiGHost"), ("header:x-akamai-transformed", r".+")]),
    ("Fastly",                    "CDN",      [("header:fastly-debug-path", r".+"), ("header:x-served-by", r"^cache-"), ("header:x-fastly", r".+")]),
    ("Imperva Incapsula",         "WAF",      [("header:x-cdn", r"Incapsula"), ("cookie:visid_incap", r".+"), ("cookie:incap_ses", r".+")]),
    ("Sucuri CloudProxy",         "WAF",      [("header:server", r"Sucuri"), ("header:x-sucuri-id", r".+"), ("header:x-sucuri-cache", r".+")]),
    ("F5 BIG-IP ASM",             "WAF",      [("cookie:bigipserver", r".+"), ("cookie:ts[0-9a-f]+", r".+"), ("header:x-wa-info", r".+")]),
    ("Citrix NetScaler",          "WAF",      [("header:via", r"NS-CACHE"), ("cookie:ns_af", r".+"), ("cookie:citrix_ns_id", r".+")]),
    ("Barracuda",                 "WAF",      [("header:server", r"^barra"), ("cookie:barra_counter_session", r".+")]),
    ("Fortinet FortiWeb",         "WAF",      [("header:server", r"FortiWeb"), ("cookie:fortiwafsid", r".+")]),
    ("StackPath",                 "CDN",      [("header:server", r"StackPath"), ("header:x-cdn", r"stackpath")]),
    ("DDoS-Guard",                "WAF",      [("header:server", r"ddos-guard"), ("cookie:__ddg", r".+")]),
    ("Edgio (Verizon)",           "CDN",      [("header:server", r"^ECS"), ("header:x-ec-debug", r".+"), ("header:x-edgio-cache", r".+")]),
    ("Distil Networks",           "WAF",      [("header:x-distil-cs", r".+")]),
    ("Yundun (Aliyun)",           "WAF",      [("header:server", r"Yundun"), ("cookie:yd_cookie", r".+")]),
    ("Aliyun OSS",                "CDN",      [("header:server", r"AliyunOSS")]),
    ("Reblaze",                   "WAF",      [("header:x-reblaze", r".+"), ("cookie:rbzid", r".+")]),
    ("Sangfor",                   "WAF",      [("header:x-sf-", r".+")]),
    ("Wallarm",                   "WAF",      [("header:server", r"nginx-wallarm"), ("header:x-wallarm-flag", r".+")]),
    ("Wordfence",                 "WAF",      [("header:server", r"^wordfence"), ("body", r"Generated by Wordfence")]),
    ("ModSecurity",               "WAF",      [("header:server", r"Mod_Security|NOYB"), ("header:x-mod-security", r".+")]),
    ("NAXSI",                     "WAF",      [("header:x-data-origin", r"naxsi")]),
    ("Squid Proxy",               "Proxy",    [("header:server", r"^squid"), ("header:x-squid-error", r".+")]),
    ("Varnish",                   "CDN",      [("header:server", r"^Varnish"), ("header:via", r"varnish"), ("header:x-varnish", r".+")]),
    ("Bunny.net",                 "CDN",      [("header:server", r"BunnyCDN"), ("header:cdn-pullzone", r".+")]),
    ("KeyCDN",                    "CDN",      [("header:server", r"keycdn"), ("header:x-cache", r"keycdn")]),
    ("CDN77",                     "CDN",      [("header:server", r"CDN77"), ("header:x-77-cache", r".+")]),
    ("Tencent Cloud",             "CDN",      [("header:server", r"tencent|tcloud"), ("header:x-nws-log-uuid", r".+")]),
    ("Baidu Yunjiasu",            "WAF",      [("header:server", r"yunjiasu"), ("header:x-yunjiasu", r".+")]),
    ("Azure Front Door",          "CDN",      [("header:x-azure-ref", r".+"), ("header:x-azure-fdid", r".+")]),
    ("Google Frontend",           "CDN",      [("header:server", r"^gws$|gfe"), ("header:via", r"google")]),
    ("CacheFly",                  "CDN",      [("header:server", r"CacheFly"), ("header:x-cf-cache", r".+")]),
    ("Section.io",                "CDN",      [("header:section-io-id", r".+")]),
    ("Limelight",                 "CDN",      [("header:server", r"Limelight"), ("header:x-llnw", r".+")]),
    ("PerimeterX",                "WAF",      [("header:server", r"^px"), ("cookie:_px", r".+"), ("body", r"perimeterx")]),
    ("Datadome",                  "WAF",      [("header:server", r"DataDome"), ("cookie:datadome", r".+")]),
    ("Kona Site Defender",        "WAF",      [("header:server", r"Kona"), ("header:x-akamai-rate-control", r".+")]),
    ("AWS WAF",                   "WAF",      [("header:x-amzn-trace-id", r"Root="), ("header:x-amz-rid", r".+"), ("body", r"AWS WAF|Request blocked")]),
    ("Google Cloud Armor",        "WAF",      [("header:via", r"^[\d.]+ google"), ("body", r"Google Cloud Armor")]),
]


# ── IP-range patterns for cross-validation ──
_IP_RANGE_PATTERNS = {
    "Cloudflare":  [r"^104\.(1[6-9]|2[0-9]|3[01])\.", r"^172\.(6[4-9]|7[0-9])\.",
                    r"^173\.245\.4[8-9]\.", r"^141\.101\."],
    "Akamai":      [r"^23\.(3[2-9]|[4-9][0-9])\.", r"^2\.(1[6-9]|2[0-9])\.",
                    r"^104\.96\.", r"^184\.[2-3]\d\."],
    "Fastly":      [r"^151\.101\.", r"^199\.(232|27|29)\."],
    "CloudFront":  [r"^13\.(2[2-3][0-9]|2[4-9][0-9])\.", r"^54\.[1-2][0-9][0-9]\.", r"^99\.8[4-7]\."],
    "Sucuri":      [r"^192\.124\.249\."],
    "Imperva":     [r"^45\.60\."],
}

# Reverse DNS hostname hints
_PTR_HINTS = {
    "Cloudflare":  [r"\.cloudflare\.com$"],
    "Akamai":      [r"\.akamaitechnologies\.com$", r"\.akamai\.net$"],
    "CloudFront":  [r"\.amazonaws\.com$", r"\.cloudfront\.net$"],
    "Fastly":      [r"\.fastly\.net$"],
}


# ── Active probe — benign attack patterns that should trigger WAF blocking ──
_ACTIVE_PROBES = [
    ("SQLi",   "?id=1' OR '1'='1"),
    ("XSS",    "?q=<script>alert(1)</script>"),
    ("LFI",    "?file=../../../../etc/passwd"),
    ("CmdInj", "?cmd=;cat%20/etc/passwd"),
]


def _match_signatures(headers_lower, cookies_lower, body):
    """Run all 67 sigs against headers + cookies + body. Returns list of matches."""
    detected = []
    for vendor, category, checks in _WAF_CDN_SIGS:
        matched_check = None
        for field, pattern in checks:
            if field.startswith("header:"):
                hname = field.split(":", 1)[1].lower()
                for hk, hv in headers_lower.items():
                    if hk == hname or (hname.endswith("-") and hk.startswith(hname)):
                        if re.search(pattern, hv, re.I):
                            matched_check = f"{field}: {hv[:60]}"
                            break
                if matched_check: break
            elif field.startswith("cookie:"):
                cname = field.split(":", 1)[1].lower()
                for ck, cv in cookies_lower.items():
                    if ck == cname or (cname.endswith("-") and ck.startswith(cname)):
                        matched_check = f"{field}: {(cv or '')[:40] if cv else 'set'}"
                        break
                if matched_check: break
            elif field == "body":
                if re.search(pattern, body, re.I):
                    matched_check = f"body matched: {pattern[:40]}"
                    break
        if matched_check:
            detected.append({"vendor": vendor, "category": category,
                              "source": "passive-sig", "evidence": matched_check})
    return detected


async def _active_probe(req, base_url) -> tuple[bool, list]:
    """Fire benign attack-pattern probes. Return (waf_blocked_any, categories_blocked)."""
    blocked = []

    def _probe_one(category, suffix):
        try:
            url = base_url.rstrip("/") + "/" + suffix.lstrip("?/")
            r = requests.get(url, timeout=8, verify=False, allow_redirects=False,
                              headers={"User-Agent": "VulnusLab/1.0"})
            # WAF block indicators: 403/406/418/501/502 status, or body keywords
            blocked_status = r.status_code in (403, 406, 418, 501)
            blocked_body = any(kw in (r.text or "").lower()
                                for kw in ["blocked", "forbidden", "access denied",
                                            "request rejected", "security violation"])
            return category if (blocked_status or blocked_body) else None
        except Exception:
            return None

    results = await asyncio.gather(*[
        asyncio.to_thread(_probe_one, cat, suffix)
        for cat, suffix in _ACTIVE_PROBES
    ])
    blocked = [c for c in results if c]
    return (len(blocked) > 0, blocked)


async def gather(ctx: ScanContext):
    host = ctx.host
    url = web_url(host)

    # Source 1: passive HTTP fingerprint
    def _probe_base():
        try:
            r = requests.get(url, timeout=10, verify=False, allow_redirects=True,
                              headers={"User-Agent": "VulnusLab/1.0"})
            headers_lower = {k.lower(): str(v) for k, v in r.headers.items()}
            cookies_lower = {c.name.lower(): c.value for c in r.cookies}
            body = (r.text or "")[:50000]
            return headers_lower, cookies_lower, body
        except Exception:
            return {}, {}, ""

    (h, c, b), ip_results, active_result = await asyncio.gather(
        asyncio.to_thread(_probe_base),
        dns_resolve(host, "A"),
        _active_probe(None, url),
    )
    passive_matches = _match_signatures(h, c, b)
    if passive_matches:
        ctx.source(f"passive-sig ({len(_WAF_CDN_SIGS)} vendors)")

    # Source 2: IP range matching
    ip_match = None
    for ip in (ip_results or []):
        for vendor, patterns in _IP_RANGE_PATTERNS.items():
            if any(re.match(p, str(ip)) for p in patterns):
                ip_match = vendor
                break
        if ip_match: break
    if ip_match:
        ctx.source("ip-range-match")
        ctx.state["ip_range_match"] = ip_match
        # If passive sigs missed it, add via IP-range source
        if not any(v["vendor"] == ip_match for v in passive_matches):
            passive_matches.append({"vendor": ip_match, "category": "CDN+WAF",
                                      "source": "ip-range", "evidence": f"IPs in {ip_match} range"})

    # Source 3: Reverse DNS hint
    rdns_hint = None
    if ip_results:
        ptr_tasks = [dns_resolve(ip, "PTR") for ip in ip_results[:2]]
        ptr_results = await asyncio.gather(*ptr_tasks)
        for ptrs in ptr_results:
            for ptr in (ptrs or []):
                for vendor, patterns in _PTR_HINTS.items():
                    if any(re.search(p, str(ptr), re.I) for p in patterns):
                        rdns_hint = vendor
                        break
                if rdns_hint: break
            if rdns_hint: break
    if rdns_hint:
        ctx.source("reverse-dns-vendor-match")
        ctx.state["reverse_dns_hint"] = rdns_hint

    # Source 4: Active probe result
    waf_blocks, blocked_categories = active_result
    ctx.state["active_probe_blocked"] = waf_blocks
    ctx.state["attack_categories_blocked"] = blocked_categories
    if waf_blocks:
        ctx.source(f"active-probe ({len(blocked_categories)} categories blocked)")
    else:
        ctx.source("active-probe (no blocks)")

    # Aggregate detected vendors
    seen_vendors = set()
    deduped = []
    for v in passive_matches:
        key = v["vendor"]
        if key in seen_vendors: continue
        seen_vendors.add(key)
        deduped.append(v)
    ctx.state["vendors_detected"] = deduped
    ctx.state["cdn_present"] = any("CDN" in v.get("category", "") for v in deduped)
    ctx.state["waf_present"] = any("WAF" in v.get("category", "") for v in deduped)

    # Backwards-compat: top-level detected[] for existing PDF section
    ctx.state["detected"] = deduped


INTEL_FIELDS = [
    ("Vendors detected",      "vendors_summary"),
    ("CDN present",           "cdn_present"),
    ("WAF present",           "waf_present"),
    ("IP-range match",        "ip_range_match"),
    ("Reverse DNS hint",      "reverse_dns_hint"),
    ("Active probe blocking", "active_probe_summary"),
]


@router.post("/api/recon/waf_cdn")
async def recon_waf_cdn(req: ScanRequest, _=Depends(verify_scan_quota)):
    host = recon_host(req.target)

    async def gather_with_display(ctx):
        await gather(ctx)
        vd = ctx.state.get("vendors_detected") or []
        if vd:
            ctx.state["vendors_summary"] = ", ".join(
                f"{v['vendor']} ({v.get('category', '?')})" for v in vd[:5])
        cats = ctx.state.get("attack_categories_blocked") or []
        ap = ctx.state.get("active_probe_blocked")
        if ap is True:
            ctx.state["active_probe_summary"] = (
                f"YES — blocked {len(cats)} of {len(_ACTIVE_PROBES)} test patterns "
                f"({', '.join(cats)})")
        elif ap is False:
            ctx.state["active_probe_summary"] = (
                f"NO — all {len(_ACTIVE_PROBES)} test patterns passed through")

    return await run_scanner(
        host=host,
        tool="waf_cdn",
        gather_func=gather_with_display,
        finding_rules=WAF_CDN_FINDING_RULES,
        intel_fields=INTEL_FIELDS,
        flat_field_keys=["detected", "vendors_detected"],
    )


def register(app):
    app.include_router(router)
