"""msf_payload_generation_test - benign msfvenom payload generation probe
(playbook §3 Payload Modules, MITRE ATT&CK T1027.002 / T1059).

What it does:
  Runs `msfvenom -p windows/x64/exec CMD=calc.exe -f raw` on the
  scanner host to verify that:

    1. The msfvenom binary is installed.
    2. The customer's MSF install can generate payload shellcode at
       all (catches broken / outdated Ruby bundle, missing payload
       module trees, encoder DB corruption, etc.).
    3. The size of the produced shellcode matches what a current MSF
       build should emit (~272 bytes for x64/exec CMD=calc.exe in
       MSF 6.4.x).

  CMD=calc.exe is a deliberately benign payload (it pops the Windows
  calculator on detonation). The generated bytes are counted and
  hashed (SHA-256) for the customer's report but NEVER written to
  disk and never delivered to the target - this is a health check, not
  an attack.

Customer input via ScanRequest.options:
  - timeout_sec   wall-clock cap (default 60s)
"""
from __future__ import annotations
import asyncio
import hashlib
import os
import shutil
from typing import Optional

from fastapi import APIRouter, Depends
from pydantic import BaseModel

from tools._shared import ScanRequest, verify_scan_quota
from tools._framework import ScanContext, run_scanner
from tools._payloads.msf_payload_generation_test_findings import (
    MSF_PAYLOAD_GENERATION_TEST_FINDING_RULES,
)

router = APIRouter()
MSFVENOM_BIN = shutil.which("msfvenom")
DEFAULT_TIMEOUT = 60
HARD_MAX_TIMEOUT = 120
PAYLOAD_NAME = "windows/x64/exec"
BENIGN_CMD = "calc.exe"
# Expected size band for windows/x64/exec CMD=calc.exe in MSF 6.x.
# Below 32 bytes = generation failed; > 4 KB = something injected
# wrappers we didn't ask for.
EXPECTED_MIN = 32
EXPECTED_MAX = 4096


class MsfPayloadGenerationTestRequest(ScanRequest):
    options: Optional[dict] = None


async def gather(ctx: ScanContext):
    if not MSFVENOM_BIN:
        ctx.state["msf_payload_generation_test_binary_missing"] = True
        ctx.source("msfvenom missing")
        return

    opts = ctx.state.get("_options") or {}
    timeout = min(max(int(opts.get("timeout_sec") or DEFAULT_TIMEOUT), 15), HARD_MAX_TIMEOUT)

    cmd = [
        MSFVENOM_BIN,
        "-p", PAYLOAD_NAME,
        f"CMD={BENIGN_CMD}",
        "-f", "raw",
    ]

    try:
        proc = await asyncio.create_subprocess_exec(
            *cmd,
            stdout=asyncio.subprocess.PIPE,
            stderr=asyncio.subprocess.PIPE,
            env={**os.environ, "TERM": "dumb"},
        )
    except Exception as e:
        ctx.state["msf_payload_generation_test_error"] = f"spawn failed: {str(e)[:200]}"
        ctx.source("spawn error")
        return

    try:
        stdout_b, stderr_b = await asyncio.wait_for(
            proc.communicate(), timeout=timeout,
        )
    except asyncio.TimeoutError:
        try: proc.kill()
        except Exception: pass
        ctx.state["msf_payload_generation_test_error"] = f"msfvenom timeout after {timeout}s"
        ctx.source(f"timeout @ {timeout}s")
        return

    payload = stdout_b or b""
    stderr = (stderr_b or b"").decode("utf-8", errors="ignore")
    byte_count = len(payload)

    # Compute hash but discard the bytes (no file write).
    sha256 = hashlib.sha256(payload).hexdigest() if payload else ""

    ctx.state["msf_payload_generation_test_msfvenom_path"] = MSFVENOM_BIN
    ctx.state["msf_payload_generation_test_payload_name"] = PAYLOAD_NAME
    ctx.state["msf_payload_generation_test_benign_cmd"] = BENIGN_CMD
    ctx.state["msf_payload_generation_test_byte_count"] = byte_count
    ctx.state["msf_payload_generation_test_sha256"] = sha256
    ctx.state["msf_payload_generation_test_within_expected_band"] = (
        EXPECTED_MIN <= byte_count <= EXPECTED_MAX
    )
    if proc.returncode and proc.returncode != 0:
        ctx.state["msf_payload_generation_test_msfvenom_exit"] = proc.returncode
        ctx.state["msf_payload_generation_test_stderr_head"] = stderr[:400]
    if byte_count == 0:
        ctx.state["msf_payload_generation_test_no_payload_produced"] = True

    ctx.source(
        f"msfvenom -p {PAYLOAD_NAME} CMD={BENIGN_CMD} -f raw -> "
        f"{byte_count} byte(s), exit={proc.returncode}"
    )


INTEL_FIELDS = [
    ("msfvenom path",            "msf_payload_generation_test_msfvenom_path"),
    ("Payload module",           "msf_payload_generation_test_payload_name"),
    ("Benign command",           "msf_payload_generation_test_benign_cmd"),
    ("Bytes produced",           "msf_payload_generation_test_byte_count"),
    ("Payload SHA-256",          "msf_payload_generation_test_sha256"),
    ("Within expected band",     "msf_payload_generation_test_within_expected_band"),
]


@router.post("/api/metasploit/msf_payload_generation_test")
async def metasploit_msf_payload_generation_test(
    req: MsfPayloadGenerationTestRequest, _=Depends(verify_scan_quota),
):
    options = req.options or {}

    async def _gather_with_options(ctx: ScanContext):
        ctx.state["_options"] = options
        await gather(ctx)

    return await run_scanner(
        host=req.target or "scanner-host",
        tool="msf_payload_generation_test",
        gather_func=_gather_with_options,
        finding_rules=MSF_PAYLOAD_GENERATION_TEST_FINDING_RULES,
        intel_fields=INTEL_FIELDS,
        flat_field_keys=[],
    )


def register(app):
    app.include_router(router)
