#!/usr/bin/env python3
"""VL-FOUNDRY scaffolder — generates a new scanner with the 7-check skeleton.

Usage:
  python scripts/forge_scanner.py <module> <scanner_name> [--tier=<tier_dir>]

Examples:
  python scripts/forge_scanner.py webapp graphql_introspection --tier=tier11_logic
  python scripts/forge_scanner.py vuln new_cve

The scaffold ships with the 7 Definition-of-Done checks pre-wired:
  1. precheck_target via the module's safe_get / web_url helper
  2. uniform_shape via standard_response / vuln_response
  3. POSITIVE emit when target is clean
  4. severity / cvss / cwe / owasp fields filled (placeholders)
  5. remediation field
  6. evidence_marker field
  7. wall-clock timeout

The intent is that the builder fills in scan logic, not boilerplate.
After scaffolding, run:
  $ python scripts/score_module.py <module> --verbose
to confirm the new scanner inherits the module's quality bar.
"""
from __future__ import annotations
import argparse
import sys
from pathlib import Path

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except Exception:
        pass

ROOT = Path(__file__).resolve().parent.parent

# Per-module template — different modules use different framework helpers
TEMPLATES = {
    "vuln": '''"""{name} — VL-FOUNDRY scanner stub. Fill in scan logic.

Generated by scripts/forge_scanner.py. Wires up:
  • precheck_target reachability guard
  • vuln_response uniform shape
  • POSITIVE emit when clean
  • full 7-check DoD fields
"""
from __future__ import annotations
import asyncio

from tools.vuln._vuln_common import precheck_target, vuln_response


WALL_CLOCK_S = 60   # Layer 6: per-scanner timeout


async def run(target: str, **kw) -> dict:
    """Scan {target} for {name}. Returns vuln_response envelope."""
    reachable = await precheck_target(target)
    if not reachable:
        return vuln_response(
            tool="{name}",
            target=target,
            status="ERROR",
            error="target unreachable",
        )

    try:
        findings = await asyncio.wait_for(
            _scan(target, **kw),
            timeout=WALL_CLOCK_S,
        )
    except asyncio.TimeoutError:
        return vuln_response(
            tool="{name}",
            target=target,
            status="ERROR",
            error=f"timeout after {{WALL_CLOCK_S}}s",
        )

    if not findings:
        # POSITIVE emit — Layer 6 check #3
        findings = [{{
            "status": "POSITIVE",
            "severity": "POSITIVE",
            "title": "{name}: no issues detected",
            "remediation": "No action required",
            "evidence_marker": "scan completed cleanly",
        }}]

    return vuln_response(
        tool="{name}",
        target=target,
        status="VULNERABLE" if any(
            f.get("status") == "VULNERABLE" for f in findings
        ) else "CLEAN",
        findings=findings,
    )


async def _scan(target: str, **kw) -> list[dict]:
    """TODO: implement scan logic. Return list of finding dicts.

    Each VULNERABLE finding MUST include:
      status, severity, cvss, cwe, owasp, remediation, evidence_marker
    """
    return []


if __name__ == "__main__":
    import sys as _s
    print(asyncio.run(run(_s.argv[1] if len(_s.argv) > 1 else "example.com")))
''',
    "webapp": '''"""{name} — VL-FOUNDRY webapp scanner stub. Fill in scan logic."""
from __future__ import annotations
import asyncio

from tools.webapp._webapp_common import precheck_target, standard_response


WALL_CLOCK_S = 30   # Layer 6 — webapp SLO is tight


async def run(target: str, **kw) -> dict:
    reachable = await precheck_target(target)
    if not reachable:
        return standard_response(
            tool="{name}",
            target=target,
            status="ERROR",
            error="target unreachable",
        )

    try:
        findings = await asyncio.wait_for(
            _scan(target, **kw),
            timeout=WALL_CLOCK_S,
        )
    except asyncio.TimeoutError:
        return standard_response(
            tool="{name}",
            target=target,
            status="ERROR",
            error=f"timeout after {{WALL_CLOCK_S}}s",
        )

    if not findings:
        findings = [{{
            "status": "POSITIVE",
            "severity": "POSITIVE",
            "title": "{name}: no issues detected",
            "remediation": "No action required",
            "evidence_marker": "scan completed cleanly",
        }}]

    return standard_response(
        tool="{name}",
        target=target,
        status="VULNERABLE" if any(
            f.get("status") == "VULNERABLE" for f in findings
        ) else "CLEAN",
        findings=findings,
    )


async def _scan(target: str, **kw) -> list[dict]:
    """TODO: implement webapp scan logic.

    Each VULNERABLE finding MUST include:
      status, severity, cvss, cwe, owasp, remediation, evidence_marker
    """
    return []
''',
    "recon": '''"""{name} — VL-FOUNDRY recon scanner stub. Fill in scan logic."""
from __future__ import annotations

from tools._framework.scanner import ScanContext, run_scanner


FINDING_RULES = {{
    # TODO: map regex / predicate → (severity, cwe, owasp, remediation)
    # Example:
    # "AWS_KEY":  ("HIGH", "CWE-200", "A05:2021",
    #              "Rotate and scope to least-privilege"),
}}


def _scan(ctx: ScanContext) -> None:
    """TODO: implement scan logic.

    Use ctx.source(...) to record evidence_marker. Use ctx.emit(...) for
    findings. The run_scanner wrapper supplies precheck + uniform shape +
    timeout enforcement.
    """
    return


async def run(target: str, **kw) -> dict:
    return await run_scanner(
        tool="{name}",
        target=target,
        finding_rules=FINDING_RULES,
        scan_fn=_scan,
        timeout=60,
        **kw,
    )
''',
}


def scaffold(module: str, name: str, tier: str | None) -> Path:
    if module not in TEMPLATES:
        sys.exit(f"unsupported module: {module} (have: {sorted(TEMPLATES)})")

    base = ROOT / "tools" / module
    if tier:
        base = base / tier
    base.mkdir(parents=True, exist_ok=True)

    out = base / f"{name}.py"
    if out.exists():
        sys.exit(f"file already exists: {out}")

    out.write_text(TEMPLATES[module].format(name=name), encoding="utf-8")
    return out


def main():
    ap = argparse.ArgumentParser(description="Scaffold a new VL-FOUNDRY scanner")
    ap.add_argument("module", help="Module: vuln|webapp|recon")
    ap.add_argument("name", help="Scanner name (snake_case, no .py)")
    ap.add_argument("--tier", default=None,
                    help="Tier subdirectory (e.g. tier11_logic)")
    args = ap.parse_args()

    path = scaffold(args.module, args.name, args.tier)
    rel = path.relative_to(ROOT)
    print(f"✓ created {rel}")
    print(f"\nNext steps:")
    print(f"  1. Fill in _scan() with real scan logic")
    print(f"  2. Add to endpoints/{args.module}_orchestrator.py "
          f"<MODULE>_TOOLS_BY_TIER")
    print(f"  3. Add to src/App.js <MODULE>_PHASES")
    print(f"  4. python scripts/score_module.py {args.module} --verbose")


if __name__ == "__main__":
    main()
