"""AI-CURATED red-team knowledge base — build script.

This is the curation SOURCE. Running it emits the shipped data files:
  red_team_ops/_curated/techniques.json   — ATT&CK Enterprise technique library
  red_team_ops/_curated/scenarios.json    — adversary-group emulation playbooks

Curation rules (do NOT weaken):
- Every entry maps to a real MITRE ATT&CK (sub)technique id.
- `emulation` is a NON-DESTRUCTIVE step (verify / read-only / benign-atomic /
  plan-and-log). `detection` is blue-team guidance.
- Genuinely destructive / irreversible / real-credential / real-exfil / DoS
  techniques carry `risk` tags that match red_team_ops.safety.FORBIDDEN, so the
  safety contract BLOCKS them (recorded as detection/resilience objectives,
  never executed).
- `atomic_safe=True` only for vetted benign Atomic-Red-Team-style tests.

Run:  python red_team_ops/_curated/_build.py
"""
from __future__ import annotations

import json
import os


def T(tid, name, tactic, desc, emu, det, risk=(), atomic=False, platforms=("any",)):
    return {"id": tid, "name": name, "tactic": tactic, "desc": desc,
            "emulation": emu, "detection": det, "risk": list(risk),
            "atomic_safe": atomic, "platforms": list(platforms)}


# Forbidden-category tags (must match safety.FORBIDDEN keys)
DESTROY = "data_destruction"
DOS = "denial_of_service"
EXFIL = "real_exfiltration"
SPREAD = "out_of_scope_spread"
CREDS = "credential_harvest_live"
PERSIST = "destructive_persistence"

TECHNIQUES = [
    # ── Reconnaissance ──────────────────────────────────────────────────────
    T("T1595", "Active Scanning", "reconnaissance",
      "Scan in-scope hosts for open ports/services.",
      "Enumerate authorized targets (ports/services/banners) — read-only.",
      "IDS port-scan signatures; spikes in connection attempts.", atomic=True, platforms=("network",)),
    T("T1595.001", "Scanning IP Blocks", "reconnaissance",
      "Sweep authorized IP ranges for live hosts.",
      "Live-host sweep of authorized CIDRs — read-only.",
      "Network-flow anomalies, ICMP/SYN sweeps.", atomic=True, platforms=("network",)),
    T("T1595.002", "Vulnerability Scanning", "reconnaissance",
      "Scan in-scope assets for known vulns.",
      "Non-exploitative vuln scan of authorized assets.",
      "Scanner user-agents, version-probe bursts.", atomic=True, platforms=("network", "web")),
    T("T1592", "Gather Victim Host Information", "reconnaissance",
      "Profile OS/software of in-scope hosts.",
      "Fingerprint OS/software from authorized banners/headers.",
      "Hard to detect externally.", atomic=True, platforms=("network",)),
    T("T1589", "Gather Victim Identity Information", "reconnaissance",
      "Collect emails/usernames for the in-scope org.",
      "OSINT username/email enumeration on authorized domains.",
      "Monitor for credential-stuffing follow-on.", atomic=True, platforms=("osint",)),
    T("T1590", "Gather Victim Network Information", "reconnaissance",
      "Map the in-scope org's network footprint.",
      "Passive ASN/DNS/subdomain mapping of authorized assets.",
      "Passive recon is hard to detect.", atomic=True, platforms=("osint",)),
    T("T1591", "Gather Victim Org Information", "reconnaissance",
      "Collect org/role/tech-stack intel.",
      "OSINT org/role/tech-stack collection for in-scope org.",
      "Not directly detectable.", atomic=True, platforms=("osint",)),
    T("T1598", "Phishing for Information", "reconnaissance",
      "Elicit info via pretext messages.",
      "Authorized pretext info-gathering to consented contacts only.",
      "User-report rate, suspicious sender domains.", platforms=("email",)),
    T("T1596", "Search Open Technical Databases", "reconnaissance",
      "Query Shodan/Censys/CT logs.",
      "Query open tech databases for in-scope assets — read-only.",
      "Not detectable on target.", atomic=True, platforms=("osint",)),
    T("T1593", "Search Open Websites/Domains", "reconnaissance",
      "Review public web/social footprint.",
      "Review the authorized org's public web/social footprint.",
      "Not detectable.", atomic=True, platforms=("osint",)),
    T("T1594", "Search Victim-Owned Websites", "reconnaissance",
      "Crawl the org's own sites for data.",
      "Crawl authorized public site for metadata/paths — read-only.",
      "Spider user-agent, crawl-rate spikes.", atomic=True, platforms=("web",)),

    # ── Resource Development (off-target; planning only) ─────────────────────
    T("T1583", "Acquire Infrastructure", "resource_development",
      "Stand up attacker infrastructure.",
      "Planning-only: document required infra; no target action.",
      "Threat-intel domain/IP monitoring.", platforms=("osint",)),
    T("T1586", "Compromise Accounts", "resource_development",
      "Obtain accounts for operations.",
      "Planning-only: note credential sources; no real compromise.",
      "N/A (off-target).", platforms=("osint",)),
    T("T1587", "Develop Capabilities", "resource_development",
      "Build tooling/malware.",
      "Planning-only: list TTPs/tooling to be used.",
      "N/A.", platforms=("osint",)),
    T("T1588", "Obtain Capabilities", "resource_development",
      "Acquire tools/exploits.",
      "Planning-only: acquire benign test tooling.",
      "N/A.", platforms=("osint",)),
    T("T1608", "Stage Capabilities", "resource_development",
      "Stage payloads on infra.",
      "Stage benign payloads on authorized infra only.",
      "Threat-intel staging detection.", platforms=("osint",)),

    # ── Initial Access ──────────────────────────────────────────────────────
    T("T1190", "Exploit Public-Facing Application", "initial_access",
      "Exploit an internet-facing app for a foothold.",
      "Non-destructively verify an in-scope app is vulnerable; do NOT drop a shell.",
      "WAF alerts, app error spikes, unexpected child processes.", platforms=("web",)),
    T("T1133", "External Remote Services", "initial_access",
      "Access exposed VPN/RDP/SSH.",
      "Confirm exposed remote services and test provided test creds.",
      "Geo-anomalous logins, new-device auth.", atomic=True, platforms=("network",)),
    T("T1566", "Phishing", "initial_access",
      "Send a phishing lure to authorized test users.",
      "Authorized simulated-phishing to consented test recipients only.",
      "Mail gateway, user-report rate, link-click telemetry.", atomic=True, platforms=("email",)),
    T("T1566.001", "Spearphishing Attachment", "initial_access",
      "Lure with a malicious attachment.",
      "Send a tracked benign attachment to consented users.",
      "Attachment sandboxing, macro-exec alerts.", atomic=True, platforms=("email",)),
    T("T1566.002", "Spearphishing Link", "initial_access",
      "Lure with a malicious link.",
      "Send a tracked benign link to consented users.",
      "URL-rewrite/click telemetry, proxy logs.", atomic=True, platforms=("email",)),
    T("T1078", "Valid Accounts", "initial_access",
      "Use legitimate credentials.",
      "Authenticate with provided test credentials to confirm access paths.",
      "Impossible-travel, new-device, off-hours logins.", atomic=True, platforms=("identity",)),
    T("T1078.004", "Cloud Accounts", "initial_access",
      "Use valid cloud credentials.",
      "Use provided cloud test creds to confirm console/API access.",
      "CloudTrail anomalous IAM use, new-region logins.", atomic=True, platforms=("cloud",)),
    T("T1199", "Trusted Relationship", "initial_access",
      "Abuse third-party/B2B trust.",
      "Map authorized third-party/B2B access paths — read-only.",
      "Unusual partner-network access.", platforms=("network",)),
    T("T1195", "Supply Chain Compromise", "initial_access",
      "Compromise via a dependency/build chain.",
      "Audit in-scope dependency/build trust — read-only; do not tamper.",
      "Build-integrity/signing verification gaps.", platforms=("supply_chain",)),
    T("T1189", "Drive-by Compromise", "initial_access",
      "Compromise via a watering-hole site.",
      "Verify a watering-hole vector exists; do not weaponize.",
      "Browser-exploit telemetry, anomalous redirects.", platforms=("web",)),
    T("T1200", "Hardware Additions", "initial_access",
      "Introduce rogue hardware.",
      "Planning-only: note physical/HW vector; no deployment.",
      "NAC, rogue-device detection.", platforms=("physical",)),

    # ── Execution ───────────────────────────────────────────────────────────
    T("T1059", "Command and Scripting Interpreter", "execution",
      "Run commands via an interpreter.",
      "Run a benign command via an interpreter on an authorized host.",
      "Process-creation + command-line logging.", atomic=True),
    T("T1059.001", "PowerShell", "execution",
      "Run commands via PowerShell.",
      "Atomic benign PowerShell (whoami) on an authorized host.",
      "Script-block logging, AMSI, parent-child anomalies.", atomic=True, platforms=("windows",)),
    T("T1059.003", "Windows Command Shell", "execution",
      "Run commands via cmd.exe.",
      "Benign cmd.exe (whoami/ipconfig) on an authorized host.",
      "cmd.exe spawned by Office/odd parents.", atomic=True, platforms=("windows",)),
    T("T1059.004", "Unix Shell", "execution",
      "Run shell commands on Unix.",
      "Benign id/uname on an authorized host.",
      "auditd/EDR process telemetry, anomalous shells.", atomic=True, platforms=("linux",)),
    T("T1059.005", "Visual Basic", "execution",
      "Execute VBScript/VBA.",
      "Detonate a benign VBScript/macro in a controlled sandbox.",
      "wscript/cscript exec, macro-security logs.", atomic=True, platforms=("windows",)),
    T("T1059.006", "Python", "execution",
      "Execute Python.",
      "Benign Python one-liner on an authorized host.",
      "python spawning network/child processes.", atomic=True),
    T("T1059.007", "JavaScript", "execution",
      "Execute JScript/Node.",
      "Benign JScript/Node test on an authorized host.",
      "wscript/node anomalous exec.", atomic=True),
    T("T1204", "User Execution", "execution",
      "Rely on a user running content.",
      "Track whether consented users run a benign tracked file/link.",
      "User-report rate, exec-from-download telemetry.", atomic=True, platforms=("email",)),
    T("T1204.002", "Malicious File", "execution",
      "User opens a malicious file.",
      "Consented user opens a tracked benign document; log only.",
      "Office-spawns-shell, mark-of-the-web bypass.", atomic=True, platforms=("windows",)),
    T("T1047", "Windows Management Instrumentation", "execution",
      "Execute via WMI.",
      "Benign WMI query (Win32_Process) on an authorized host.",
      "wmic/WMI-Activity logs, remote WMI.", atomic=True, platforms=("windows",)),
    T("T1053", "Scheduled Task/Job", "execution",
      "Execute/persist via scheduling.",
      "Create a clearly-tagged benign job, then REMOVE it in-window.",
      "Task-creation events (4698), cron changes.", atomic=True),
    T("T1053.005", "Scheduled Task", "execution",
      "Execute/persist via Windows Scheduled Task.",
      "Create a tagged benign task, then remove it.",
      "4698/4702 task events, schtasks telemetry.", atomic=True, platforms=("windows",)),
    T("T1569.002", "Service Execution", "execution",
      "Execute via a Windows service.",
      "Start a benign tagged service, then remove it.",
      "7045 service-install, PsExec artifacts.", atomic=True, platforms=("windows",)),
    T("T1106", "Native API", "execution",
      "Execute via OS native API.",
      "Benign API-call test (CreateProcess) on an authorized host.",
      "EDR API telemetry, unbacked memory exec.", platforms=("windows",)),
    T("T1129", "Shared Modules", "execution",
      "Execute via loaded modules/DLLs.",
      "Load a benign signed DLL on an authorized host.",
      "Image-load telemetry, unsigned DLL loads.", platforms=("windows",)),

    # ── Persistence ─────────────────────────────────────────────────────────
    T("T1098", "Account Manipulation", "persistence",
      "Add/modify accounts to keep access.",
      "Emulate-only: log the technique; do not modify real accounts.",
      "Directory-change auditing, new privileged members.",
      risk=(PERSIST,), platforms=("identity",)),
    T("T1136", "Create Account", "persistence",
      "Create an account for persistence.",
      "BLOCKED: do not create real persistent accounts; objective only.",
      "4720 account-creation, new local/domain users.",
      risk=(PERSIST,), platforms=("identity",)),
    T("T1136.001", "Local Account", "persistence",
      "Create a local account.",
      "BLOCKED: do not create real local accounts; objective only.",
      "4720, net user adds.", risk=(PERSIST,), platforms=("windows", "linux")),
    T("T1547.001", "Registry Run Keys / Startup Folder", "persistence",
      "Persist via run keys / startup.",
      "Add a tagged benign run-key, then remove it.",
      "Run-key writes (Sysmon 13), startup-folder changes.", atomic=True, platforms=("windows",)),
    T("T1543.003", "Windows Service", "persistence",
      "Persist via a Windows service.",
      "Install a tagged benign service, then remove it.",
      "7045 service-install, ImagePath anomalies.", atomic=True, platforms=("windows",)),
    T("T1505.003", "Web Shell", "persistence",
      "Plant a web shell backdoor.",
      "BLOCKED: verify the upload vector only; do not deploy a live shell.",
      "New executables in webroot, anomalous web-process children.",
      risk=(PERSIST,), platforms=("web",)),
    T("T1546.003", "WMI Event Subscription", "persistence",
      "Persist via WMI event subscription.",
      "Register a tagged benign WMI subscription, then remove it.",
      "WMI-Activity __EventFilter/Consumer creation.", platforms=("windows",)),
    T("T1574", "Hijack Execution Flow", "persistence",
      "Hijack DLL search order / paths.",
      "Identify DLL-search-order/path-hijack vectors — read-only.",
      "Unsigned DLLs from writable paths.", platforms=("windows",)),
    T("T1037", "Boot or Logon Initialization Scripts", "persistence",
      "Persist via logon scripts.",
      "Add a tagged benign logon script, then remove it.",
      "Logon-script registry/GPO changes.", platforms=("windows", "linux")),

    # ── Privilege Escalation ────────────────────────────────────────────────
    T("T1068", "Exploitation for Privilege Escalation", "privilege_escalation",
      "Exploit a local vuln to elevate.",
      "Identify a local privesc vector (version/config); do not weaponize.",
      "EDR exploit-guard, unexpected SYSTEM/root processes.", platforms=("windows", "linux")),
    T("T1548.002", "Bypass User Account Control", "privilege_escalation",
      "Bypass UAC to elevate.",
      "Benign atomic UAC-bypass test on an authorized host.",
      "fodhelper/eventvwr auto-elevate anomalies.", atomic=True, platforms=("windows",)),
    T("T1548.003", "Sudo and Sudo Caching", "privilege_escalation",
      "Abuse sudo misconfig to elevate.",
      "Read-only sudo -l / sudoers review on an authorized host.",
      "sudo logs, auth.log anomalies.", atomic=True, platforms=("linux",)),
    T("T1134", "Access Token Manipulation", "privilege_escalation",
      "Manipulate tokens to elevate.",
      "Benign token-impersonation test (whoami /priv).",
      "Token-manipulation EDR telemetry.", platforms=("windows",)),
    T("T1055", "Process Injection", "privilege_escalation",
      "Inject code into another process.",
      "Benign atomic injection test into a sacrificial process.",
      "CreateRemoteThread, unbacked executable memory.", platforms=("windows", "linux")),
    T("T1484.001", "Group Policy Modification", "privilege_escalation",
      "Abuse GPO to escalate.",
      "Read-only GPO review; do not modify policy.",
      "GPO change auditing (5136).", platforms=("windows",)),

    # ── Defense Evasion ─────────────────────────────────────────────────────
    T("T1562.001", "Impair Defenses: Disable or Modify Tools", "defense_evasion",
      "Disable AV/EDR/logging.",
      "Emulate-only: log the intent; do NOT disable security controls.",
      "Service-stop events, EDR self-protection alerts.", platforms=("windows", "linux")),
    T("T1070.004", "Indicator Removal: File Deletion", "defense_evasion",
      "Delete artifacts to cover tracks.",
      "BLOCKED — destructive. Recorded as a detection objective.",
      "File-delete auditing, gaps in artifact continuity.",
      risk=(DESTROY,), platforms=("windows", "linux")),
    T("T1070.001", "Clear Windows Event Logs", "defense_evasion",
      "Wipe event logs.",
      "BLOCKED — destructive. Detection objective only.",
      "1102 log-cleared, gaps in event sequence.",
      risk=(DESTROY,), platforms=("windows",)),
    T("T1027", "Obfuscated Files or Information", "defense_evasion",
      "Obfuscate payloads to evade.",
      "Detonate a benign obfuscated sample for detection testing.",
      "Entropy analysis, AMSI, packer signatures.", atomic=True),
    T("T1140", "Deobfuscate/Decode Files", "defense_evasion",
      "Decode payloads on host.",
      "Benign decode test (certutil) on an authorized host.",
      "certutil/base64 decode telemetry.", atomic=True, platforms=("windows",)),
    T("T1112", "Modify Registry", "defense_evasion",
      "Tamper with the registry.",
      "Write/read a tagged benign registry value, then remove it.",
      "Registry-modification auditing (Sysmon 13).", atomic=True, platforms=("windows",)),
    T("T1036", "Masquerading", "defense_evasion",
      "Disguise tooling as legit.",
      "Run a benign binary renamed to mimic a system process.",
      "Path/signature mismatch, name vs hash.", atomic=True),
    T("T1218", "System Binary Proxy Execution", "defense_evasion",
      "Proxy execution via LOLBins.",
      "Benign LOLBin test (rundll32/mshta no-op).",
      "LOLBin command-line anomalies.", atomic=True, platforms=("windows",)),
    T("T1497", "Virtualization/Sandbox Evasion", "defense_evasion",
      "Evade sandboxes/VMs.",
      "Benign sandbox-check test; log only.",
      "Anti-VM API calls, timing checks.", atomic=True),
    T("T1553", "Subvert Trust Controls", "defense_evasion",
      "Abuse code-signing/cert trust.",
      "Identify code-signing/cert-trust gaps — read-only.",
      "Untrusted-signer execution, cert anomalies."),
    T("T1620", "Reflective Code Loading", "defense_evasion",
      "Load code reflectively in memory.",
      "Benign reflective-load test for detection testing.",
      "Unbacked/memory-only module loads."),

    # ── Credential Access ───────────────────────────────────────────────────
    T("T1110", "Brute Force", "credential_access",
      "Guess credentials.",
      "Rate-limited spray against authorized auth endpoints with a test wordlist.",
      "Lockout spikes, failed-auth bursts (4625).", atomic=True, platforms=("identity",)),
    T("T1110.003", "Password Spraying", "credential_access",
      "Spray one password across many accounts.",
      "Single-password spray across authorized accounts, rate-limited.",
      "Many accounts, one password; 4625 patterns.", atomic=True, platforms=("identity",)),
    T("T1110.004", "Credential Stuffing", "credential_access",
      "Replay breached cred pairs.",
      "Replay test credential pairs against an authorized login (consented).",
      "High-volume distinct-credential login attempts.", atomic=True, platforms=("identity",)),
    T("T1003.001", "OS Credential Dumping: LSASS", "credential_access",
      "Dump LSASS for credentials.",
      "BLOCKED: log technique; do not capture real production creds.",
      "LSASS access by non-system processes (EDR).",
      risk=(CREDS,), platforms=("windows",)),
    T("T1003.002", "Security Account Manager", "credential_access",
      "Dump SAM hashes.",
      "BLOCKED: do not dump real SAM hashes; objective only.",
      "SAM/registry-hive access, reg save HKLM\\SAM.",
      risk=(CREDS,), platforms=("windows",)),
    T("T1003.003", "NTDS", "credential_access",
      "Extract the AD NTDS.dit database.",
      "BLOCKED: do not extract real NTDS.dit; objective only.",
      "ntdsutil/VSS NTDS access, 4662 DC reads.",
      risk=(CREDS,), platforms=("windows",)),
    T("T1558.003", "Kerberoasting", "credential_access",
      "Request service tickets to crack offline.",
      "Request SPNs for authorized AD; mark crackable; do not reuse real creds.",
      "4769 RC4 ticket requests, abnormal SPN queries.", platforms=("windows",)),
    T("T1558.001", "Golden Ticket", "credential_access",
      "Forge Kerberos TGTs.",
      "BLOCKED: do not forge real TGTs; resilience objective only.",
      "Anomalous TGT lifetime, krbtgt usage.",
      risk=(CREDS,), platforms=("windows",)),
    T("T1552", "Unsecured Credentials", "credential_access",
      "Find exposed credentials.",
      "Read-only search for exposed secrets in authorized scope; do not reuse.",
      "Secret-scanning, access to credential files.", atomic=True),
    T("T1552.001", "Credentials In Files", "credential_access",
      "Find credentials in files.",
      "Locate credential files (report paths only); do not exfil/reuse.",
      "Mass reads of config/.env/key files.", atomic=True),
    T("T1555", "Credentials from Password Stores", "credential_access",
      "Extract creds from browsers/keystores.",
      "BLOCKED: do not extract real browser/keystore creds; objective only.",
      "Browser-credential-store access by non-browser process.",
      risk=(CREDS,)),
    T("T1056.001", "Keylogging", "credential_access",
      "Capture keystrokes.",
      "BLOCKED: do not capture real keystrokes; objective only.",
      "Hook installation, keylogger EDR signatures.",
      risk=(CREDS,)),
    T("T1187", "Forced Authentication", "credential_access",
      "Coerce auth to capture hashes.",
      "BLOCKED: do not capture real NetNTLM hashes; objective only.",
      "Outbound SMB/WebDAV to attacker host, responder sigs.",
      risk=(CREDS,), platforms=("windows",)),
    T("T1557", "Adversary-in-the-Middle", "credential_access",
      "Intercept traffic/credentials.",
      "BLOCKED: do not intercept real credentials/traffic; objective only.",
      "ARP/LLMNR/NBT-NS poisoning, rogue gateway.",
      risk=(CREDS,), platforms=("network",)),

    # ── Discovery ───────────────────────────────────────────────────────────
    T("T1046", "Network Service Discovery", "discovery",
      "Enumerate services on reachable hosts.",
      "Read-only service scan of in-scope hosts.",
      "Internal scan signatures, east-west spikes.", atomic=True, platforms=("network",)),
    T("T1087", "Account Discovery", "discovery",
      "Enumerate accounts/groups.",
      "Read-only directory/IAM account enumeration on authorized scope.",
      "LDAP query spikes, recon-tool signatures.", atomic=True, platforms=("identity",)),
    T("T1087.002", "Account Discovery: Domain Account", "discovery",
      "Enumerate domain accounts/groups.",
      "Read-only domain account/group enumeration (BloodHound collector).",
      "SharpHound LDAP patterns, 4661 access.", atomic=True, platforms=("windows",)),
    T("T1018", "Remote System Discovery", "discovery",
      "Enumerate reachable hosts.",
      "Enumerate reachable in-scope hosts — read-only.",
      "net view / ping sweeps, ARP scans.", atomic=True, platforms=("network",)),
    T("T1082", "System Information Discovery", "discovery",
      "Profile the host.",
      "Benign systeminfo/uname on an authorized host.",
      "systeminfo/host-recon command telemetry.", atomic=True),
    T("T1083", "File and Directory Discovery", "discovery",
      "Enumerate files/dirs.",
      "Read-only directory listing on an authorized host.",
      "Recursive dir enumeration, mass stat.", atomic=True),
    T("T1057", "Process Discovery", "discovery",
      "Enumerate processes.",
      "Benign tasklist/ps on an authorized host.",
      "Process-enumeration telemetry.", atomic=True),
    T("T1016", "System Network Configuration Discovery", "discovery",
      "Read network config.",
      "Benign ipconfig/ifconfig/route on an authorized host.",
      "Network-config recon commands.", atomic=True),
    T("T1049", "System Network Connections Discovery", "discovery",
      "List active connections.",
      "Benign netstat on an authorized host.",
      "netstat/connection-enumeration telemetry.", atomic=True),
    T("T1069", "Permission Groups Discovery", "discovery",
      "Enumerate groups/roles.",
      "Read-only group/role enumeration on authorized scope.",
      "net group / whoami /groups telemetry.", atomic=True),
    T("T1482", "Domain Trust Discovery", "discovery",
      "Map domain trusts.",
      "Read-only domain-trust enumeration.",
      "nltest/LDAP trust queries.", atomic=True, platforms=("windows",)),
    T("T1135", "Network Share Discovery", "discovery",
      "Enumerate shares.",
      "Read-only share enumeration on authorized hosts.",
      "net view, SMB share-enum bursts.", atomic=True, platforms=("windows",)),
    T("T1201", "Password Policy Discovery", "discovery",
      "Read the password policy.",
      "Read-only password-policy query on authorized scope.",
      "net accounts / LDAP policy reads.", atomic=True),
    T("T1033", "System Owner/User Discovery", "discovery",
      "Identify the logged-in user.",
      "Benign whoami on an authorized host.",
      "whoami/quser telemetry.", atomic=True),
    T("T1526", "Cloud Service Discovery", "discovery",
      "Enumerate cloud services.",
      "Read-only enumeration of authorized cloud services/APIs.",
      "CloudTrail describe/list bursts.", atomic=True, platforms=("cloud",)),

    # ── Lateral Movement ────────────────────────────────────────────────────
    T("T1021", "Remote Services", "lateral_movement",
      "Move laterally via remote services.",
      "Confirm remote-service reachability/auth on in-scope hosts only.",
      "Anomalous remote-logon source/dest pairs.", atomic=True, platforms=("network",)),
    T("T1021.001", "Remote Services: RDP", "lateral_movement",
      "Move laterally via RDP.",
      "Confirm RDP reachability/auth on in-scope hosts only.",
      "4624 type-10 logons, unusual RDP pairs.", atomic=True, platforms=("windows",)),
    T("T1021.002", "SMB / Windows Admin Shares", "lateral_movement",
      "Move laterally via SMB admin shares.",
      "Confirm ADMIN$/C$ access with provided creds on an in-scope host.",
      "5140 share access, PsExec/SMB lateral signatures.", atomic=True, platforms=("windows",)),
    T("T1021.004", "Remote Services: SSH", "lateral_movement",
      "Move laterally via SSH.",
      "Confirm SSH reachability/auth on in-scope hosts.",
      "Anomalous SSH source IPs, auth.log spikes.", atomic=True, platforms=("linux",)),
    T("T1021.006", "Windows Remote Management", "lateral_movement",
      "Move laterally via WinRM.",
      "Confirm WinRM reachability/auth on in-scope hosts.",
      "WinRM/WSMan logons, 4624 + 5985 traffic.", atomic=True, platforms=("windows",)),
    T("T1550.002", "Use Alternate Auth Material: Pass the Hash", "lateral_movement",
      "Authenticate with a stolen NTLM hash.",
      "BLOCKED: do not reuse real NTLM hashes; objective only.",
      "NTLM logons without preceding interactive auth.",
      risk=(CREDS,), platforms=("windows",)),
    T("T1550.003", "Use Alternate Auth Material: Pass the Ticket", "lateral_movement",
      "Authenticate with a stolen Kerberos ticket.",
      "BLOCKED: do not reuse real Kerberos tickets; objective only.",
      "Anomalous ticket use, mismatched TGT/TGS.",
      risk=(CREDS,), platforms=("windows",)),
    T("T1570", "Lateral Tool Transfer", "lateral_movement",
      "Move tools between hosts.",
      "Transfer a benign tagged file to an in-scope host.",
      "SMB/HTTP tool-drop, new exe on host.", atomic=True),
    T("T1563", "Remote Service Session Hijacking", "lateral_movement",
      "Hijack an existing session.",
      "Identify hijackable sessions — read-only; do not hijack.",
      "Session-reconnect anomalies, tscon use.", platforms=("windows",)),
    T("T1080", "Taint Shared Content", "lateral_movement",
      "Plant malicious content on shares.",
      "BLOCKED: could spread out of scope; objective only.",
      "Modified files on shares, write bursts.",
      risk=(SPREAD,)),

    # ── Collection ──────────────────────────────────────────────────────────
    T("T1005", "Data from Local System", "collection",
      "Collect data from the host.",
      "Identify (do not copy) sensitive-data locations on authorized hosts.",
      "Mass file reads, staging-dir creation."),
    T("T1039", "Data from Network Shared Drive", "collection",
      "Collect data from shares.",
      "Identify sensitive shares — read-only; do not copy real data.",
      "Mass share reads, large SMB pulls."),
    T("T1114", "Email Collection", "collection",
      "Collect data from mailboxes.",
      "Confirm mailbox access path with provided creds; do not read real PII.",
      "Mass mailbox access, EWS/eDiscovery bursts.", platforms=("email",)),
    T("T1113", "Screen Capture", "collection",
      "Capture the screen.",
      "Take a single benign screenshot on an authorized host.",
      "Screen-capture API telemetry.", atomic=True),
    T("T1074", "Data Staged", "collection",
      "Stage data for exfil.",
      "Create a benign canary staging archive; do not stage real data.",
      "Staging-dir creation, large temp archives.", atomic=True),
    T("T1560", "Archive Collected Data", "collection",
      "Compress/encrypt collected data.",
      "Archive benign canary data (zip/rar) on an authorized host.",
      "rar/7z/zip of large data, password-protected archives.", atomic=True),
    T("T1119", "Automated Collection", "collection",
      "Auto-collect data at scale.",
      "Run a benign canary collection script; do not gather real data.",
      "Scripted mass-file access patterns."),
    T("T1530", "Data from Cloud Storage", "collection",
      "Collect data from cloud storage.",
      "Identify accessible buckets/objects — read-only; do not exfil real data.",
      "S3/GCS list+get bursts, public-bucket access.", atomic=True, platforms=("cloud",)),

    # ── Command and Control ─────────────────────────────────────────────────
    T("T1071", "Application Layer Protocol", "command_and_control",
      "C2 over a standard protocol.",
      "Benign beacon over a standard protocol to an authorized listener.",
      "Beacon jitter, rare-domain traffic, JA3 anomalies.", atomic=True, platforms=("network",)),
    T("T1071.001", "Application Layer Protocol: Web", "command_and_control",
      "C2 over HTTP(S).",
      "Benign HTTP(S) beacon to an authorized listener for detection testing.",
      "Beaconing, rare-domain TLS, JA3/JA4 anomalies.", atomic=True, platforms=("network",)),
    T("T1071.004", "Application Layer Protocol: DNS", "command_and_control",
      "C2 over DNS.",
      "Benign DNS-beacon pattern to an authorized resolver/listener.",
      "High-entropy subdomains, TXT-record bursts.", atomic=True, platforms=("network",)),
    T("T1573", "Encrypted Channel", "command_and_control",
      "Encrypt the C2 channel.",
      "Benign TLS-encrypted beacon to an authorized listener.",
      "Self-signed/rare-CA TLS, JA3 anomalies.", atomic=True, platforms=("network",)),
    T("T1090", "Proxy", "command_and_control",
      "Relay C2 through a proxy.",
      "Route benign test traffic through an authorized proxy/relay.",
      "Multi-hop traffic, unexpected proxy chains.", atomic=True, platforms=("network",)),
    T("T1572", "Protocol Tunneling", "command_and_control",
      "Tunnel C2 inside another protocol.",
      "Benign tunnel (DNS/ICMP/HTTP) to an authorized listener.",
      "Tunneling signatures, anomalous protocol payloads.", atomic=True, platforms=("network",)),
    T("T1105", "Ingress Tool Transfer", "command_and_control",
      "Pull tools onto the host.",
      "Download a benign tagged tool to an authorized host.",
      "certutil/curl/bitsadmin downloads, new exe.", atomic=True),
    T("T1095", "Non-Application Layer Protocol", "command_and_control",
      "C2 over raw TCP/ICMP.",
      "Benign raw-TCP/ICMP beacon to an authorized listener.",
      "Non-standard-port beacons, ICMP payloads.", atomic=True, platforms=("network",)),
    T("T1219", "Remote Access Software", "command_and_control",
      "Abuse RMM tools for access.",
      "Confirm presence/use of RMM tools — read-only.",
      "AnyDesk/TeamViewer/RMM execution telemetry.", atomic=True),
    T("T1102", "Web Service", "command_and_control",
      "C2 via a legitimate web service.",
      "Benign C2-over-web-service test (paste/cloud) to an authorized listener.",
      "Traffic to cloud/paste services, rare-domain APIs.", platforms=("network",)),

    # ── Exfiltration (real exfil always blocked) ────────────────────────────
    T("T1041", "Exfiltration Over C2 Channel", "exfiltration",
      "Exfil over the C2 channel.",
      "BLOCKED: emulate with benign canary data only; never real data.",
      "Large outbound over C2, DLP triggers.",
      risk=(EXFIL,), platforms=("network",)),
    T("T1048", "Exfiltration Over Alternative Protocol", "exfiltration",
      "Exfil over DNS/FTP/ICMP.",
      "BLOCKED: canary-only over DNS/FTP/ICMP; never real data.",
      "Anomalous outbound protocols, DNS/ICMP volume.",
      risk=(EXFIL,), platforms=("network",)),
    T("T1567", "Exfiltration Over Web Service", "exfiltration",
      "Exfil to cloud/paste services.",
      "BLOCKED: canary-only to cloud/paste; never real data.",
      "Uploads to cloud-storage/paste sites.",
      risk=(EXFIL,), platforms=("network",)),
    T("T1011", "Exfiltration Over Other Network Medium", "exfiltration",
      "Exfil over Bluetooth/Wi-Fi/cellular.",
      "BLOCKED: canary-only over alt medium; never real data.",
      "Bluetooth/Wi-Fi/cellular exfil anomalies.",
      risk=(EXFIL,), platforms=("network",)),
    T("T1052", "Exfiltration Over Physical Medium", "exfiltration",
      "Exfil via removable media.",
      "BLOCKED: canary-only via removable media; never real data.",
      "USB mass-storage writes, removable-media policy.",
      risk=(EXFIL,), platforms=("physical",)),
    T("T1029", "Scheduled Transfer", "exfiltration",
      "Exfil on a schedule.",
      "BLOCKED: canary-only scheduled exfil; never real data.",
      "Periodic outbound bursts at fixed intervals.",
      risk=(EXFIL,), platforms=("network",)),
    T("T1030", "Data Transfer Size Limits", "exfiltration",
      "Exfil in fixed-size chunks.",
      "BLOCKED: canary-only chunked exfil; never real data.",
      "Uniform-sized outbound chunks.",
      risk=(EXFIL,), platforms=("network",)),

    # ── Impact (always blocked) ─────────────────────────────────────────────
    T("T1486", "Data Encrypted for Impact (Ransomware)", "impact",
      "Encrypt data to deny access.",
      "BLOCKED — destructive. Resilience objective only.",
      "Mass file rename/entropy spikes, shadow-copy deletion.",
      risk=(DESTROY,), platforms=("windows", "linux")),
    T("T1485", "Data Destruction", "impact",
      "Destroy data irrecoverably.",
      "BLOCKED — destructive. Resilience objective only.",
      "Mass deletes/overwrites, secure-wipe patterns.",
      risk=(DESTROY,)),
    T("T1490", "Inhibit System Recovery", "impact",
      "Delete backups/shadow copies.",
      "BLOCKED — destructive. Resilience objective only.",
      "vssadmin delete shadows, wbadmin delete, bcdedit.",
      risk=(DESTROY,), platforms=("windows",)),
    T("T1489", "Service Stop", "impact",
      "Stop critical services.",
      "BLOCKED — disruptive. Resilience objective only.",
      "Critical-service stop events (7036/7040).",
      risk=(DOS,)),
    T("T1498", "Network Denial of Service", "impact",
      "Flood the network.",
      "BLOCKED — DoS. Resilience objective only.",
      "Bandwidth saturation, availability monitors.",
      risk=(DOS,), platforms=("network",)),
    T("T1499", "Endpoint Denial of Service", "impact",
      "Exhaust endpoint resources.",
      "BLOCKED — DoS. Resilience objective only.",
      "Resource-exhaustion alerts.",
      risk=(DOS,)),
    T("T1491", "Defacement", "impact",
      "Deface web assets.",
      "BLOCKED — destructive. Resilience objective only.",
      "Unauthorized content changes on web assets.",
      risk=(DESTROY,), platforms=("web",)),
    T("T1561", "Disk Wipe", "impact",
      "Wipe disks / boot sectors.",
      "BLOCKED — destructive. Resilience objective only.",
      "Raw disk writes, MBR/boot-sector tampering.",
      risk=(DESTROY,)),
    T("T1496", "Resource Hijacking", "impact",
      "Hijack resources (e.g. mining).",
      "BLOCKED — abuse/DoS. Resilience objective only.",
      "Sustained CPU/GPU spikes, mining-pool traffic.",
      risk=(DOS,)),
]


# ── Adversary-group emulation playbooks (AI-curated kill chains) ─────────────
SCENARIOS = {
    "external_foothold": {
        "label": "External foothold (perimeter to access)",
        "adversary": "Generic external attacker",
        "description": "Internet-facing recon and exploitation to a first authenticated foothold.",
        "techniques": ["T1595", "T1595.002", "T1589", "T1190", "T1078"],
    },
    "phishing_to_persistence": {
        "label": "Phishing to persistence",
        "adversary": "Commodity phishing crew",
        "description": "Spearphishing attachment leads to code execution and a persistence foothold.",
        "techniques": ["T1566.001", "T1204.002", "T1059.001", "T1547.001", "T1053.005"],
    },
    "ad_compromise": {
        "label": "Active Directory compromise",
        "adversary": "Hands-on-keyboard intruder",
        "description": "Domain recon, Kerberoasting and credential reuse toward domain dominance.",
        "techniques": ["T1087.002", "T1018", "T1482", "T1558.003", "T1003.003", "T1550.002", "T1021.001"],
    },
    "full_kill_chain": {
        "label": "Full kill chain (recon to impact)",
        "adversary": "End-to-end emulation",
        "description": "All 14 tactics end to end; destructive endpoints are recorded as resilience objectives.",
        "techniques": ["T1595", "T1190", "T1059.004", "T1053.005", "T1068", "T1562.001",
                       "T1110.003", "T1046", "T1021.001", "T1005", "T1071.001", "T1041", "T1486"],
    },
    "apt29_cozy_bear": {
        "label": "APT29 (Cozy Bear / Nobelium) — stealthy espionage",
        "adversary": "APT29 (Russia, SVR)",
        "description": "Low-and-slow espionage: spearphishing link, stealthy persistence, mailbox collection and quiet HTTPS exfil.",
        "techniques": ["T1566.002", "T1204.002", "T1059.001", "T1547.001", "T1027",
                       "T1003.001", "T1021.006", "T1114", "T1071.001", "T1041"],
    },
    "fin7_carbanak": {
        "label": "FIN7 / Carbanak — financial intrusion",
        "adversary": "FIN7 (financially motivated)",
        "description": "Weaponized document, scripting and scheduled-task persistence toward POS/finance data collection.",
        "techniques": ["T1566.001", "T1204.002", "T1059.005", "T1053.005", "T1055",
                       "T1003.001", "T1087", "T1113", "T1074", "T1041"],
    },
    "apt28_fancy_bear": {
        "label": "APT28 (Fancy Bear) — credential-driven",
        "adversary": "APT28 (Russia, GRU)",
        "description": "Perimeter exploit / phishing, password spraying and Kerberoasting into lateral movement and exfil.",
        "techniques": ["T1190", "T1566.002", "T1078", "T1110.003", "T1558.003",
                       "T1021.001", "T1560", "T1048"],
    },
    "lazarus_supply_chain": {
        "label": "Lazarus — supply-chain intrusion",
        "adversary": "Lazarus Group (DPRK)",
        "description": "Supply-chain compromise, obfuscated execution, persistence and DNS/cloud exfil.",
        "techniques": ["T1195", "T1059.007", "T1547.001", "T1027", "T1003.001",
                       "T1021.002", "T1071.004", "T1567"],
    },
    "conti_ransomware_playbook": {
        "label": "Conti — ransomware affiliate playbook",
        "adversary": "Conti / ransomware affiliate",
        "description": "Phishing to beacon, AD recon, Kerberoasting and PtH, double-extortion exfil, then encryption (encryption + recovery-inhibition are blocked resilience objectives).",
        "techniques": ["T1566.002", "T1059.001", "T1071.001", "T1087.002", "T1558.003",
                       "T1550.002", "T1021.002", "T1560", "T1567", "T1490", "T1486"],
    },
    "ransomware_operator": {
        "label": "Ransomware operator (fast)",
        "adversary": "Big-game-hunting ransomware",
        "description": "Rapid intrusion to mass encryption; the destructive endpoints test backup/recovery resilience (blocked).",
        "techniques": ["T1566.001", "T1204.002", "T1059.001", "T1003.001", "T1018",
                       "T1021.002", "T1490", "T1486"],
    },
    "insider_threat": {
        "label": "Insider threat / data theft",
        "adversary": "Malicious insider",
        "description": "Legitimate access used to locate, collect and (blocked) exfiltrate sensitive data.",
        "techniques": ["T1078", "T1083", "T1005", "T1114", "T1052"],
    },
    "cloud_account_takeover": {
        "label": "Cloud account takeover",
        "adversary": "Cloud-focused attacker",
        "description": "Valid cloud credentials, service/account discovery, and cloud-storage collection/exfil.",
        "techniques": ["T1078.004", "T1526", "T1087", "T1530", "T1567"],
    },
    "web_app_to_dc": {
        "label": "Web app to domain controller",
        "adversary": "External-to-internal pivot",
        "description": "Public web exploit and web-shell vector, local credential discovery, and pivot toward AD.",
        "techniques": ["T1190", "T1505.003", "T1059.004", "T1552.001", "T1003.003",
                       "T1021.002", "T1018"],
    },
    "living_off_the_land": {
        "label": "Living-off-the-land (LOLBins)",
        "adversary": "Stealth/fileless operator",
        "description": "Native binaries and built-in tooling for execution, discovery and C2 — minimal new artifacts.",
        "techniques": ["T1059.001", "T1218", "T1047", "T1057", "T1082", "T1016",
                       "T1049", "T1071.001"],
    },
    "credential_access_sweep": {
        "label": "Credential-access sweep",
        "adversary": "Credential harvester",
        "description": "Spray, stuffing and credential-store techniques — real-credential capture is blocked.",
        "techniques": ["T1110.003", "T1110.004", "T1003.001", "T1552.001", "T1555", "T1558.003"],
    },
    "exfil_resilience_test": {
        "label": "Exfiltration / DLP resilience test",
        "adversary": "Data-theft emulation",
        "description": "Stage and archive canary data and attempt multiple exfil channels (all blocked) to test DLP and egress detection.",
        "techniques": ["T1005", "T1560", "T1041", "T1048", "T1567", "T1011"],
    },
}


def main():
    here = os.path.dirname(os.path.abspath(__file__))
    by_id = {t["id"] for t in TECHNIQUES}

    # Integrity: every scenario technique must exist in the library.
    missing = {}
    for name, sc in SCENARIOS.items():
        gaps = [tid for tid in sc["techniques"] if tid not in by_id]
        if gaps:
            missing[name] = gaps
    if missing:
        raise SystemExit(f"scenario references unknown technique ids: {missing}")

    # Duplicate-id check.
    ids = [t["id"] for t in TECHNIQUES]
    dupes = sorted({i for i in ids if ids.count(i) > 1})
    if dupes:
        raise SystemExit(f"duplicate technique ids: {dupes}")

    with open(os.path.join(here, "techniques.json"), "w", encoding="utf-8") as fh:
        json.dump(TECHNIQUES, fh, indent=2)
    with open(os.path.join(here, "scenarios.json"), "w", encoding="utf-8") as fh:
        json.dump(SCENARIOS, fh, indent=2)

    print(f"wrote techniques.json ({len(TECHNIQUES)} techniques) "
          f"and scenarios.json ({len(SCENARIOS)} scenarios)")


if __name__ == "__main__":
    main()
